'use strict';var h=void 0,u=null,TiltChrome=TiltChrome||{};
TiltChrome.BrowserOverlay={href:u,panel:u,canvas:u,s:u,initialize:function(){this.a();this.href===window.content.location.href?this.href=u:window.menubar.Id?window.setTimeout(this.create.bind(this),200):this.create()},create:function(){this.href=window.content.location.href;var a=window.content.innerWidth,b=window.content.innerHeight;z.p.aa=document.getElementById("tilt-panel-iframe").contentDocument;z.p.S=gBrowser.selectedBrowser.parentNode;this.panel=document.getElementById("tilt-panel");this.canvas=
z.p.fa(a,b,!0);this.s=new TiltChrome.bc(this.canvas)},a:function(){z.p.aa=u;z.p.S=u;if(this.panel!==u)this.panel.hidePopup(),this.panel=u;if(this.s!==u)this.s.a(),this.s=u;if(this.canvas!==u)this.canvas.parentNode.removeChild(this.canvas),this.canvas=u;window.QueryInterface(Ci.nsIInterfaceRequestor).getInterface(Ci.nsIDOMWindowUtils).garbageCollect()}};var z=z||{};
z.eb=function(a,b,c){this.Qb=this.Hb=this.Gb=this.Y=this.X=0;this.ua=C.create();this.La=C.create();this.ga=C.create();this.Ta=L.create([0,0,0,1]);this.t=L.create([0,0,0,1]);this.Ha=L.create([0,0,0,1]);this.Ia=0;this.Oc(a,b,c)};
z.eb.prototype={loop:function(a){a="undefined"===typeof a?0.25:z.e.Ga(a/100,0.01,0.99);this.Ia+=(this.Qb-this.Ia)*a;this.X+=(this.Gb-this.X)*a;this.Y+=(this.Hb-this.Y)*a;this.Wa(this.X,this.Y,this.width,this.height,this.Xa,this.La);C.tb(this.ua,this.La,this.ga);C.length(this.ga)>0?(this.t[0]=this.ga[0],this.t[1]=this.ga[1],this.t[2]=this.ga[2],this.t[3]=-C.A(this.ua,this.La)):(this.t[0]=0,this.t[1]=0,this.t[2]=0,this.t[3]=1);return{rotation:L.multiply(this.Ta,this.t,this.Ha),zoom:this.Ia}},Ac:function(a,
b){this.X=a;this.Y=b;this.Wa(this.X,this.Y,this.width,this.height,this.Xa,this.ua);L.set(this.Ha,this.Ta)},zc:function(a,b){this.Gb=a;this.Hb=b},Bc:function(a){this.Qb-=a*10},Wa:function(a,b,c,d,e,g){a=(a-c/2)/e;b=(b-d/2)/e;c=a*a+b*b;d=0;c>1?(d=1/Math.sqrt(c),g[0]=a*d,g[1]=b*d,g[2]=0):(g[0]=a,g[1]=b,g[2]=Math.sqrt(1-c))},Oc:function(a,b,c){this.width=a;this.height=b;this.Xa="undefined"!==typeof c?c:b;this.Wa(this.X,this.Y,this.width,this.height,this.Xa,this.ua);L.set(this.Ha,this.Ta)},a:function(){for(var a in this)delete this[a]}};
z=z||{};z.q=function(a,b,c){this.b=u;this.length=this.B=this.sa=0;"undefined"!==typeof a&&this.Ra(a,b,c)};z.q.prototype={Ra:function(a,b,c){"undefined"===typeof c&&(c=a.length/b);var d=new Float32Array(a),e=z.g;this.b=e.createBuffer();e.bindBuffer(e.ARRAY_BUFFER,this.b);e.bufferData(e.ARRAY_BUFFER,d,e.STATIC_DRAW);this.sa=b;this.B=c;this.length=a.length;b=0;for(c=a.length;b<c;b++)this[b]=a[b]},a:function(){for(var a in this)delete this[a]}};
z.$=function(a,b){this.b=u;this.B=this.sa=this.length=0;"undefined"!==typeof a&&this.Ra(a,b)};z.$.prototype={Ra:function(a,b){if("undefined"===typeof b)b=a.length;var c=new Uint16Array(a),d=z.g;this.b=d.createBuffer();d.bindBuffer(d.ELEMENT_ARRAY_BUFFER,this.b);d.bufferData(d.ELEMENT_ARRAY_BUFFER,c,d.STATIC_DRAW);this.sa=1;this.B=b;this.length=a.length;c=0;for(d=a.length;c<d;c++)this[c]=a[c]},a:function(){for(var a in this)delete this[a]}};z=z||{};z.g=u;z.z=u;z.za=-1;z.Aa=-1;z.ka={};
z.rb=function(){z.g=u;z.z=u;z.za=-1;z.Aa=-1;z.ka={}};z=z||{};z.Da=function(a,b){this.b=u;this.id=0;this.w=this.attributes=u;this.R={};arguments.length===2&&this.sc(a,b)};
z.Da.prototype={sc:function(a,b){this.b=z.Yb.create(a,b);this.id=this.b.id;this.attributes=this.b.attributes;this.w=this.b.w;delete this.b.id;delete this.b.attributes;delete this.b.w},Wb:function(){if(z.za!==this.id){z.za=this.id;var a=z.g;a.useProgram(this.b);if(z.Aa<this.attributes.length){z.Aa=this.attributes.length;for(var b in this.attributes)this.attributes.hasOwnProperty(b)&&b!=="length"&&a.enableVertexAttribArray(this.attributes[b])}}},Fa:function(a,b){var c=z.g,d=this.attributes[a],e=b.sa;
c.bindBuffer(c.ARRAY_BUFFER,b.b);c.vertexAttribPointer(d,e,c.FLOAT,!1,0,0)},la:function(a,b){var c=b[0]+b[1]+b[2]+(b[4]+b[5]+b[6])+(b[8]+b[9]+b[10])+(b[12]+b[13]+b[14]);this.R[a]!==c&&(this.R[a]=c,z.g.uniformMatrix4fv(this.w[a],!1,b))},pb:function(a,b){var c=b[3]*255<<24|b[0]*255<<16|b[1]*255<<8|b[2]*255;this.R[a]!==c&&(this.R[a]=c,z.g.uniform4fv(this.w[a],b))},bindTexture:function(a,b){if(this.R[a]!==b.id){this.R[a]=b.id;var c=z.g;c.bindTexture(c.TEXTURE_2D,b.b);c.uniform1i(this.w[a],0)}},a:function(){for(var a in this)try{"function"===
typeof this[a].a&&this[a].a()}catch(b){}finally{delete this[a]}}};z=z||{};
z.Yb={create:function(a,b){var c=this.compile(a,"x-shader/x-vertex"),d=this.compile(b,"x-shader/x-fragment");return this.link(c,d)},compile:function(a,b){var c=z.g,d;if("string"!==typeof a||a.length<1)return z.O.error(z.Q.get("compileShader.source.error")),u;if(b==="x-shader/x-vertex")d=c.createShader(c.VERTEX_SHADER);else if(b==="x-shader/x-fragment")d=c.createShader(c.FRAGMENT_SHADER);else return z.O.error(z.Q.Ma("compileShader.type.error"),[a]),u;c.shaderSource(d,a);c.compileShader(d);d.src=a;
return!c.getShaderParameter(d,c.COMPILE_STATUS)?(c=c.getShaderInfoLog(d),z.O.error(z.Q.Ma("compileShader.compile.error"),[c]),u):d},link:function(a,b){var c=z.g,d;d=c.createProgram();c.attachShader(d,a);c.attachShader(d,b);c.linkProgram(d);if(!c.getProgramParameter(d,c.LINK_STATUS))return d=c.getProgramInfoLog(d),z.O.error(z.Q.Ma("linkProgram.error",[d])),u;d.id=++this.count;c=[a.src,b.src].join(" ").replace(/#.*|[(){};,]/g," ").split(" ");return this.Vc(d,c)},Tc:function(a,b){return z.g.getAttribLocation(a,
b)},Wc:function(a,b){return z.g.getUniformLocation(a,b)},Uc:function(a,b){if("string"===typeof b){if(b.length<1)return u;var c;return(c=this.Tc(a,b))>=0?c:this.Wc(a,b)}return u},Vc:function(a,b){var c,d,e,g;a.attributes={};a.attributes.length=0;a.w={};c=0;for(d=b.length;c<d;c++)e=b[c],g=this.Uc(a,e),"number"===typeof g&&"undefined"===typeof a.attributes[e]&&(a.attributes[e]=g,a.attributes.length++),"object"===typeof g&&g instanceof WebGLUniformLocation&&"undefined"===typeof a.w[e]&&(a.w[e]=g);return a},
count:0};z=z||{};z.I=function(a,b,c){this.b=u;this.id=0;this.height=this.width=-1;this.loaded=!1;this.onload=c;"object"===typeof a?this.zb(a,b):"string"===typeof a?this.tc(a,b):z.O.error(z.Q.get("initTexture.source.error"))};
z.I.prototype={zb:function(a,b){this.b=z.ob.create(a,b);this.id=this.b.id;this.width=this.b.width;this.height=this.b.height;this.loaded=!0;if("undefined"!==typeof this.onload)this.onload();delete this.b.id;delete this.b.width;delete this.b.height;delete this.onload},tc:function(a,b){var c=this,d=new Image;d.src=a;d.onload=function(){c.zb(d,b);b=d=c=u}},a:function(){for(var a in this)try{"function"===typeof this[a].a&&this[a].a()}catch(b){}finally{delete this[a]}}};z=z||{};
z.ob={create:function(a,b){b=b||{};if("undefined"!==typeof z.ka[a.src])return z.ka[a.src];var c=z.g,d=z.ob.Pc(a,b),e=a.width,g=a.height,f=c.createTexture();c.bindTexture(c.TEXTURE_2D,f);c.texImage2D(c.TEXTURE_2D,0,c.RGBA,c.RGBA,c.UNSIGNED_BYTE,d);f.width=e;f.height=g;f.id=++this.count;this.Sc(b);c.bindTexture(c.TEXTURE_2D,u);"undefined"!==typeof a.src&&(z.ka[a.src]=f);return f},Sc:function(a){var b=z.g,c=b.TEXTURE_MIN_FILTER,d=b.TEXTURE_MAG_FILTER,e=b.TEXTURE_WRAP_S,g=b.TEXTURE_WRAP_T,a=a||{};a.L&&
b.bindTexture(b.TEXTURE_2D,a.L.b);"nearest"===a.Eb?b.texParameteri(b.TEXTURE_2D,c,b.NEAREST):"linear"===a.Eb&&a.Fb?b.texParameteri(b.TEXTURE_2D,c,b.LINEAR_MIPMAP_LINEAR):b.texParameteri(b.TEXTURE_2D,c,b.LINEAR);"nearest"===a.Cb?b.texParameteri(b.TEXTURE_2D,d,b.NEAREST):"linear"===a.Cb&&a.Fb?b.texParameteri(b.TEXTURE_2D,d,b.LINEAR_MIPMAP_LINEAR):b.texParameteri(b.TEXTURE_2D,d,b.LINEAR);"repeat"===a.Kd?b.texParameteri(b.TEXTURE_2D,e,b.REPEAT):b.texParameteri(b.TEXTURE_2D,e,b.CLAMP_TO_EDGE);"repeat"===
a.Ld?b.texParameteri(b.TEXTURE_2D,g,b.REPEAT):b.texParameteri(b.TEXTURE_2D,g,b.CLAMP_TO_EDGE);a.Fb&&b.generateMipmap(b.TEXTURE_2D)},Pc:function(a,b){var c=(a.src||"").indexOf("chrome://"),d=z.e.Ab(a.height);if(z.e.Ab(a.width)&&d&&c===-1)try{return a}finally{b=a=u}b=b||{};c=z.p.fa(z.e.Ib(a.width),z.e.Ib(a.height));d=c.getContext("2d");if(b.fill)d.fillStyle=b.fill,d.fillRect(0,0,c.width,c.height);d.drawImage(a,0,0,a.width,a.height,0,0,c.width,c.height);if(b.stroke)d.strokeStyle=b.stroke,d.lineWidth=
b.va,d.strokeRect(0,0,c.width,c.height);return c},Dd:function(a){z.g.pixelStorei(z.g.UNPACK_FLIP_Y_WEBGL,a)},count:0};z=z||{};z.N=function(a,b,c,d){this.x=a||0;this.y=b||0;this.width=c.width;this.height=c.height;this.K=c;this.G=[this.x,this.y,this.width,this.height];if("function"===typeof d)this.onclick=d};
z.N.prototype={update:function(){var a=this.K,b=this.G,c=this.x,d=this.y,e=this.width,g=this.height;b[0]=c;b[1]=d;b[2]=e;b[3]=g;a.x=c;a.y=d;a.width=e;a.height=g},l:function(a){a=a||z.z;this.K.l(a)},a:function(){for(var a in this)try{"function"===typeof this[a].a&&this[a].a()}catch(b){}finally{delete this[a]}}};z=z||{};z.lb=function(a,b){this.color=a;this.K=b;this.G=[b.x,b.y,b.width,b.height]};
z.lb.prototype={update:function(){var a=this.K,b=this.G,c=a.G;a.update();b[0]=c[0];b[1]=c[1];b[2]=c[2];b[3]=c[3]},l:function(a){a=a||z.z;a.fill(this.color);a.Ec();a.rect(0,0,a.width,a.height);this.K.l(a)},a:function(){for(var a in this)try{"function"===typeof this[a].a&&this[a].a()}catch(b){}finally{delete this[a]}}};z=z||{};
z.H=function(a,b,c,d,e,g){this.L=a;this.region=b||[0,0,a.width,a.height];this.x=c||0;this.y=d||0;this.width=e||this.region[2];this.height=g||this.region[3];this.G=[this.x,this.y,this.width,this.height];this.Ba=u};
z.H.prototype={update:function(){var a=this.G,b=this.y,c=this.width,d=this.height;a[0]=this.x;a[1]=b;a[2]=c;a[3]=d},l:function(a){a=a||z.z;if(this.Ba===u&&this.L.loaded){var b=this.region,c=this.L;this.Ba=new z.q([b[0]/c.width,b[1]/c.height,(b[0]+b[2])/c.width,b[1]/c.height,b[0]/c.width,(b[1]+b[3])/c.height,(b[0]+b[2])/c.width,(b[1]+b[3])/c.height],2)}a.wb(this.L,this.x,this.y,this.width,this.height,this.Ba)},a:function(){for(var a in this)try{"function"===typeof this[a].a&&this[a].a()}catch(b){}finally{delete this[a]}}};
z=z||{};z.kb=function(){this.elements=[]};
z.kb.prototype={push:function(){for(var a=0,b=arguments.length;a<b;a++)this.elements.push(arguments[a])},remove:function(){for(var a=0,b=arguments.length,c=-1;a<b;a++)(c=this.elements.indexOf(arguments[a]))!==-1&&this.elements.splice(c,1)},l:function(){var a=z.z,b=this.elements,c,d,e;a.ha();a.origin();a.ub();d=0;for(e=b.length;d<e;d++)c=b[d],c.update(),c.Oa||c.l(a)},click:function(a,b){var c=this.elements,d,e,g,f,j,i,l;i=0;for(l=c.length;i<l;i++)if(d=c[i],e=d.G||[-1,-1,-1,-1],g=e[0],f=e[1],j=e[2],
e=e[3],a>g&&a<g+j&&b>f&&b<f+e&&"function"===typeof d.onclick)d.onclick(a,b)},U:function(){},a:function(){for(var a in this.elements)try{"function"===typeof this.elements[a].a&&this.elements[a].a()}catch(b){}finally{delete this.elements[a]}for(var c in this)try{"function"===typeof this[c].a&&this[c].a()}catch(d){}finally{delete this[c]}}};
function ca(a){var b={indent_size:2,indent_char:" ",max_char:78,brace_style:"collapse"},c,d,e,b=b||{};c=b.ea||2;d=b.xb||" ";e=b.ma||"collapse";b=new function(){this.i=0;this.Hd="";this.T="CONTENT";this.c={parent:"parent1",xd:1,wd:""};this.M=this.Bb=this.wc=this.xa=this.r="";this.m={ya:"\n\r\t ".split(""),Xc:"br,input,link,meta,!doctype,basefont,base,area,hr,wbr,param,img,isindex,?xml,embed".split(","),ic:"head,body,/html".split(","),W:function(a,b){for(var c=0;c<b.length;c++)if(a===b[c])return!0;
return!1}};this.mc=function(){for(var a="",b=[],c=!1;this.input.charAt(this.i)!=="<";){if(this.i>=this.input.length)return b.length?b.join(""):["","TK_EOF"];a=this.input.charAt(this.i);this.i++;this.k++;if(this.m.W(a,this.m.ya))b.length&&(c=!0),this.k--;else{if(c){if(this.k>=this.Db){b.push("\n");for(c=0;c<this.u;c++)b.push(this.qa);this.k=0}else b.push(" "),this.k++;c=!1}b.push(a)}}return b.length?b.join(""):""};this.nc=function(){var a="",b=[],a=/<\/script>/igm;a.lastIndex=this.i;for(var c=(a=a.exec(this.input))?
a.index:this.input.length;this.i<c;){if(this.i>=this.input.length)return b.length?b.join(""):["","TK_EOF"];a=this.input.charAt(this.i);this.i++;b.push(a)}return b.length?b.join(""):""};this.Ya=function(a){this.c[a+"count"]?this.c[a+"count"]++:this.c[a+"count"]=1;this.c[a+this.c[a+"count"]]=this.u;this.c[a+this.c[a+"count"]+"parent"]=this.c.parent;this.c.parent=a+this.c[a+"count"]};this.Qc=function(a){if(this.c[a+"count"]){for(var b=this.c.parent;b;){if(a+this.c[a+"count"]===b)break;b=this.c[b+"parent"]}if(b)this.u=
this.c[a+this.c[a+"count"]],this.c.parent=this.c[b+"parent"];delete this.c[a+this.c[a+"count"]+"parent"];delete this.c[a+this.c[a+"count"]];this.c[a+"count"]==1?delete this.c[a+"count"]:this.c[a+"count"]--}};this.oc=function(){var a="",b=[],c=!1;do{if(this.i>=this.input.length)return b.length?b.join(""):["","TK_EOF"];a=this.input.charAt(this.i);this.i++;this.k++;if(this.m.W(a,this.m.ya))c=!0,this.k--;else{if(a==="'"||a==='"')if(!b[1]||b[1]!=="!")a+=this.ca(a),c=!0;a==="="&&(c=!1);if(b.length&&b[b.length-
1]!=="="&&a!==">"&&c)this.k>=this.Db?(this.Z(!1,b),this.k=0):(b.push(" "),this.k++),c=!1;b.push(a)}}while(a!==">");a=b.join("");c=a.substring(1,a.indexOf(" ")!=-1?a.indexOf(" "):a.indexOf(">")).toLowerCase();a.charAt(a.length-2)==="/"||this.m.W(c,this.m.Xc)?this.r="SINGLE":c==="script"?(this.Ya(c),this.r="SCRIPT"):c==="style"?(this.Ya(c),this.r="STYLE"):c==="a"?(a=this.ca("</a>",a),b.push(a),this.r="SINGLE"):c.charAt(0)==="!"?c.indexOf("[if")!=-1?(a.indexOf("!IE")!=-1&&(a=this.ca("--\>",a),b.push(a)),
this.r="START"):c.indexOf("[endif")!=-1?(this.r="END",this.dd()):(a=c.indexOf("[cdata[")!=-1?this.ca("]]\>",a):this.ca("--\>",a),b.push(a),this.r="SINGLE"):(c.charAt(0)==="/"?(this.Qc(c.substring(1)),this.r="END"):(this.Ya(c),this.r="START"),this.m.W(c,this.m.ic)&&this.Z(!0,this.J));return b.join("")};this.ca=function(a,b){if(b&&b.indexOf(a)!=-1)return"";var c="",d="",e=!0;do{if(this.i>=this.input.length)break;c=this.input.charAt(this.i);this.i++;if(this.m.W(c,this.m.ya)){if(!e){this.k--;continue}if(c===
"\n"||c==="\r"){d+="\n";for(c=0;c<this.u;c++)d+=this.qa;e=!1;this.k=0;continue}}d+=c;this.k++;e=!0}while(d.indexOf(a)==-1);return d};this.pc=function(){var a;if(this.Bb==="TK_TAG_SCRIPT"){a=this.nc();if(typeof a!=="string")return a;a=S(a,{indent_size:this.ea,indent_char:this.yb,indent_level:this.u,brace_style:this.ma});return[a.replace(/^[\t ]+/,""),"TK_CONTENT"]}if(this.T==="CONTENT")return a=this.mc(),typeof a!=="string"?a:[a,"TK_CONTENT"];if(this.T==="TAG")return a=this.oc(),typeof a!=="string"?
a:[a,"TK_TAG_"+this.r]};this.Ic=function(a,b,c,d){this.input=a||"";this.J=[];this.yb=b;this.qa="";this.ea=c;this.ma=d;this.u=0;this.Db=80;for(a=this.k=0;a<this.ea;a++)this.qa+=this.yb;this.Z=function(a,b){this.k=0;if(b&&b.length){if(!a)for(;this.m.W(b[b.length-1],this.m.ya);)b.pop();b.push("\n");for(var c=0;c<this.u;c++)b.push(this.qa)}};this.ta=function(a){this.J.push(a)};this.qc=function(){this.u++};this.dd=function(){this.u>0&&this.u--}};return this};for(b.Ic(a,d,c,e);;){a=b.pc();b.M=a[0];b.xa=
a[1];if(b.xa==="TK_EOF")break;switch(b.xa){case "TK_TAG_START":case "TK_TAG_SCRIPT":case "TK_TAG_STYLE":b.Z(!1,b.J);b.ta(b.M);b.qc();b.T="CONTENT";break;case "TK_TAG_END":b.Z(!0,b.J);b.ta(b.M);b.T="CONTENT";break;case "TK_TAG_SINGLE":b.Z(!1,b.J);b.ta(b.M);b.T="CONTENT";break;case "TK_CONTENT":b.M!==""&&(b.Z(!1,b.J),b.ta(b.M)),b.T="TAG"}b.Bb=b.xa;b.wc=b.M}return b.J.join("")}
function S(a,b){function c(a){for(a=typeof a==="undefined"?!1:a;r.length&&(r[r.length-1]===" "||r[r.length-1]===F||r[r.length-1]===V||a&&(r[r.length-1]==="\n"||r[r.length-1]==="\r"));)r.pop()}function d(a){return a.replace(/^\s\s*|\s\s*$/,"")}function e(){var a=M;M=!1;g();M=a}function g(a){k.oa=!1;if(!M||!n(k.mode))if(a=typeof a==="undefined"?!0:a,k.V=!1,c(),r.length){if(r[r.length-1]!=="\n"||!a)P=!0,r.push("\n");V&&r.push(V);for(a=0;a<k.v;a+=1)r.push(F);k.o&&k.D&&(aa===" "?r.push("    "):r.push(F))}}
function f(){if(k.oa)k.oa=!1;else{var a=" ";r.length&&(a=r[r.length-1]);a!==" "&&a!=="\n"&&a!==F&&r.push(" ")}}function j(){P=!1;k.oa=!1;r.push(x)}function i(){r.length&&r[r.length-1]===F&&r.pop()}function l(a){k&&G.push(k);k={Hc:k?k.mode:"BLOCK",mode:a,o:!1,F:!1,D:!1,Qa:!1,V:!1,Pa:!1,oa:!1,ra:-1,v:k?k.v+(k.o&&k.D?1:0):0,ab:0}}function n(a){return a==="[EXPRESSION]"||a==="[INDENTED-EXPRESSION]"}function t(a){return a==="[EXPRESSION]"||a==="[INDENTED-EXPRESSION]"||a==="(EXPRESSION)"}function p(){X=
k.mode==="DO_BLOCK";G.length>0&&(k=G.pop())}function q(a){for(var b=0;b<a.length;b++)if(d(a[b])[0]!="*")return!1;return!0}function m(a,b){for(var c=0;c<b.length;c+=1)if(b[c]===a)return!0;return!1}function y(){N=0;if(o>=H)return["","TK_EOF"];T=!1;var a=s.charAt(o);o+=1;if(M&&n(k.mode)){for(var b=0;m(a,I);){a==="\n"?(c(),r.push("\n"),P=!0,b=0):a==="\t"?b+=4:a!=="\r"&&(b+=1);if(o>=H)return["","TK_EOF"];a=s.charAt(o);o+=1}if(k.ra===-1)k.ra=b;if(P){var e;for(e=0;e<k.v+1;e+=1)r.push(F);if(k.ra!==-1)for(e=
0;e<b-k.ra;e++)r.push(" ")}}else{for(;m(a,I);){a==="\n"&&(N+=ba?N<=ba?1:0:1);if(o>=H)return["","TK_EOF"];a=s.charAt(o);o+=1}if(Z&&N>1)for(e=0;e<N;e+=1)g(e===0),P=!0;T=N>0}if(m(a,J)){if(o<H)for(;m(s.charAt(o),J);)if(a+=s.charAt(o),o+=1,o===H)break;if(o!==H&&a.match(/^[0-9]+[Ee]$/)&&(s.charAt(o)==="-"||s.charAt(o)==="+"))return b=s.charAt(o),o+=1,e=y(),a+=b+e[0],[a,"TK_WORD"];if(a==="in")return[a,"TK_OPERATOR"];T&&w!=="TK_OPERATOR"&&w!=="TK_EQUALS"&&!k.V&&(Z||v!=="var")&&g();return[a,"TK_WORD"]}if(a===
"("||a==="[")return[a,"TK_START_EXPR"];if(a===")"||a==="]")return[a,"TK_END_EXPR"];if(a==="{")return[a,"TK_START_BLOCK"];if(a==="}")return[a,"TK_END_BLOCK"];if(a===";")return[a,"TK_SEMICOLON"];if(a==="/"){b="";e=!0;if(s.charAt(o)==="*"){o+=1;if(o<H)for(;!(s.charAt(o)==="*"&&s.charAt(o+1)&&s.charAt(o+1)==="/")&&o<H;){a=s.charAt(o);b+=a;if(a==="\r"||a==="\n")e=!1;o+=1;if(o>=H)break}o+=2;return e?["/*"+b+"*/","TK_INLINE_COMMENT"]:["/*"+b+"*/","TK_BLOCK_COMMENT"]}if(s.charAt(o)==="/"){for(b=a;s.charAt(o)!==
"\r"&&s.charAt(o)!=="\n";)if(b+=s.charAt(o),o+=1,o>=H)break;o+=1;T&&g();return[b,"TK_COMMENT"]}}if(a==="'"||a==='"'||a==="/"&&(w==="TK_WORD"&&m(v,["return","do"])||w==="TK_COMMENT"||w==="TK_START_EXPR"||w==="TK_START_BLOCK"||w==="TK_END_BLOCK"||w==="TK_OPERATOR"||w==="TK_EQUALS"||w==="TK_EOF"||w==="TK_SEMICOLON")){b=a;e=!1;var f=a;if(o<H)if(b==="/")for(a=!1;e||a||s.charAt(o)!==b;){if(f+=s.charAt(o),e?e=!1:(e=s.charAt(o)==="\\",s.charAt(o)==="["?a=!0:s.charAt(o)==="]"&&(a=!1)),o+=1,o>=H)return[f,"TK_STRING"]}else for(;e||
s.charAt(o)!==b;)if(f+=s.charAt(o),e=e?!1:s.charAt(o)==="\\",o+=1,o>=H)return[f,"TK_STRING"];o+=1;f+=b;if(b==="/")for(;o<H&&m(s.charAt(o),J);)f+=s.charAt(o),o+=1;return[f,"TK_STRING"]}if(a==="#"){if(r.length===0&&s.charAt(o)==="!"){for(f=a;o<H&&a!="\n";)a=s.charAt(o),f+=a,o+=1;r.push(d(f)+"\n");g();return y()}b="#";if(o<H&&m(s.charAt(o),Q)){do a=s.charAt(o),b+=a,o+=1;while(o<H&&a!=="#"&&a!=="=");a!=="#"&&(s.charAt(o)==="["&&s.charAt(o+1)==="]"?(b+="[]",o+=2):s.charAt(o)==="{"&&s.charAt(o+1)==="}"&&
(b+="{}",o+=2));return[b,"TK_WORD"]}}if(a==="<"&&s.substring(o-1,o+3)==="<\!--")return o+=3,k.Qa=!0,["<\!--","TK_COMMENT"];if(a==="-"&&k.Qa&&s.substring(o-1,o+2)==="--\>")return k.Qa=!1,o+=2,T&&g(),["--\>","TK_COMMENT"];if(m(a,K)){for(;o<H&&m(a+s.charAt(o),K);)if(a+=s.charAt(o),o+=1,o>=H)break;return a==="="?[a,"TK_EQUALS"]:[a,"TK_OPERATOR"]}return[a,"TK_UNKNOWN"]}var s,r,x,w,v,A,B,k,G,F,I,J,K,o,E,Q,D,R,X,T,P,N,V="",b=b?b:{},O;if(b.Yc!==h&&b.Sa===h)b.Sa=b.Yc;b.ec!==h&&(O=b.ec?"expand":"collapse");
O=b.ma?b.ma:O?O:"collapse";B=b.ea?b.ea:2;var aa=b.xb?b.xb:" ",Z=typeof b.Gc==="undefined"?!0:b.Gc,ba=typeof b.yc==="undefined"?!1:b.yc,da=b.Sa==="undefined"?!1:b.Sa,M=typeof b.vc==="undefined"?!1:b.vc;P=!1;var H=a.length;for(F="";B>0;)F+=aa,B-=1;for(;a&&(a[0]===" "||a[0]==="\t");)V+=a[0],a=a.substring(1);s=a;B="";w="TK_START_EXPR";A=v="";r=[];X=!1;I="\n\r\t ".split("");J="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_$".split("");Q="0123456789".split("");K="+ - * / % & ++ -- = += -= *= /= %= == === != !== > < >= <= >> << >>> >>>= >>= <<= && &= | || ! !! , : ? ^ ^= |= ::".split(" ");
E="continue,try,throw,return,var,if,switch,case,default,for,while,break,function".split(",");G=[];l("BLOCK");for(o=0;;){R=y();x=R[0];R=R[1];if(R==="TK_EOF")break;switch(R){case "TK_START_EXPR":if(x==="["){if(w==="TK_WORD"||v===")"){m(v,E)&&f();l("(EXPRESSION)");j();break}if(k.mode==="[EXPRESSION]"||k.mode==="[INDENTED-EXPRESSION]")if(A==="]"&&v===","){if(k.mode==="[EXPRESSION]")k.mode="[INDENTED-EXPRESSION]",M||(k.v+=1);l("[EXPRESSION]");M||g()}else if(v==="["){if(k.mode==="[EXPRESSION]")k.mode="[INDENTED-EXPRESSION]",
M||(k.v+=1);l("[EXPRESSION]");M||g()}else l("[EXPRESSION]");else l("[EXPRESSION]")}else l("(EXPRESSION)");v===";"||w==="TK_START_BLOCK"?g():w==="TK_END_EXPR"||w==="TK_START_EXPR"||w==="TK_END_BLOCK"||v==="."||(w!=="TK_WORD"&&w!=="TK_OPERATOR"?f():B==="function"||B==="typeof"?da&&f():(m(v,E)||v==="catch")&&f());j();break;case "TK_END_EXPR":if(x==="]")if(M){if(v==="}"){i();j();p();break}}else if(k.mode==="[INDENTED-EXPRESSION]"&&v==="]"){p();g();j();break}p();j();break;case "TK_START_BLOCK":B==="do"?
l("DO_BLOCK"):l("BLOCK");O=="expand"?(w!=="TK_OPERATOR"&&(v==="return"||v==="="?f():g(!0)),j(),k.v+=1):(w!=="TK_OPERATOR"&&w!=="TK_START_EXPR"?w==="TK_START_BLOCK"?g():f():n(k.Hc)&&v===","&&(A==="}"?f():g()),k.v+=1,j());break;case "TK_END_BLOCK":p();O=="expand"?v!=="{"&&g():w==="TK_START_BLOCK"?P?i():c():n(k.mode)&&M?(M=!1,g(),M=!0):g();j();break;case "TK_WORD":if(X){f();j();f();X=!1;break}if(x==="function"){if(k.o)k.D=!0;if((P||v===";")&&v!=="{"){N=P?N:0;Z||(N=1);for(D=0;D<2-N;D++)g(!1)}}if(x===
"case"||x==="default"){v===":"?i():(k.v--,g(),k.v++);j();k.Pa=!0;break}D="NONE";w==="TK_END_BLOCK"?m(x.toLowerCase(),["else","catch","finally"])?O=="expand"||O=="end-expand"?D="NEWLINE":(D="SPACE",f()):D="NEWLINE":w==="TK_SEMICOLON"&&(k.mode==="BLOCK"||k.mode==="DO_BLOCK")?D="NEWLINE":w==="TK_SEMICOLON"&&t(k.mode)?D="SPACE":w==="TK_STRING"?D="NEWLINE":w==="TK_WORD"?(v==="else"&&c(!0),D="SPACE"):w==="TK_START_BLOCK"?D="NEWLINE":w==="TK_END_EXPR"&&(f(),D="NEWLINE");m(x,E)&&v!==")"&&(D=v=="else"?"SPACE":
"NEWLINE");if(k.V&&w==="TK_END_EXPR")k.V=!1;if(m(x.toLowerCase(),["else","catch","finally"]))w!=="TK_END_BLOCK"||O=="expand"||O=="end-expand"?g():(c(!0),f());else if(D==="NEWLINE"){if(!((w==="TK_START_EXPR"||v==="="||v===",")&&x==="function"))if(x==="function"&&v=="new")f();else if(v==="return"||v==="throw")f();else if(w!=="TK_END_EXPR"){if((w!=="TK_START_EXPR"||x!=="var")&&v!==":")x==="if"&&B==="else"&&v!=="{"?f():(k.o=!1,k.D=!1,g())}else if(m(x,E)&&v!=")")k.o=!1,k.D=!1,g()}else n(k.mode)&&v===","&&
A==="}"?g():D==="SPACE"&&f();j();B=x;if(x==="var")k.o=!0,k.D=!1,k.F=!1;if(x==="if")k.V=!0;if(x==="else")k.V=!1;break;case "TK_SEMICOLON":j();k.o=!1;k.D=!1;if(k.mode=="OBJECT")k.mode="BLOCK";break;case "TK_STRING":w==="TK_START_BLOCK"||w==="TK_END_BLOCK"||w==="TK_SEMICOLON"?g():w==="TK_WORD"&&f();j();break;case "TK_EQUALS":if(k.o)k.F=!0;f();j();f();break;case "TK_OPERATOR":D=A=!0;if(k.o&&x===","&&t(k.mode))k.F=!1;if(k.o&&x===",")if(k.F){j();k.D=!0;k.F=!1;g();break}else k.F=!1;if(v==="return"||v===
"throw"){f();j();break}if(x===":"&&k.Pa){j();g();k.Pa=!1;break}if(x==="::"){j();break}if(x===","){k.o?k.F?(j(),g(),k.F=!1):(j(),f()):w==="TK_END_BLOCK"&&k.mode!=="(EXPRESSION)"?(j(),k.mode==="OBJECT"&&v==="}"?g():f()):k.mode==="OBJECT"?(j(),g()):(j(),f());break}else m(x,["--","++","!"])||m(x,["-","+"])&&(m(w,["TK_START_BLOCK","TK_START_EXPR","TK_EQUALS","TK_OPERATOR"])||m(v,E))?(D=A=!1,v===";"&&t(k.mode)&&(A=!0),w==="TK_WORD"&&m(v,E)&&(A=!0),k.mode==="BLOCK"&&(v==="{"||v===";")&&g()):x==="."?A=!1:
x===":"?k.ab==0?(k.mode="OBJECT",A=!1):k.ab-=1:x==="?"&&(k.ab+=1);A&&f();j();D&&f();break;case "TK_BLOCK_COMMENT":A=x.split(/\x0a|\x0d\x0a/);if(q(A.slice(1))){g();r.push(A[0]);for(D=1;D<A.length;D++)g(),r.push(" "),r.push(d(A[D]))}else{A.length>1?(g(),c()):f();for(D=0;D<A.length;D++)r.push(A[D]),r.push("\n")}g();break;case "TK_INLINE_COMMENT":f();j();t(k.mode)?f():e();break;case "TK_COMMENT":T?g():f();j();e();break;case "TK_UNKNOWN":(v==="return"||v==="throw")&&f(),j()}A=v;w=R;v=x}return V+r.join("").replace(/[\n ]+$/,
"")}if(typeof exports!=="undefined")exports.pd=S;var U,C,W,Y,L;U=typeof Float32Array!="undefined"?Float32Array:typeof WebGLFloatArray!="undefined"?WebGLFloatArray:Array;
C={create:function(a){var b=new U(3);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];return b},add:function(a,b,c){if(!c||a==c)return a[0]+=b[0],a[1]+=b[1],a[2]+=b[2],a;c[0]=a[0]+b[0];c[1]=a[1]+b[1];c[2]=a[2]+b[2];return c},ja:function(a,b,c){if(!c||a==c)return a[0]-=b[0],a[1]-=b[1],a[2]-=b[2],a;c[0]=a[0]-b[0];c[1]=a[1]-b[1];c[2]=a[2]-b[2];return c},ud:function(a,b){b||(b=a);b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];return b},scale:function(a,b,c){if(!c||a==c)return a[0]*=
b,a[1]*=b,a[2]*=b,a;c[0]=a[0]*b;c[1]=a[1]*b;c[2]=a[2]*b;return c},normalize:function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],g=Math.sqrt(c*c+d*d+e*e);if(g){if(g==1)return b[0]=c,b[1]=d,b[2]=e,b}else return b[0]=0,b[1]=0,b[2]=0,b;g=1/g;b[0]=c*g;b[1]=d*g;b[2]=e*g;return b},tb:function(a,b,c){c||(c=a);var d=a[0],e=a[1],a=a[2],g=b[0],f=b[1],b=b[2];c[0]=e*b-a*f;c[1]=a*g-d*b;c[2]=d*f-e*g;return c},length:function(a){var b=a[0],c=a[1],a=a[2];return Math.sqrt(b*b+c*c+a*a)},A:function(a,b){return a[0]*b[0]+
a[1]*b[1]+a[2]*b[2]},direction:function(a,b,c){c||(c=a);var d=a[0]-b[0],e=a[1]-b[1],a=a[2]-b[2],b=Math.sqrt(d*d+e*e+a*a);if(!b)return c[0]=0,c[1]=0,c[2]=0,c;b=1/b;c[0]=d*b;c[1]=e*b;c[2]=a*b;return c},qd:function(a,b,c,d){d||(d=a);d[0]=a[0]+c*(b[0]-a[0]);d[1]=a[1]+c*(b[1]-a[1]);d[2]=a[2]+c*(b[2]-a[2]);return d},$a:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+"]"}};
W={create:function(a){var b=new U(9);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b[4]=a[4],b[5]=a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];return b},da:function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=1;a[5]=0;a[6]=0;a[7]=0;a[8]=1;return a},bd:function(a,b){if(!b||a==b){var c=a[1],d=a[2],e=a[5];a[1]=a[3];a[2]=a[6];a[3]=c;a[5]=a[7];a[6]=d;a[7]=e;return a}b[0]=a[0];b[1]=a[3];b[2]=a[6];b[3]=a[1];
b[4]=a[4];b[5]=a[7];b[6]=a[2];b[7]=a[5];b[8]=a[8];return b},Ub:function(a,b){b||(b=Y.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=0;b[4]=a[3];b[5]=a[4];b[6]=a[5];b[7]=0;b[8]=a[6];b[9]=a[7];b[10]=a[8];b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b},$a:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+"]"}};
Y={create:function(a){var b=new U(16);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b[4]=a[4],b[5]=a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8],b[9]=a[9],b[10]=a[10],b[11]=a[11],b[12]=a[12],b[13]=a[13],b[14]=a[14],b[15]=a[15]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=a[12];b[13]=a[13];b[14]=a[14];b[15]=a[15];return b},da:function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=
0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},bd:function(a,b){if(!b||a==b){var c=a[1],d=a[2],e=a[3],g=a[6],f=a[7],j=a[11];a[1]=a[4];a[2]=a[8];a[3]=a[12];a[4]=c;a[6]=a[9];a[7]=a[13];a[8]=d;a[9]=g;a[11]=a[14];a[12]=e;a[13]=f;a[14]=j;return a}b[0]=a[0];b[1]=a[4];b[2]=a[8];b[3]=a[12];b[4]=a[1];b[5]=a[5];b[6]=a[9];b[7]=a[13];b[8]=a[2];b[9]=a[6];b[10]=a[10];b[11]=a[14];b[12]=a[3];b[13]=a[7];b[14]=a[11];b[15]=a[15];return b},kd:function(a){var b=a[0],c=a[1],d=a[2],e=a[3],g=a[4],f=a[5],
j=a[6],i=a[7],l=a[8],n=a[9],t=a[10],p=a[11],q=a[12],m=a[13],y=a[14],a=a[15];return q*n*j*e-l*m*j*e-q*f*t*e+g*m*t*e+l*f*y*e-g*n*y*e-q*n*d*i+l*m*d*i+q*c*t*i-b*m*t*i-l*c*y*i+b*n*y*i+q*f*d*p-g*m*d*p-q*c*j*p+b*m*j*p+g*c*y*p-b*f*y*p-l*f*d*a+g*n*d*a+l*c*j*a-b*n*j*a-g*c*t*a+b*f*t*a},inverse:function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],g=a[3],f=a[4],j=a[5],i=a[6],l=a[7],n=a[8],t=a[9],p=a[10],q=a[11],m=a[12],y=a[13],s=a[14],r=a[15],x=c*j-d*f,w=c*i-e*f,v=c*l-g*f,A=d*i-e*j,B=d*l-g*j,k=e*l-g*i,G=n*y-t*m,F=
n*s-p*m,I=n*r-q*m,J=t*s-p*y,K=t*r-q*y,o=p*r-q*s,E=1/(x*o-w*K+v*J+A*I-B*F+k*G);b[0]=(j*o-i*K+l*J)*E;b[1]=(-d*o+e*K-g*J)*E;b[2]=(y*k-s*B+r*A)*E;b[3]=(-t*k+p*B-q*A)*E;b[4]=(-f*o+i*I-l*F)*E;b[5]=(c*o-e*I+g*F)*E;b[6]=(-m*k+s*v-r*w)*E;b[7]=(n*k-p*v+q*w)*E;b[8]=(f*K-j*I+l*G)*E;b[9]=(-c*K+d*I-g*G)*E;b[10]=(m*B-y*v+r*x)*E;b[11]=(-n*B+t*v-q*x)*E;b[12]=(-f*J+j*F-i*G)*E;b[13]=(c*J-d*F+e*G)*E;b[14]=(-m*A+y*w-s*x)*E;b[15]=(n*A-t*w+p*x)*E;return b}};
Y.Gd=function(a,b){b||(b=Y.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b};Y.ad=function(a,b){b||(b=W.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[4];b[4]=a[5];b[5]=a[6];b[6]=a[8];b[7]=a[9];b[8]=a[10];return b};
Y.Fd=function(a,b){var c=a[0],d=a[1],e=a[2],g=a[4],f=a[5],j=a[6],i=a[8],l=a[9],n=a[10],t=n*f-j*l,p=-n*g+j*i,q=l*g-f*i,m=c*t+d*p+e*q;if(!m)return u;m=1/m;b||(b=W.create());b[0]=t*m;b[1]=(-n*d+e*l)*m;b[2]=(j*d-e*f)*m;b[3]=p*m;b[4]=(n*c-e*i)*m;b[5]=(-j*c+e*g)*m;b[6]=q*m;b[7]=(-l*c+d*i)*m;b[8]=(f*c-d*g)*m;return b};
Y.multiply=function(a,b,c){c||(c=a);var d=a[0],e=a[1],g=a[2],f=a[3],j=a[4],i=a[5],l=a[6],n=a[7],t=a[8],p=a[9],q=a[10],m=a[11],y=a[12],s=a[13],r=a[14],a=a[15],x=b[0],w=b[1],v=b[2],A=b[3],B=b[4],k=b[5],G=b[6],F=b[7],I=b[8],J=b[9],K=b[10],o=b[11],E=b[12],Q=b[13],D=b[14],b=b[15];c[0]=x*d+w*j+v*t+A*y;c[1]=x*e+w*i+v*p+A*s;c[2]=x*g+w*l+v*q+A*r;c[3]=x*f+w*n+v*m+A*a;c[4]=B*d+k*j+G*t+F*y;c[5]=B*e+k*i+G*p+F*s;c[6]=B*g+k*l+G*q+F*r;c[7]=B*f+k*n+G*m+F*a;c[8]=I*d+J*j+K*t+o*y;c[9]=I*e+J*i+K*p+o*s;c[10]=I*g+J*l+K*
q+o*r;c[11]=I*f+J*n+K*m+o*a;c[12]=E*d+Q*j+D*t+b*y;c[13]=E*e+Q*i+D*p+b*s;c[14]=E*g+Q*l+D*q+b*r;c[15]=E*f+Q*n+D*m+b*a;return c};Y.Cc=function(a,b,c){c||(c=b);var d=b[0],e=b[1],b=b[2];c[0]=a[0]*d+a[4]*e+a[8]*b+a[12];c[1]=a[1]*d+a[5]*e+a[9]*b+a[13];c[2]=a[2]*d+a[6]*e+a[10]*b+a[14];return c};Y.Dc=function(a,b){var c;c||(c=b);var d=b[0],e=b[1],g=b[2],f=b[3];c[0]=a[0]*d+a[4]*e+a[8]*g+a[12]*f;c[1]=a[1]*d+a[5]*e+a[9]*g+a[13]*f;c[2]=a[2]*d+a[6]*e+a[10]*g+a[14]*f;c[3]=a[3]*d+a[7]*e+a[11]*g+a[15]*f};
Y.translate=function(a,b,c){var d=b[0],e=b[1],b=b[2];if(!c||a==c)return a[12]=a[0]*d+a[4]*e+a[8]*b+a[12],a[13]=a[1]*d+a[5]*e+a[9]*b+a[13],a[14]=a[2]*d+a[6]*e+a[10]*b+a[14],a[15]=a[3]*d+a[7]*e+a[11]*b+a[15],a;var g=a[0],f=a[1],j=a[2],i=a[3],l=a[4],n=a[5],t=a[6],p=a[7],q=a[8],m=a[9],y=a[10],s=a[11];c[0]=g;c[1]=f;c[2]=j;c[3]=i;c[4]=l;c[5]=n;c[6]=t;c[7]=p;c[8]=q;c[9]=m;c[10]=y;c[11]=s;c[12]=g*d+l*e+q*b+a[12];c[13]=f*d+n*e+m*b+a[13];c[14]=j*d+t*e+y*b+a[14];c[15]=i*d+p*e+s*b+a[15];return c};
Y.scale=function(a,b,c){var d=b[0],e=b[1],b=b[2];if(!c||a==c)return a[0]*=d,a[1]*=d,a[2]*=d,a[3]*=d,a[4]*=e,a[5]*=e,a[6]*=e,a[7]*=e,a[8]*=b,a[9]*=b,a[10]*=b,a[11]*=b,a;c[0]=a[0]*d;c[1]=a[1]*d;c[2]=a[2]*d;c[3]=a[3]*d;c[4]=a[4]*e;c[5]=a[5]*e;c[6]=a[6]*e;c[7]=a[7]*e;c[8]=a[8]*b;c[9]=a[9]*b;c[10]=a[10]*b;c[11]=a[11]*b;c[12]=a[12];c[13]=a[13];c[14]=a[14];c[15]=a[15];return c};
Y.rotate=function(a,b,c,d){var e=c[0],g=c[1],c=c[2],f=Math.sqrt(e*e+g*g+c*c);if(!f)return u;f!=1&&(f=1/f,e*=f,g*=f,c*=f);var j=Math.sin(b),i=Math.cos(b),l=1-i,b=a[0],f=a[1],n=a[2],t=a[3],p=a[4],q=a[5],m=a[6],y=a[7],s=a[8],r=a[9],x=a[10],w=a[11],v=e*e*l+i,A=g*e*l+c*j,B=c*e*l-g*j,k=e*g*l-c*j,G=g*g*l+i,F=c*g*l+e*j,I=e*c*l+g*j,e=g*c*l-e*j,g=c*c*l+i;d?a!=d&&(d[12]=a[12],d[13]=a[13],d[14]=a[14],d[15]=a[15]):d=a;d[0]=b*v+p*A+s*B;d[1]=f*v+q*A+r*B;d[2]=n*v+m*A+x*B;d[3]=t*v+y*A+w*B;d[4]=b*k+p*G+s*F;d[5]=f*
k+q*G+r*F;d[6]=n*k+m*G+x*F;d[7]=t*k+y*G+w*F;d[8]=b*I+p*e+s*g;d[9]=f*I+q*e+r*g;d[10]=n*I+m*e+x*g;d[11]=t*I+y*e+w*g;return d};Y.Nb=function(a,b,c){var d=Math.sin(b),b=Math.cos(b),e=a[4],g=a[5],f=a[6],j=a[7],i=a[8],l=a[9],n=a[10],t=a[11];c?a!=c&&(c[0]=a[0],c[1]=a[1],c[2]=a[2],c[3]=a[3],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[4]=e*b+i*d;c[5]=g*b+l*d;c[6]=f*b+n*d;c[7]=j*b+t*d;c[8]=e*-d+i*b;c[9]=g*-d+l*b;c[10]=f*-d+n*b;c[11]=j*-d+t*b;return c};
Y.Ob=function(a,b,c){var d=Math.sin(b),b=Math.cos(b),e=a[0],g=a[1],f=a[2],j=a[3],i=a[8],l=a[9],n=a[10],t=a[11];c?a!=c&&(c[4]=a[4],c[5]=a[5],c[6]=a[6],c[7]=a[7],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[0]=e*b+i*-d;c[1]=g*b+l*-d;c[2]=f*b+n*-d;c[3]=j*b+t*-d;c[8]=e*d+i*b;c[9]=g*d+l*b;c[10]=f*d+n*b;c[11]=j*d+t*b;return c};
Y.Pb=function(a,b,c){var d=Math.sin(b),b=Math.cos(b),e=a[0],g=a[1],f=a[2],j=a[3],i=a[4],l=a[5],n=a[6],t=a[7];c?a!=c&&(c[8]=a[8],c[9]=a[9],c[10]=a[10],c[11]=a[11],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[0]=e*b+i*d;c[1]=g*b+l*d;c[2]=f*b+n*d;c[3]=j*b+t*d;c[4]=e*-d+i*b;c[5]=g*-d+l*b;c[6]=f*-d+n*b;c[7]=j*-d+t*b;return c};
Y.kc=function(a,b,c,d,e,g,f){f||(f=Y.create());var j=b-a,i=d-c,l=g-e;f[0]=e*2/j;f[1]=0;f[2]=0;f[3]=0;f[4]=0;f[5]=e*2/i;f[6]=0;f[7]=0;f[8]=(b+a)/j;f[9]=(d+c)/i;f[10]=-(g+e)/l;f[11]=-1;f[12]=0;f[13]=0;f[14]=-(g*e*2)/l;f[15]=0;return f};Y.ha=function(a,b,c,d,e,g){a=c*Math.tan(a*Math.PI/360);b*=a;return Y.kc(-b,b,-a*(g?-1:1),a*(g?-1:1),c,d,e)};
Y.Kb=function(a,b,c,d,e,g,f){f||(f=Y.create());var j=b-a,i=d-c,l=g-e;f[0]=2/j;f[1]=0;f[2]=0;f[3]=0;f[4]=0;f[5]=2/i;f[6]=0;f[7]=0;f[8]=0;f[9]=0;f[10]=-2/l;f[11]=0;f[12]=-(a+b)/j;f[13]=-(d+c)/i;f[14]=-(g+e)/l;f[15]=1;return f};
Y.xc=function(a,b,c,d){d||(d=Y.create());var e=a[0],g=a[1],a=a[2],f=c[0],j=c[1],i=c[2],c=b[1],l=b[2];if(e==b[0]&&g==c&&a==l)return Y.da(d);var n,t,p,q,c=e-b[0],l=g-b[1],b=a-b[2];q=1/Math.sqrt(c*c+l*l+b*b);c*=q;l*=q;b*=q;n=j*b-i*l;i=i*c-f*b;f=f*l-j*c;(q=Math.sqrt(n*n+i*i+f*f))?(q=1/q,n*=q,i*=q,f*=q):f=i=n=0;j=l*f-b*i;t=b*n-c*f;p=c*i-l*n;(q=Math.sqrt(j*j+t*t+p*p))?(q=1/q,j*=q,t*=q,p*=q):p=t=j=0;d[0]=n;d[1]=j;d[2]=c;d[3]=0;d[4]=i;d[5]=t;d[6]=l;d[7]=0;d[8]=f;d[9]=p;d[10]=b;d[11]=0;d[12]=-(n*e+i*g+f*a);
d[13]=-(j*e+t*g+p*a);d[14]=-(c*e+l*g+b*a);d[15]=1;return d};Y.$a=function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+", "+a[9]+", "+a[10]+", "+a[11]+", "+a[12]+", "+a[13]+", "+a[14]+", "+a[15]+"]"};
L={create:function(a){var b=new U(4);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];return b},fd:function(a,b){var c=a[0],d=a[1],e=a[2];if(!b||a==b)return a[3]=-Math.sqrt(Math.abs(1-c*c-d*d-e*e)),a;b[0]=c;b[1]=d;b[2]=e;b[3]=-Math.sqrt(Math.abs(1-c*c-d*d-e*e));return b},inverse:function(a,b){if(!b||a==b)return a[0]*=-1,a[1]*=-1,a[2]*=-1,a;b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];b[3]=a[3];return b},length:function(a){var b=a[0],c=a[1],d=a[2],
a=a[3];return Math.sqrt(b*b+c*c+d*d+a*a)},normalize:function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],g=a[3],f=Math.sqrt(c*c+d*d+e*e+g*g);if(f==0)return b[0]=0,b[1]=0,b[2]=0,b[3]=0,b;f=1/f;b[0]=c*f;b[1]=d*f;b[2]=e*f;b[3]=g*f;return b},multiply:function(a,b,c){c||(c=a);var d=a[0],e=a[1],g=a[2],a=a[3],f=b[0],j=b[1],i=b[2],b=b[3];c[0]=d*b+a*f+e*i-g*j;c[1]=e*b+a*j+g*f-d*i;c[2]=g*b+a*i+d*j-e*f;c[3]=a*b-d*f-e*j-g*i;return c},Cc:function(a,b,c){c||(c=b);var d=b[0],e=b[1],g=b[2],b=a[0],f=a[1],j=a[2],a=a[3],
i=a*d+f*g-j*e,l=a*e+j*d-b*g,n=a*g+b*e-f*d,d=-b*d-f*e-j*g;c[0]=i*a+d*-b+l*-j-n*-f;c[1]=l*a+d*-f+n*-b-i*-j;c[2]=n*a+d*-j+i*-f-l*-b;return c},ad:function(a,b){b||(b=W.create());var c=a[0],d=a[1],e=a[2],g=a[3],f=c+c,j=d+d,i=e+e,l=c*f,n=c*j;c*=i;var t=d*j;d*=i;e*=i;f*=g;j*=g;g*=i;b[0]=1-(t+e);b[1]=n-g;b[2]=c+j;b[3]=n+g;b[4]=1-(l+e);b[5]=d-f;b[6]=c-j;b[7]=d+f;b[8]=1-(l+t);return b},Ub:function(a,b){b||(b=Y.create());var c=a[0],d=a[1],e=a[2],g=a[3],f=c+c,j=d+d,i=e+e,l=c*f,n=c*j;c*=i;var t=d*j;d*=i;e*=i;
f*=g;j*=g;g*=i;b[0]=1-(t+e);b[1]=n-g;b[2]=c+j;b[3]=0;b[4]=n+g;b[5]=1-(l+e);b[6]=d-f;b[7]=0;b[8]=c-j;b[9]=d+f;b[10]=1-(l+t);b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b},Ed:function(a,b,c,d){d||(d=a);var e=a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3];if(Math.abs(e)>=1)return d!=a&&(d[0]=a[0],d[1]=a[1],d[2]=a[2],d[3]=a[3]),d;var g=Math.acos(e),f=Math.sqrt(1-e*e);if(Math.abs(f)<0.0010)return d[0]=a[0]*0.5+b[0]*0.5,d[1]=a[1]*0.5+b[1]*0.5,d[2]=a[2]*0.5+b[2]*0.5,d[3]=a[3]*0.5+b[3]*0.5,d;e=Math.sin((1-c)*
g)/f;c=Math.sin(c*g)/f;d[0]=a[0]*e+b[0]*c;d[1]=a[1]*e+b[1]*c;d[2]=a[2]*e+b[2]*c;d[3]=a[3]*e+b[3]*c;return d},$a:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+"]"}};var $;$||($={});
(function(){function a(a){return a<10?"0"+a:a}function b(a){e.lastIndex=0;return e.test(a)?'"'+a.replace(e,function(a){var b=j[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,d){var e,j,q,m,y=g,s,r=d[a];r&&typeof r==="object"&&typeof r.toJSON==="function"&&(r=r.toJSON(a));typeof i==="function"&&(r=i.call(d,a,r));switch(typeof r){case "string":return b(r);case "number":return isFinite(r)?String(r):"null";case "boolean":case "null":return String(r);
case "object":if(!r)return"null";g+=f;s=[];if(Object.prototype.toString.apply(r)==="[object Array]"){m=r.length;for(e=0;e<m;e+=1)s[e]=c(e,r)||"null";q=s.length===0?"[]":g?"[\n"+g+s.join(",\n"+g)+"\n"+y+"]":"["+s.join(",")+"]";g=y;return q}if(i&&typeof i==="object"){m=i.length;for(e=0;e<m;e+=1)typeof i[e]==="string"&&(j=i[e],(q=c(j,r))&&s.push(b(j)+(g?": ":":")+q))}else for(j in r)Object.prototype.hasOwnProperty.call(r,j)&&(q=c(j,r))&&s.push(b(j)+(g?": ":":")+q);q=s.length===0?"{}":g?"{\n"+g+s.join(",\n"+
g)+"\n"+y+"}":"{"+s.join(",")+"}";g=y;return q}}if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":u},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var d=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g,f,j={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},i;if(typeof $.stringify!=="function")$.stringify=function(a,b,d){var e;f=g="";if(typeof d==="number")for(e=0;e<d;e+=1)f+=" ";else typeof d==="string"&&(f=d);if((i=b)&&typeof b!=="function"&&(typeof b!=="object"||typeof b.length!=="number"))throw Error("JSON.stringify");return c("",{"":a})};
if(typeof $.parse!=="function")$.parse=function(a,b){function c(a,d){var e,g,f=a[d];if(f&&typeof f==="object")for(e in f)Object.prototype.hasOwnProperty.call(f,e)&&(g=c(f,e),g!==h?f[e]=g:delete f[e]);return b.call(a,d,f)}var e,a=String(a);d.lastIndex=0;d.test(a)&&(a=a.replace(d,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),typeof b==="function"?c({"":e},""):e;throw new SyntaxError("JSON.parse");}})();z=z||{};
z.hb=function(a,b,c){a=a||1;b=b||1;c=c||1;this.d=new z.q([-0.5*a,-0.5*b,0.5*c,0.5*a,-0.5*b,0.5*c,0.5*a,0.5*b,0.5*c,-0.5*a,0.5*b,0.5*c,-0.5*a,0.5*b,0.5*c,0.5*a,0.5*b,0.5*c,0.5*a,0.5*b,-0.5*c,-0.5*a,0.5*b,-0.5*c,0.5*a,-0.5*b,-0.5*c,-0.5*a,-0.5*b,-0.5*c,-0.5*a,0.5*b,-0.5*c,0.5*a,0.5*b,-0.5*c,-0.5*a,-0.5*b,-0.5*c,0.5*a,-0.5*b,-0.5*c,0.5*a,-0.5*b,0.5*c,-0.5*a,-0.5*b,0.5*c,0.5*a,-0.5*b,0.5*c,0.5*a,-0.5*b,-0.5*c,0.5*a,0.5*b,-0.5*c,0.5*a,0.5*b,0.5*c,-0.5*a,-0.5*b,-0.5*c,-0.5*a,-0.5*b,0.5*c,-0.5*a,0.5*b,0.5*
c,-0.5*a,0.5*b,-0.5*c],3);this.wa=new z.q([0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1],2);this.j=new z.$([0,1,2,0,2,3,4,5,6,4,6,7,8,9,10,8,10,11,12,13,14,12,14,15,16,17,18,16,18,19,20,21,22,20,22,23])};z.hb.prototype={a:function(){for(var a in this)try{"function"===typeof this[a].a&&this[a].a()}catch(b){}finally{delete this[a]}}};z=z||{};
z.ib=function(a,b,c){a=a||1;b=b||1;c=c||1;this.d=new z.q([-0.5*a,-0.5*b,0.5*c,0.5*a,-0.5*b,0.5*c,0.5*a,0.5*b,0.5*c,-0.5*a,0.5*b,0.5*c,0.5*a,-0.5*b,-0.5*c,-0.5*a,-0.5*b,-0.5*c,-0.5*a,0.5*b,-0.5*c,0.5*a,0.5*b,-0.5*c],3);this.j=new z.$([0,1,1,2,2,3,3,0,4,5,5,6,6,7,7,4,0,5,1,4,2,7,3,6])};z.ib.prototype={a:function(){for(var a in this)try{"function"===typeof this[a].a&&this[a].a()}catch(b){}finally{delete this[a]}}};z=z||{};
z.mb=function(){this.d=new z.q([0,0,1,0,0,1,1,1],2);this.wa=new z.q([0,0,1,0,0,1,1,1],2)};z.mb.prototype={a:function(){for(var a in this)try{"function"===typeof this[a].a&&this[a].a()}catch(b){}finally{delete this[a]}}};z=z||{};z.nb=function(){this.d=new z.q([0,0,1,0,1,1,0,1,0,0],2)};z.nb.prototype={a:function(){for(var a in this)try{"function"===typeof this[a].a&&this[a].a()}catch(b){}finally{delete this[a]}}};z=z||{};
z.Ca=function(a,b){for(var c in a)this[c]=a[c];if("string"===typeof this.color)this.color=z.e.pa(this.color);else if("undefined"===typeof this.color)this.color=[1,1,1,1];if("undefined"===typeof this.Ka)this.Ka=z.z.TRIANGLES;if("function"===typeof b)this.l=b};
z.Ca.prototype={l:function(){var a=z.z,b=this.d,c=this.wa,d=this.j,e=this.color,g=this.L,f=this.Ka;g?a.Xb(b,c,e,g):a.bb(b,e);d?a.hc(f,d):a.na(f,b.B);this.h=Y.create(a.h);this.C=Y.create(a.C)},a:function(){for(var a in this)try{"function"===typeof this[a].a&&this[a].a()}catch(b){}finally{delete this[a]}}};z=z||{};
z.Ea=function(a,b,c){this.canvas=a;this.f=this.sb(a);z.rb();z.g=this.f;z.z=this;"undefined"!==typeof this.f?(this.TRIANGLES=this.f.TRIANGLES,this.TRIANGLE_STRIP=this.f.TRIANGLE_STRIP,this.TRIANGLE_FAN=this.f.TRIANGLE_FAN,this.LINES=this.f.LINES,this.LINE_STRIP=this.f.LINE_STRIP,this.LINE_LOOP=this.f.LINE_LOOP,this.POINTS=this.f.POINTS,this.COLOR_BUFFER_BIT=this.f.COLOR_BUFFER_BIT,this.DEPTH_BUFFER_BIT=this.f.DEPTH_BUFFER_BIT,this.STENCIL_BUFFER_BIT=this.f.STENCIL_BUFFER_BIT,"function"===typeof c&&
c()):(z.O.log(z.Q.get("initWebGL.error")),"function"===typeof b&&b());this.width=a.width;this.height=a.height;this.Va=[];this.h=Y.da(Y.create());this.C=Y.da(Y.create());this.clearColor=[0,0,0,0];this.Tb=[0,0,0,0];this.fillColor=[0,0,0,0];this.strokeColor=[0,0,0,0];this.Sb=0;this.fc=new z.Da(z.P.fb.cb,z.P.fb.Na);this.Zc=new z.Da(z.P.I.cb,z.P.I.Na);this.Za=new z.mb;this.Kc=new z.nb;this.gd=new z.hb;this.hd=new z.ib;this.Ua=0;this.currentTime=u;this.ba=this.jc=this.vb=this.elapsedTime=0;this.origin();
this.ha();this.ub()};
z.Ea.prototype={clear:function(a,b,c,d){var e=this.clearColor,g=this.f;if(e[0]!==a||e[1]!==b||e[2]!==c||e[3]!==d)e[0]=a,e[1]=b,e[2]=c,e[3]=d,g.clearColor(a,b,c,d),a*=255,b*=255,c*=255,d*=255,this.canvas.setAttribute("style","background: rgba("+a+", "+b+", "+c+", "+d+"); width: 100%; height: 100%;");g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT)},ha:function(){var a=this.width,b=this.height,c=a/2,d=b/2,e=d/Math.tan(z.e.ia(45)/2);Y.ha(45,a/b,e/10,e*100,this.C,!0);Y.translate(this.C,[-c,-d,-e])},Kb:function(){Y.Kb(0,
this.width,this.height,0,-1E3,1E3,this.C)},Mb:function(){this.Va.push(Y.create(this.h))},Lb:function(){if(this.Va.length>0)this.h=this.Va.pop()},origin:function(){Y.da(this.h)},transform:function(a){Y.multiply(this.h,a)},translate:function(a,b,c){Y.translate(this.h,[a,b,c||0])},rotate:function(a,b,c,d){Y.rotate(this.h,a,[b,c,d])},Nb:function(a){Y.Nb(this.h,a)},Ob:function(a){Y.Ob(this.h,a)},Pb:function(a){Y.Pb(this.h,a)},scale:function(a,b,c){Y.scale(this.h,[a,b,c||0])},ub:function(){this.dc("alpha");
this.Ja(!1);this.$c("#fff");this.fill("#fff");this.stroke("#000");this.va(1)},$c:function(a){this.Tb=z.e.pa(a)},fill:function(a){this.fillColor=z.e.pa(a)},stroke:function(a){this.strokeColor=z.e.pa(a)},Ec:function(){var a=this.strokeColor;a[0]=0;a[1]=0;a[2]=0;a[3]=0},va:function(a){if(this.Sb!==a)this.Sb=a,this.f.lineWidth(a)},dc:function(a){var b=this.f;"alpha"===a?(b.enable(b.BLEND),b.blendFunc(b.SRC_ALPHA,b.ONE_MINUS_SRC_ALPHA)):"add"===a||"additive"===a?(b.enable(b.BLEND),b.blendFunc(b.SRC_ALPHA,
b.ONE)):b.disable(b.BLEND)},Ja:function(a){var b=this.f;a?b.enable(b.DEPTH_TEST):b.disable(b.DEPTH_TEST)},bb:function(a,b){var c=this.fc;c.Wb();c.Fa("vertexPosition",a);c.la("mvMatrix",this.h);c.la("projMatrix",this.C);c.pb("color",b)},Xb:function(a,b,c,d){var e=this.Zc;e.Wb();e.Fa("vertexPosition",a);e.Fa("vertexTexCoord",b);e.la("mvMatrix",this.h);e.la("projMatrix",this.C);e.pb("color",c);e.bindTexture("sampler",d)},rect:function(a,b,c,d){var e=this.Za,g=this.Kc,f=this.fillColor,j=this.strokeColor;
"center"===this.Za.zd&&(a-=c/2,b-=d/2);this.Mb();this.translate(a,b,0);this.scale(c,d,1);j[3]&&(this.bb(g.d,j),this.na(this.LINE_STRIP,g.d.B));f[3]&&(this.bb(e.d,f),this.na(this.TRIANGLE_STRIP,e.d.B));this.Lb()},wb:function(a,b,c,d,e,g){var f=this.Za,j=this.Tb,g=g||f.wa;if("undefined"===typeof d||"undefined"===typeof e)d=a.width,e=a.height;"center"===f.nd&&(b-=d/2,c-=e/2);j[3]&&(this.Mb(),this.translate(b,c,0),this.scale(d,e,1),this.Xb(f.d,g,j,a),this.na(this.TRIANGLE_STRIP,f.d.B),this.Lb())},na:function(a,
b){this.f.drawArrays(a,0,b)},hc:function(a,b){var c=this.f;c.bindBuffer(c.ELEMENT_ARRAY_BUFFER,b.b);c.drawElements(a,b.B,c.UNSIGNED_SHORT,0)},sb:function(a,b){var c=["experimental-webgl","webgl","webkit-3d","moz-webgl"],d,e,g;e=0;for(g=c.length;e<g;++e){try{d=a.getContext(c[e],b)}catch(f){}if(d)break}return d},loop:function(a){window.Nc(a);this.origin();this.ha();this.currentTime=(new Date).getTime();if(this.Ua!==0)this.ba=this.currentTime-this.Ua,this.jc=1E3/this.ba;this.Ua=this.currentTime;this.elapsedTime+=
this.ba;this.vb++},a:function(){z.rb();for(var a in this)try{"function"===typeof this[a].a&&this[a].a()}catch(b){}finally{delete this[a]}}};window.Nc=window.Ad||window.Jd||window.sd||window.vd||window.td||function(a){window.setTimeout(a,1E3/60)};z=z||{};z.P={};z.P.fb={cb:"attribute vec3 vertexPosition;\nuniform mat4 mvMatrix;\nuniform mat4 projMatrix;\nvoid main(void) {\n    gl_Position = projMatrix * mvMatrix * vec4(vertexPosition, 1.0);\n}",Na:"#ifdef GL_ES\nprecision highp float;\n#endif\nuniform vec4 color;\nvoid main(void) {\n    gl_FragColor = color;\n}"};
z.P.I={cb:"attribute vec3 vertexPosition;\nattribute vec2 vertexTexCoord;\nuniform mat4 mvMatrix;\nuniform mat4 projMatrix;\nvarying vec2 texCoord;\nvoid main(void) {\n  gl_Position = projMatrix * mvMatrix * vec4(vertexPosition, 1.0);\n  texCoord = vertexTexCoord;\n}",Na:"#ifdef GL_ES\nprecision highp float;\n#endif\nuniform vec4 color;\nuniform sampler2D sampler;\nvarying vec2 texCoord;\nvoid main(void) {\n  vec4 tex = texture2D(sampler, vec2(texCoord.s, texCoord.t));\n  gl_FragColor = color * tex;\n}"};
z=z||{};
z.O={log:function(a){"undefined"===typeof a&&(a="undefined");try{Components.classes["@mozilla.org/consoleservice;1"].getService(Components.interfaces.nsIConsoleService).logStringMessage(a)}catch(b){alert(a)}},error:function(a,b,c,d,e,g,f){"undefined"===typeof a&&(a="undefined");try{var j=Components.classes["@mozilla.org/consoleservice;1"].getService(Components.interfaces.nsIConsoleService),i=Components.classes["@mozilla.org/scripterror;1"].createInstance(Components.interfaces.nsIScriptError);i.init(a,
b,c,d,e,g,f);j.logMessage(i)}catch(l){alert(a)}}};z.Q={qb:"tilt-string-bundle",get:function(a){if("undefined"===typeof a)return"undefined";var b=document.getElementById(this.qb);return b?b.getString(a):a},Ma:function(a,b){if("undefined"===typeof a)return"undefined";if("undefined"===typeof b)return a;var c=document.getElementById(this.qb);return c?c.ld(a,b):[a,b].join(" ")}};z=z||{};
z.p={aa:h,S:h,fa:function(a,b,c,d){if("undefined"===typeof this.aa)this.aa=document;if("undefined"===typeof this.S)this.S=document.body;var e=this.S,g=this.aa.createElement("canvas");g.setAttribute("style","width: 100%; height: 100%;");g.width=a;g.height=b;g.id=d;c&&this.append(g,e);return g},od:function(){var a=this.fa(window.innerWidth,window.innerHeight,!0);this.S.setAttribute("style","background:#000; margin: 0px; padding: 0px; overflow: hidden;");return a},append:function(a,b){b.appendChild(a)},
remove:function(a){a.parentNode.removeChild(a)},cd:function(a,b,c){function d(a,b,c){var i,l,n;i=0;for(l=b.childNodes.length;i<l;i++)n=b.childNodes[i],c>e&&(e=c),a(n,c),d(a,n,c+1)}var e=0;try{"function"===typeof a&&d(a,c||window.content.document,0),"function"===typeof b&&b(e)}finally{c=u}},lc:function(a){try{if(a.localName==="head"||a.localName==="body")throw new Exception;var b=a.getBoundingClientRect();return{x:b.left+window.content.pageXOffset,y:b.top+window.content.pageYOffset,width:b.width,height:b.height}}catch(c){var d=
b=0,e=a.clientWidth,g=a.clientHeight;if(a.offsetParent){do b+=a.offsetLeft,d+=a.offsetTop;while(a=a.offsetParent)}else{if(a.x)b=a.x;if(a.y)d=a.y}return{x:b,y:d,width:e,height:g}}finally{}},md:function(a){var b;a.nodeType===1?b="ELEMENT_NODE":a.nodeType===2?b="ATTRIBUTE_NODE":a.nodeType===3?b="TEXT_NODE":a.nodeType===4?b="CDATA_SECTION_NODE":a.nodeType===5?b="ENTITY_REFERENCE_NODE":a.nodeType===6?b="ENTITY_NODE":a.nodeType===7?b="PROCESSING_INSTRUCTION_NODE":a.nodeType===8?b="COMMENT_NODE":a.nodeType===
9?b="DOCUMENT_NODE":a.nodeType===10?b="DOCUMENT_TYPE_NODE":a.nodeType===11?b="DOCUMENT_FRAGMENT_NODE":a.nodeType===12&&(b="NOTATION_NODE");return b}};z=z||{};
z.e={ia:function(a){return a*Math.PI/180},jd:function(a){return a*180/Math.PI},Ab:function(a){return(a&a-1)===0},Ib:function(a){var b;--a;for(b=1;b<32;b<<=1)a|=a>>b;return a+1},Ga:function(a,b,c){return Math.max(b,Math.min(c,a))},yd:function(a,b,c){b*=0.5;var d=Math.sin(b),e=a[0]*d,g=a[1]*d,a=a[2]*d,b=Math.cos(b);return"undefined"===typeof c?[e,g,a,b]:(c[0]=e,c[1]=g,c[2]=a,c[3]=b,c)},Jc:function(a,b,c,d){var e;b*=0.5;a*=0.5;c*=0.5;e=Math.sin(b);var g=Math.sin(a),f=Math.sin(c),j=Math.cos(b),i=Math.cos(a),
l=Math.cos(c),b=e*i*l-j*g*f,a=j*g*l+e*i*f,c=j*i*f-e*g*l;e=j*i*l+e*g*f;return"undefined"===typeof d?[b,a,c,e]:(d[0]=b,d[1]=a,d[2]=c,d[3]=e,d)},Vb:function(a,b,c,d,e){var g=Y.create(),e=e||L.create();Y.multiply(d,c,g);Y.inverse(g);e[0]=+((a[0]-b[0])/b[2]*2-1);e[1]=-((a[1]-b[1])/b[3]*2-1);e[2]=2*a[2]-1;e[3]=1;Y.Dc(g,e);e[3]=1/e[3];e[0]*=e[3];e[1]*=e[3];e[2]*=e[3];return e},gc:function(a,b,c,d,e){this.Vb(a,c,d,e,a);this.Vb(b,c,d,e,b);return{position:a,xc:b,direction:C.normalize(C.ja(b,a))}},uc:function(a,
b,c,d,e){var g=C.create(),f=C.create(),j=C.create(),i=C.create(),l=C.create(),n=d.position,d=d.direction;"undefined"===typeof e&&(e=C.create());C.ja(b,a,g);C.ja(c,a,f);C.tb(g,f,j);if(j[0]===0&&j[1]===0&&j[2]===0)return-1;C.ja(n,a,l);b=-C.A(j,l);j=+C.A(j,d);if(Math.abs(j)<1.0E-4)return b==0?2:0;j=b/j;if(j<0)return 0;C.add(n,C.scale(d,j),e);n=C.A(g,g);d=C.A(g,f);j=C.A(f,f);C.ja(e,a,i);a=C.A(i,g);f=C.A(i,f);i=d*d-n*j;e=(d*f-j*a)/i;if(e<0||e>1)return 0;f=(d*a-n*f)/i;return f<0||e+f>1?0:1},pa:function(a){if("undefined"!==
typeof this[a])return this[a];var b,c,d,e;b=a.charAt(0)==="#"?a.substring(1):a;if(b.length===3)c=b.charAt(0),d=b.charAt(1),e=b.charAt(2),b=[c,c,d,d,e,e,"ff"].join("");else if(b.length===4)c=b.charAt(0),d=b.charAt(1),e=b.charAt(2),b=b.charAt(3),b=[c,c,d,d,e,e,b,b].join("");else if(b.match("^rgba")=="rgba")return b=b.substring(5,b.length-1).split(","),b[0]/=255,b[1]/=255,b[2]/=255,b[3]/=255,this[a]=b;else if(b.match("^rgb")=="rgb")return b=b.substring(4,b.length-1).split(","),b[0]/=255,b[1]/=255,b[2]/=
255,b[3]=1,this[a]=b;c=parseInt(b.substring(0,2),16)/255;d=parseInt(b.substring(2,4),16)/255;e=parseInt(b.substring(4,6),16)/255;b=b.length===6?1:parseInt(b.substring(6,8),16)/255;this[a]=[c,d,e,b];return[c,d,e,b]}};z=z||{};z.$b={trim:function(a){return a.replace(/^\s+|\s+$/g,"")},rd:function(a){return a.replace(/^\s+/,"")},Cd:function(a){return a.replace(/\s+$/,"")}};z=z||{};z.jb={};
z.jb.cc={rc:function(a){var b,c,d,e;b=z.p.fa();c=z.p.fa();b=z.Ea.prototype.sb(b);b=b.getParameter(b.MAX_TEXTURE_SIZE);d=a.innerWidth+a.scrollMaxX;e=a.innerHeight+a.scrollMaxY;d=z.e.Ga(d,0,b);b=z.e.Ga(e,0,b);c.width=d;c.height=b;c.getContext("2d").drawWindow(a,0,0,d,b,"#fff");return c}};z=z||{};
z.ed={Mc:function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.send(u);d.onreadystatechange=function(){d.readyState===4&&"function"===typeof b&&b(d,c)}},Bd:function(a,b,c){function d(d,f){e[f]=d;g++;g===a.length&&"function"===typeof b&&b(e,c)}var e=[],g=0,f,j;f=0;for(j=a.length;f<j;f++)this.Mc(a[f],d,f)}};TiltChrome=TiltChrome||{};TiltChrome.gb={};
TiltChrome.gb.Zb=function(){function a(){return y!==u?y[17]||y[224]:!1}var b=u,c=0,d=0,e=0,g=0,f=0,j=0,i=0,l=L.create(),n=!1,t=0,p=0,q=0,m=0,y=[];this.init=function(a){b=new z.eb(a.width,a.height);a.addEventListener("mousedown",s,!1);a.addEventListener("mouseup",r,!1);a.addEventListener("dblclick",x,!1);a.addEventListener("mousemove",w,!1);a.addEventListener("mouseout",v,!1);a.addEventListener("DOMMouseScroll",A,!1);window.addEventListener("keydown",B,!1);window.addEventListener("keyup",k,!1)};this.loop=
function(k){var B=this.s;if(n)if(a()||n===3){c=g+q-t;d=f+m-p;B.Rb(c,d,e);return}else b.zc(q,m);a()||(y[37]&&(c+=k/3),y[39]&&(c-=k/3),y[38]&&(d+=k/3),y[40]&&(d-=k/3),y[65]&&(i-=z.e.ia(k)/10),y[68]&&(i+=z.e.ia(k)/10),y[87]&&(j+=z.e.ia(k)/10),y[83]&&(j-=z.e.ia(k)/10));k=b.loop(k);z.e.Jc(i,j,0,l);B.Rc(L.multiply(l,k.rotation));B.Rb(c,d,e=k.zoom)};var s=function(e){e.preventDefault();e.stopPropagation();q=e.clientX-e.target.offsetLeft;m=e.clientY-e.target.offsetTop;t=q;p=m;g=c;f=d;n=e.which;!a()&&n!==
3&&b.Ac(q,m)}.bind(this),r=function(a){a.preventDefault();a.stopPropagation();var b=Math.abs(p-m);Math.abs(t-q)<2&&b<2&&this.s.click(q,m);q=a.clientX-a.target.offsetLeft;m=a.clientY-a.target.offsetTop;t=q;p=m;g=c;f=d;n=!1}.bind(this),x=function(a){a.preventDefault();a.stopPropagation();var b=Math.abs(p-m);Math.abs(t-q)<2&&b<2&&this.s.U(q,m);q=a.clientX-a.target.offsetLeft;m=a.clientY-a.target.offsetTop;t=q;p=m;g=c;f=d;n=!1}.bind(this),w=function(a){a.preventDefault();a.stopPropagation();q=a.clientX-
a.target.offsetLeft;m=a.clientY-a.target.offsetTop}.bind(this),v=function(a){a.preventDefault();a.stopPropagation();n=!1}.bind(this),A=function(a){a.preventDefault();a.stopPropagation();b.Bc(a.detail)}.bind(this),B=function(a){"open"!==TiltChrome.BrowserOverlay.panel.state&&(y[a.keyCode||a.which]=!0)}.bind(this),k=function(a){a=a.keyCode||a.which;y[a]=!1;if(a===27)"open"===TiltChrome.BrowserOverlay.panel.state?(TiltChrome.BrowserOverlay.panel.hidePopup(),y=[],n=!1):(TiltChrome.BrowserOverlay.a(),
TiltChrome.BrowserOverlay.href=u)}.bind(this);this.a=function(a){a.removeEventListener("mousedown",s,!1);a.removeEventListener("mouseup",r,!1);a.removeEventListener("dblclick",x,!1);a.removeEventListener("mousemove",w,!1);a.removeEventListener("mouseout",v,!1);a.removeEventListener("DOMMouseScroll",A,!1);window.removeEventListener("keydown",B,!1);window.removeEventListener("keyup",k,!1);k=B=A=v=w=x=r=s=u;b.a();y=l=b=u;for(var c in this)try{"function"===typeof this[c].a&&this[c].a()}catch(d){}finally{delete this[c]}}};
TiltChrome=TiltChrome||{};
TiltChrome.ac=function(){var a=u,b=u,c=u,d=u,e=u,g=u,f=u,j=u;this.init=function(i){a=new z.kb;b=new z.I("chrome://tilt/skin/tilt-gui.png",{Eb:"nearest",Cb:"nearest"});c=new z.lb("#0107",new z.H(b,[210,210,610,610]));c.Oa=!0;c.K.x=i.width/2-305;c.K.y=i.height/2-305;d=new z.N(i.width-320,0,new z.H(b,[945,0,70,40]));e=new z.N(i.width-240,0,new z.H(b,[945,40,65,40]));g=new z.N(i.width-160,0,new z.H(b,[945,80,50,40]));f=new z.N(i.width-50,0,new z.H(b,[945,120,45,40]));j=new z.N(0,0,new z.H(b,[0,148,42,
42]));b.onload=function(){this.s.Lc()}.bind(this);c.onclick=function(){c.Oa=!0};g.onclick=function(){c.Oa=!1};f.onclick=function(){TiltChrome.BrowserOverlay.a();TiltChrome.BrowserOverlay.href=u};a.push(c,j,d,e,g,f)};this.l=function(){a.l()};this.click=function(b,c){a.click(b,c)};this.U=function(b,c){a.U(b,c)};this.a=function(){a.a();a=u;for(var b in this)try{"function"===typeof this[b].a&&this[b].a()}catch(c){}finally{delete this[b]}}};TiltChrome=TiltChrome||{};
TiltChrome.bc=function(a){var b=new TiltChrome.gb.Zb,c=new TiltChrome.ac;function d(){j!==u&&(j.loop(d),l.loaded&&(i&&(i=!1,j.clear(0,0,0,1),j.Ja(!1),j.wb(l,0,0,j.width,j.height),j.translate(j.width/2,j.height/2-30,m.n[2]-t*25),j.transform(L.Ub(m.rotation)),j.translate(m.n[0],m.n[1],0),j.Ja(!0),j.va(2),p.l(),q.l(),c.l(j.ba)),"function"===typeof b.loop&&b.loop(j.ba)),(j.vb+1)%1E3===0&&window.QueryInterface(Ci.nsIInterfaceRequestor).getInterface(Ci.nsIDOMWindowUtils).garbageCollect())}function e(){var a=
[],b=[],c=[],d=[],e=[];z.p.cd(function(f,g){if(!(f.localName==="a"||f.localName==="b"||f.localName==="i"||f.localName==="u"||f.localName==="img")){var i=z.p.lc(f);if(i.width>4&&i.height>4){var k=i.x-j.width/2,l=i.y-j.height/2,m=g*t,p=i.width,q=i.height,i=a.length/3;a.push(k,l,m);a.push(k+p,l,m);a.push(k+p,l+q,m);a.push(k,l+q,m);a.push(k,l+q,m-t);a.push(k+p,l+q,m-t);a.push(k+p,l+q,m);a.push(k,l+q,m);a.push(k,l,m);a.push(k+p,l,m);a.push(k+p,l,m-t);a.push(k,l,m-t);b.push((k+j.width/2)/n.width,(l+j.height/
2)/n.height,(k+j.width/2+p)/n.width,(l+j.height/2)/n.height,(k+j.width/2+p)/n.width,(l+j.height/2+q)/n.height,(k+j.width/2)/n.width,(l+j.height/2+q)/n.height);for(k=0;k<2;k++)b.push(0,0,0,0,0,0,0,0);e.push({innerHTML:f.innerHTML,name:f.localName,className:f.className,id:f.id});c.push(i+0,i+1,i+2,i+0,i+2,i+3);c.push(i+4,i+5,i+6,i+4,i+6,i+7);c.push(i+8,i+9,i+10,i+8,i+10,i+11);c.push(i+10,i+9,i+6,i+10,i+6,i+5);c.push(i+8,i+11,i+4,i+8,i+4,i+7);d.push(i+0,i+1,i+1,i+2,i+2,i+3,i+3,i+0);d.push(i+4,i+5,i+
5,i+6,i+6,i+7,i+7,i+4);d.push(i+8,i+9,i+9,i+10,i+10,i+11,i+11,i+8);d.push(i+10,i+9,i+9,i+6,i+6,i+5,i+5,i+10);d.push(i+8,i+11,i+11,i+4,i+4,i+7,i+7,i+8)}}});p=new z.Ca({d:new z.q(a,3),wa:new z.q(b,2),j:new z.$(c),color:"#fff",L:n,Fc:e});q=new z.Ca({d:p.d,j:new z.$(d),color:"#999",Ka:j.LINES})}function g(){if(TiltChrome.BrowserOverlay.href!==window.content.location.href)TiltChrome.BrowserOverlay.href=u,TiltChrome.BrowserOverlay.a()}function f(){j.width=window.content.innerWidth;j.height=window.content.innerHeight;
i=!0;TiltChrome.BrowserOverlay.panel.hidePopup()}var j=new z.Ea(a),i=!0,l=u,n=u,t=15,p=u,q=u,m={n:C.create(),rotation:L.create()};(function(){var d=z.jb.cc.rc(window.content);n=new z.I(d,{fill:"white",stroke:"#aaa",va:8});e.call(this);gBrowser.tabContainer.addEventListener("TabClose",g,0);gBrowser.tabContainer.addEventListener("TabAttrModified",g,0);gBrowser.contentWindow.addEventListener("resize",f,0);b.s=this;"function"===typeof b.init&&b.init(a);c.s=this;"function"===typeof c.init&&c.init(a);l=
new z.I("chrome://tilt/skin/tilt-background.png");m.n=[0,0,0];m.rotation=[0,0,0,1]}).call(this);d.call(this);this.Lc=function(){i=!0};this.Rb=function(a,b,c){if(m.n[0]!=a||m.n[1]!=b||m.n[2]!=c)m.n[0]=a,m.n[1]=b,m.n[2]=c,i=!0};this.Rc=function(a){if(m.rotation[0]!=a[0]||m.rotation[1]!=a[1]||m.rotation[2]!=a[2]||m.rotation[3]!=a[3])L.set(a,m.rotation),i=!0};this.click=function(a,b){"function"===typeof c.click&&c.click(a,b);TiltChrome.BrowserOverlay.panel.hidePopup();window.content.focus();i=!0};this.U=
function(a,b){"function"===typeof c.U&&c.U(a,b);var d=z.e.gc([a,b,0],[a,b,1],[0,0,j.width,j.height],p.h,p.C),e=C.create(),f=[],g,l,m,k,n;g=0;for(l=p.j.length;g<l;g+=3)m=[p.d[p.j[g]*3],p.d[p.j[g]*3+1],p.d[p.j[g]*3+2]],k=[p.d[p.j[g+1]*3],p.d[p.j[g+1]*3+1],p.d[p.j[g+1]*3+2]],n=[p.d[p.j[g+2]*3],p.d[p.j[g+2]*3+1],p.d[p.j[g+2]*3+2]],z.e.uc(m,k,n,d,e)>0&&f.push({location:C.create(e),Jb:p.Fc[Math.floor(g/30)]});if(f.length>0)f.sort(function(a,b){return a.location[2]<b.location[2]?1:-1}),e=f[0],d=e.Jb,e=z.$b.trim(ca(e.Jb.innerHTML).replace(/</g,
"&lt;").replace(/>/g,"&gt;")),f=document.getElementById("tilt-panel-iframe"),g=f.contentDocument.getElementById("editor"),document.getElementById("tilt-panel-label").value=" <"+d.name+(d.className?' class="'+d.className+'"':"")+(d.id?' id="'+d.id+'"':"")+">",TiltChrome.BrowserOverlay.panel.openPopup(u,"overlap",window.innerWidth-f.width-21,window.innerHeight-f.height-77,!1,!1),g.innerHTML=e,f.contentWindow.onload();i=!0};this.a=function(){gBrowser.tabContainer.removeEventListener("TabClose",g,0);
gBrowser.tabContainer.removeEventListener("TabAttrModified",g,0);gBrowser.contentWindow.removeEventListener("resize",f,0);j.a();j=u;b.a(a);b=u;c.a(a);c=u;l.a();l=u;n.a();n=u;p.a();p=u;q.a();q=u;delete m.rotation;delete m.n;m=u;for(var d in this)try{"function"===typeof this[d].a&&this[d].a()}catch(e){}finally{delete this[d]}}};
