'use strict';var i=void 0,w=null,TiltChrome=TiltChrome||{};
TiltChrome.BrowserOverlay={href:w,panel:w,canvas:w,oa:w,initialize:function(){this.a();this.href===window.content.location.href?this.href=w:window.menubar.Ed?window.setTimeout(this.create.bind(this),100):this.create()},create:function(){this.href=window.content.location.href;var a=window.content.innerWidth,b=window.content.innerHeight;z.o.S=document.getElementById("tilt-panel-iframe").contentDocument;z.o.J=gBrowser.selectedBrowser.parentNode;this.panel=document.getElementById("tilt-panel");this.canvas=
z.o.W(a,b,!0);this.oa=new TiltChrome.Mb(this.canvas)},a:function(){z.o.S=w;z.o.J=w;if(this.panel!==w)this.panel.hidePopup(),this.panel=w;if(this.oa!==w)this.oa.a(),this.oa=w;if(this.canvas!==w)this.canvas.parentNode.removeChild(this.canvas),this.canvas=w;window.QueryInterface(Ci.nsIInterfaceRequestor).getInterface(Ci.nsIDOMWindowUtils).garbageCollect()}};var z=z||{};
z.Ua=function(a,b,c){this.Bb=this.ub=this.tb=this.O=this.N=0;this.ka=D.create();this.Ca=D.create();this.X=D.create();this.Ka=L.create([0,0,0,1]);this.r=L.create([0,0,0,1]);this.xa=L.create([0,0,0,1]);this.ya=0;this.Fc(a,b,c)};
z.Ua.prototype={loop:function(a){a="undefined"===typeof a?0.25:z.d.wa(a/100,0.01,0.99);this.ya+=(this.Bb-this.ya)*a;this.N+=(this.tb-this.N)*a;this.O+=(this.ub-this.O)*a;this.Na(this.N,this.O,this.width,this.height,this.Oa,this.Ca);D.ib(this.ka,this.Ca,this.X);D.length(this.X)>0?(this.r[0]=this.X[0],this.r[1]=this.X[1],this.r[2]=this.X[2],this.r[3]=-D.v(this.ka,this.Ca)):(this.r[0]=0,this.r[1]=0,this.r[2]=0,this.r[3]=1);return{rotation:L.multiply(this.Ka,this.r,this.xa),zoom:this.ya}},oc:function(a,
b){this.N=a;this.O=b;this.Na(this.N,this.O,this.width,this.height,this.Oa,this.ka);L.set(this.xa,this.Ka)},nc:function(a,b){this.tb=a;this.ub=b},pc:function(a){this.Bb-=a*10},Na:function(a,b,c,d,e,g){a=(a-c/2)/e;b=(b-d/2)/e;c=a*a+b*b;d=0;c>1?(d=1/Math.sqrt(c),g[0]=a*d,g[1]=b*d,g[2]=0):(g[0]=a,g[1]=b,g[2]=Math.sqrt(1-c))},Fc:function(a,b,c){this.width=a;this.height=b;this.Oa="undefined"!==typeof c?c:b;this.Na(this.N,this.O,this.width,this.height,this.Oa,this.ka);L.set(this.xa,this.Ka)},a:function(){for(var a in this)delete this[a]}};
z=z||{};z.q=function(a,b,c){this.b=w;this.length=this.P=this.ha=0;"undefined"!==typeof a&&this.Ia(a,b,c)};z.q.prototype={Ia:function(a,b,c){"undefined"===typeof c&&(c=a.length/b);var d=new Float32Array(a),e=z.f;this.b=e.createBuffer();e.bindBuffer(e.ARRAY_BUFFER,this.b);e.bufferData(e.ARRAY_BUFFER,d,e.STATIC_DRAW);this.ha=b;this.P=c;this.length=a.length;b=0;for(c=a.length;b<c;b++)this[b]=a[b]},a:function(){for(var a in this)delete this[a]}};
z.R=function(a,b){this.b=w;this.P=this.ha=this.length=0;"undefined"!==typeof a&&this.Ia(a,b)};z.R.prototype={Ia:function(a,b){if("undefined"===typeof b)b=a.length;var c=new Uint16Array(a),d=z.f;this.b=d.createBuffer();d.bindBuffer(d.ELEMENT_ARRAY_BUFFER,this.b);d.bufferData(d.ELEMENT_ARRAY_BUFFER,c,d.STATIC_DRAW);this.ha=1;this.P=b;this.length=a.length;c=0;for(d=a.length;c<d;c++)this[c]=a[c]},a:function(){for(var a in this)delete this[a]}};z=z||{};z.f=w;z.$=w;z.qa=-1;z.ra=-1;
z.gb=function(){z.f=w;z.$=w;z.qa=-1;z.ra=-1};z=z||{};z.ta=function(a,b){this.b=w;this.id=0;this.u=this.attributes=w;this.I={};arguments.length===2&&this.ec(a,b)};
z.ta.prototype={ec:function(a,b){this.b=z.Jb.create(a,b);this.id=this.b.id;this.attributes=this.b.attributes;this.u=this.b.u;delete this.b.id;delete this.b.attributes;delete this.b.u},Hb:function(){if(z.qa!==this.id){z.qa=this.id;var a=z.f;a.useProgram(this.b);if(z.ra<this.attributes.length){z.ra=this.attributes.length;for(var b in this.attributes)this.attributes.hasOwnProperty(b)&&b!=="length"&&a.enableVertexAttribArray(this.attributes[b])}}},va:function(a,b){var c=z.f,d=this.attributes[a],e=b.ha;
c.bindBuffer(c.ARRAY_BUFFER,b.b);c.vertexAttribPointer(d,e,c.FLOAT,!1,0,0)},aa:function(a,b){var c=b[0]+b[1]+b[2]+(b[4]+b[5]+b[6])+(b[8]+b[9]+b[10])+(b[12]+b[13]+b[14]);this.I[a]!==c&&(this.I[a]=c,z.f.uniformMatrix4fv(this.u[a],!1,b))},cb:function(a,b){var c=b[3]*255<<24|b[0]*255<<16|b[1]*255<<8|b[2]*255;this.I[a]!==c&&(this.I[a]=c,z.f.uniform4fv(this.u[a],b))},bindTexture:function(a,b){if(this.I[a]!==b.id){this.I[a]=b.id;var c=z.f;c.bindTexture(c.TEXTURE_2D,b.b);c.uniform1i(this.u[a],0)}},a:function(){for(var a in this)"function"===
typeof this[a].a&&this[a].a(),delete this[a]}};z=z||{};
z.Jb={create:function(a,b){var c=this.compile(a,"x-shader/x-vertex"),d=this.compile(b,"x-shader/x-fragment");return this.link(c,d)},compile:function(a,b){var c=z.f,d;if("string"!==typeof a||a.length<1)return z.D.error(z.G.get("compileShader.source.error")),w;if(b==="x-shader/x-vertex")d=c.createShader(c.VERTEX_SHADER);else if(b==="x-shader/x-fragment")d=c.createShader(c.FRAGMENT_SHADER);else return z.D.error(z.G.Da("compileShader.type.error"),[a]),w;c.shaderSource(d,a);c.compileShader(d);d.src=a;
return!c.getShaderParameter(d,c.COMPILE_STATUS)?(c=c.getShaderInfoLog(d),z.D.error(z.G.Da("compileShader.compile.error"),[c]),w):d},link:function(a,b){var c=z.f,d;d=c.createProgram();c.attachShader(d,a);c.attachShader(d,b);c.linkProgram(d);if(!c.getProgramParameter(d,c.LINK_STATUS))return d=c.getProgramInfoLog(d),z.D.error(z.G.Da("linkProgram.error",[d])),w;d.id=++this.count;c=[a.src,b.src].join(" ").replace(/#.*|[(){};,]/g," ").split(" ");return this.Mc(d,c)},Kc:function(a,b){return z.f.getAttribLocation(a,
b)},Nc:function(a,b){return z.f.getUniformLocation(a,b)},Lc:function(a,b){if("string"===typeof b){if(b.length<1)return w;var c;return(c=this.Kc(a,b))>=0?c:this.Nc(a,b)}return w},Mc:function(a,b){var c,d,e,g;a.attributes={};a.attributes.length=0;a.u={};c=0;for(d=b.length;c<d;c++)e=b[c],g=this.Lc(a,e),"number"===typeof g&&"undefined"===typeof a.attributes[e]&&(a.attributes[e]=g,a.attributes.length++),"object"===typeof g&&g instanceof WebGLUniformLocation&&"undefined"===typeof a.u[e]&&(a.u[e]=g);return a},
count:0};z=z||{};z.H=function(a,b){this.b=w;this.id=0;this.height=this.width=-1;this.loaded=!1;"object"===typeof a?this.nb(a,b):"string"===typeof a?this.fc(a,b):z.D.error(z.G.get("initTexture.source.error"))};
z.H.prototype={nb:function(a,b){this.b=z.bb.create(a,b);this.id=this.b.id;this.width=this.b.width;this.height=this.b.height;this.loaded=!0;delete this.b.id;delete this.b.width;delete this.b.height},fc:function(a,b,c){var d=this,e=new Image;e.src=a;e.onload=function(){d.nb(e,b);b=e=d=w;"function"===typeof c&&c()}},a:function(){for(var a in this)delete this[a]}};z=z||{};
z.bb={create:function(a,b){var b=b||{},c=z.f,d=z.bb.Gc(a,b),e=a.width,g=a.height,f=c.createTexture();c.bindTexture(c.TEXTURE_2D,f);c.texImage2D(c.TEXTURE_2D,0,c.RGBA,c.RGBA,c.UNSIGNED_BYTE,d);f.width=e;f.height=g;f.id=++this.count;this.Jc(b);c.bindTexture(c.TEXTURE_2D,w);return f},Jc:function(a){var b=z.f,c=b.TEXTURE_MIN_FILTER,d=b.TEXTURE_MAG_FILTER,e=b.TEXTURE_WRAP_S,g=b.TEXTURE_WRAP_T,a=a||{};a.Sa&&b.bindTexture(b.TEXTURE_2D,a.Sa.b);"nearest"===a.mc?b.texParameteri(b.TEXTURE_2D,c,b.NEAREST):"linear"===
a.mc&&a.sb?b.texParameteri(b.TEXTURE_2D,c,b.LINEAR_MIPMAP_LINEAR):b.texParameteri(b.TEXTURE_2D,c,b.LINEAR);"nearest"===a.kc?b.texParameteri(b.TEXTURE_2D,d,b.NEAREST):"linear"===a.kc&&a.sb?b.texParameteri(b.TEXTURE_2D,d,b.LINEAR_MIPMAP_LINEAR):b.texParameteri(b.TEXTURE_2D,d,b.LINEAR);"repeat"===a.Gd?b.texParameteri(b.TEXTURE_2D,e,b.REPEAT):b.texParameteri(b.TEXTURE_2D,e,b.CLAMP_TO_EDGE);"repeat"===a.Hd?b.texParameteri(b.TEXTURE_2D,g,b.REPEAT):b.texParameteri(b.TEXTURE_2D,g,b.CLAMP_TO_EDGE);a.sb&&b.generateMipmap(b.TEXTURE_2D)},
Gc:function(a,b){var c=(a.src||"").indexOf("chrome://"),d=z.d.pb(a.height);if(z.d.pb(a.width)&&d&&c===-1)try{return a}finally{b=a=w}b=b||{};c=z.o.W(z.d.vb(a.width),z.d.vb(a.height));d=c.getContext("2d");if(b.fill)d.fillStyle=b.fill,d.fillRect(0,0,c.width,c.height);d.drawImage(a,0,0,a.width,a.height,0,0,c.width,c.height);if(b.stroke)d.strokeStyle=b.stroke,d.lineWidth=b.la,d.strokeRect(0,0,c.width,c.height);return c},zd:function(a){z.f.pixelStorei(z.f.UNPACK_FLIP_Y_WEBGL,a)},count:0};
function ca(a){var b={indent_size:2,indent_char:" ",max_char:78,brace_style:"default"},c,d,e,b=b||{};c=b.V||4;d=b.lb||" ";e=b.ba||"collapse";b=new function(){this.i=0;this.Dd="";this.K="CONTENT";this.c={parent:"parent1",td:1,sd:""};this.C=this.qb=this.ic=this.na=this.p="";this.l={pa:"\n\r\t ".split(""),Oc:"br,input,link,meta,!doctype,basefont,base,area,hr,wbr,param,img,isindex,?xml,embed".split(","),Tb:"head,body,/html".split(","),M:function(a,b){for(var c=0;c<b.length;c++)if(a===b[c])return!0;return!1}};
this.Yb=function(){for(var a="",b=[],c=!1;this.input.charAt(this.i)!=="<";){if(this.i>=this.input.length)return b.length?b.join(""):["","TK_EOF"];a=this.input.charAt(this.i);this.i++;this.k++;if(this.l.M(a,this.l.pa))b.length&&(c=!0),this.k--;else{if(c){if(this.k>=this.rb){b.push("\n");for(c=0;c<this.s;c++)b.push(this.fa);this.k=0}else b.push(" "),this.k++;c=!1}b.push(a)}}return b.length?b.join(""):""};this.Zb=function(){var a="",b=[],a=/<\/script>/igm;a.lastIndex=this.i;for(var c=(a=a.exec(this.input))?
a.index:this.input.length;this.i<c;){if(this.i>=this.input.length)return b.length?b.join(""):["","TK_EOF"];a=this.input.charAt(this.i);this.i++;b.push(a)}return b.length?b.join(""):""};this.Pa=function(a){this.c[a+"count"]?this.c[a+"count"]++:this.c[a+"count"]=1;this.c[a+this.c[a+"count"]]=this.s;this.c[a+this.c[a+"count"]+"parent"]=this.c.parent;this.c.parent=a+this.c[a+"count"]};this.Hc=function(a){if(this.c[a+"count"]){for(var b=this.c.parent;b;){if(a+this.c[a+"count"]===b)break;b=this.c[b+"parent"]}if(b)this.s=
this.c[a+this.c[a+"count"]],this.c.parent=this.c[b+"parent"];delete this.c[a+this.c[a+"count"]+"parent"];delete this.c[a+this.c[a+"count"]];this.c[a+"count"]==1?delete this.c[a+"count"]:this.c[a+"count"]--}};this.$b=function(){var a="",b=[],c=!1;do{if(this.i>=this.input.length)return b.length?b.join(""):["","TK_EOF"];a=this.input.charAt(this.i);this.i++;this.k++;if(this.l.M(a,this.l.pa))c=!0,this.k--;else{if(a==="'"||a==='"')if(!b[1]||b[1]!=="!")a+=this.T(a),c=!0;a==="="&&(c=!1);if(b.length&&b[b.length-
1]!=="="&&a!==">"&&c)this.k>=this.rb?(this.Q(!1,b),this.k=0):(b.push(" "),this.k++),c=!1;b.push(a)}}while(a!==">");a=b.join("");c=a.substring(1,a.indexOf(" ")!=-1?a.indexOf(" "):a.indexOf(">")).toLowerCase();a.charAt(a.length-2)==="/"||this.l.M(c,this.l.Oc)?this.p="SINGLE":c==="script"?(this.Pa(c),this.p="SCRIPT"):c==="style"?(this.Pa(c),this.p="STYLE"):c==="a"?(a=this.T("</a>",a),b.push(a),this.p="SINGLE"):c.charAt(0)==="!"?c.indexOf("[if")!=-1?(a.indexOf("!IE")!=-1&&(a=this.T("--\>",a),b.push(a)),
this.p="START"):c.indexOf("[endif")!=-1?(this.p="END",this.Vc()):(a=c.indexOf("[cdata[")!=-1?this.T("]]\>",a):this.T("--\>",a),b.push(a),this.p="SINGLE"):(c.charAt(0)==="/"?(this.Hc(c.substring(1)),this.p="END"):(this.Pa(c),this.p="START"),this.l.M(c,this.l.Tb)&&this.Q(!0,this.B));return b.join("")};this.T=function(a,b){if(b&&b.indexOf(a)!=-1)return"";var c="",d="",e=!0;do{if(this.i>=this.input.length)break;c=this.input.charAt(this.i);this.i++;if(this.l.M(c,this.l.pa)){if(!e){this.k--;continue}if(c===
"\n"||c==="\r"){d+="\n";for(c=0;c<this.s;c++)d+=this.fa;e=!1;this.k=0;continue}}d+=c;this.k++;e=!0}while(d.indexOf(a)==-1);return d};this.ac=function(){var a;if(this.qb==="TK_TAG_SCRIPT"){a=this.Zb();if(typeof a!=="string")return a;a=S(a,{indent_size:this.V,indent_char:this.mb,indent_level:this.s,brace_style:this.ba});return[a.replace(/^[\t ]+/,""),"TK_CONTENT"]}if(this.K==="CONTENT")return a=this.Yb(),typeof a!=="string"?a:[a,"TK_CONTENT"];if(this.K==="TAG")return a=this.$b(),typeof a!=="string"?
a:[a,"TK_TAG_"+this.p]};this.zc=function(a,b,c,d){this.input=a||"";this.B=[];this.mb=b;this.fa="";this.V=c;this.ba=d;this.s=0;this.rb=80;for(a=this.k=0;a<this.V;a++)this.fa+=this.mb;this.Q=function(a,b){this.k=0;if(b&&b.length){if(!a)for(;this.l.M(b[b.length-1],this.l.pa);)b.pop();b.push("\n");for(var c=0;c<this.s;c++)b.push(this.fa)}};this.ja=function(a){this.B.push(a)};this.cc=function(){this.s++};this.Vc=function(){this.s>0&&this.s--}};return this};for(b.zc(a,d,c,e);;){a=b.ac();b.C=a[0];b.na=a[1];
if(b.na==="TK_EOF")break;switch(b.na){case "TK_TAG_START":case "TK_TAG_SCRIPT":case "TK_TAG_STYLE":b.Q(!1,b.B);b.ja(b.C);b.cc();b.K="CONTENT";break;case "TK_TAG_END":b.Q(!0,b.B);b.ja(b.C);b.K="CONTENT";break;case "TK_TAG_SINGLE":b.Q(!1,b.B);b.ja(b.C);b.K="CONTENT";break;case "TK_CONTENT":b.C!==""&&(b.Q(!1,b.B),b.ja(b.C)),b.K="TAG"}b.qb=b.na;b.ic=b.C}return b.B.join("")}
function S(a,b){function c(a){for(a=typeof a==="undefined"?!1:a;n.length&&(n[n.length-1]===" "||n[n.length-1]===G||n[n.length-1]===V||a&&(n[n.length-1]==="\n"||n[n.length-1]==="\r"));)n.pop()}function d(a){return a.replace(/^\s\s*|\s\s*$/,"")}function e(){var a=M;M=!1;g();M=a}function g(a){k.ca=!1;if(!M||!m(k.mode))if(a=typeof a==="undefined"?!0:a,k.L=!1,c(),n.length){if(n[n.length-1]!=="\n"||!a)P=!0,n.push("\n");V&&n.push(V);for(a=0;a<k.t;a+=1)n.push(G);k.n&&k.z&&(aa===" "?n.push("    "):n.push(G))}}
function f(){if(k.ca)k.ca=!1;else{var a=" ";n.length&&(a=n[n.length-1]);a!==" "&&a!=="\n"&&a!==G&&n.push(" ")}}function h(){P=!1;k.ca=!1;n.push(y)}function j(){n.length&&n[n.length-1]===G&&n.pop()}function l(a){k&&B.push(k);k={yc:k?k.mode:"BLOCK",mode:a,n:!1,A:!1,z:!1,Ga:!1,L:!1,Fa:!1,ca:!1,ga:-1,t:k?k.t+(k.n&&k.z?1:0):0,Ra:0}}function m(a){return a==="[EXPRESSION]"||a==="[INDENTED-EXPRESSION]"}function s(a){return a==="[EXPRESSION]"||a==="[INDENTED-EXPRESSION]"||a==="(EXPRESSION)"}function x(){X=
k.mode==="DO_BLOCK";B.length>0&&(k=B.pop())}function r(a){for(var b=0;b<a.length;b++)if(d(a[b])[0]!="*")return!1;return!0}function q(a,b){for(var c=0;c<b.length;c+=1)if(b[c]===a)return!0;return!1}function u(){N=0;if(o>=H)return["","TK_EOF"];T=!1;var a=p.charAt(o);o+=1;if(M&&m(k.mode)){for(var b=0;q(a,I);){a==="\n"?(c(),n.push("\n"),P=!0,b=0):a==="\t"?b+=4:a!=="\r"&&(b+=1);if(o>=H)return["","TK_EOF"];a=p.charAt(o);o+=1}if(k.ga===-1)k.ga=b;if(P){var e;for(e=0;e<k.t+1;e+=1)n.push(G);if(k.ga!==-1)for(e=
0;e<b-k.ga;e++)n.push(" ")}}else{for(;q(a,I);){a==="\n"&&(N+=ba?N<=ba?1:0:1);if(o>=H)return["","TK_EOF"];a=p.charAt(o);o+=1}if(Z&&N>1)for(e=0;e<N;e+=1)g(e===0),P=!0;T=N>0}if(q(a,J)){if(o<H)for(;q(p.charAt(o),J);)if(a+=p.charAt(o),o+=1,o===H)break;if(o!==H&&a.match(/^[0-9]+[Ee]$/)&&(p.charAt(o)==="-"||p.charAt(o)==="+"))return b=p.charAt(o),o+=1,e=u(),a+=b+e[0],[a,"TK_WORD"];if(a==="in")return[a,"TK_OPERATOR"];T&&t!=="TK_OPERATOR"&&t!=="TK_EQUALS"&&!k.L&&(Z||v!=="var")&&g();return[a,"TK_WORD"]}if(a===
"("||a==="[")return[a,"TK_START_EXPR"];if(a===")"||a==="]")return[a,"TK_END_EXPR"];if(a==="{")return[a,"TK_START_BLOCK"];if(a==="}")return[a,"TK_END_BLOCK"];if(a===";")return[a,"TK_SEMICOLON"];if(a==="/"){b="";e=!0;if(p.charAt(o)==="*"){o+=1;if(o<H)for(;!(p.charAt(o)==="*"&&p.charAt(o+1)&&p.charAt(o+1)==="/")&&o<H;){a=p.charAt(o);b+=a;if(a==="\r"||a==="\n")e=!1;o+=1;if(o>=H)break}o+=2;return e?["/*"+b+"*/","TK_INLINE_COMMENT"]:["/*"+b+"*/","TK_BLOCK_COMMENT"]}if(p.charAt(o)==="/"){for(b=a;p.charAt(o)!==
"\r"&&p.charAt(o)!=="\n";)if(b+=p.charAt(o),o+=1,o>=H)break;o+=1;T&&g();return[b,"TK_COMMENT"]}}if(a==="'"||a==='"'||a==="/"&&(t==="TK_WORD"&&q(v,["return","do"])||t==="TK_COMMENT"||t==="TK_START_EXPR"||t==="TK_START_BLOCK"||t==="TK_END_BLOCK"||t==="TK_OPERATOR"||t==="TK_EQUALS"||t==="TK_EOF"||t==="TK_SEMICOLON")){b=a;e=!1;var f=a;if(o<H)if(b==="/")for(a=!1;e||a||p.charAt(o)!==b;){if(f+=p.charAt(o),e?e=!1:(e=p.charAt(o)==="\\",p.charAt(o)==="["?a=!0:p.charAt(o)==="]"&&(a=!1)),o+=1,o>=H)return[f,"TK_STRING"]}else for(;e||
p.charAt(o)!==b;)if(f+=p.charAt(o),e=e?!1:p.charAt(o)==="\\",o+=1,o>=H)return[f,"TK_STRING"];o+=1;f+=b;if(b==="/")for(;o<H&&q(p.charAt(o),J);)f+=p.charAt(o),o+=1;return[f,"TK_STRING"]}if(a==="#"){if(n.length===0&&p.charAt(o)==="!"){for(f=a;o<H&&a!="\n";)a=p.charAt(o),f+=a,o+=1;n.push(d(f)+"\n");g();return u()}b="#";if(o<H&&q(p.charAt(o),Q)){do a=p.charAt(o),b+=a,o+=1;while(o<H&&a!=="#"&&a!=="=");a!=="#"&&(p.charAt(o)==="["&&p.charAt(o+1)==="]"?(b+="[]",o+=2):p.charAt(o)==="{"&&p.charAt(o+1)==="}"&&
(b+="{}",o+=2));return[b,"TK_WORD"]}}if(a==="<"&&p.substring(o-1,o+3)==="<\!--")return o+=3,k.Ga=!0,["<\!--","TK_COMMENT"];if(a==="-"&&k.Ga&&p.substring(o-1,o+2)==="--\>")return k.Ga=!1,o+=2,T&&g(),["--\>","TK_COMMENT"];if(q(a,K)){for(;o<H&&q(a+p.charAt(o),K);)if(a+=p.charAt(o),o+=1,o>=H)break;return a==="="?[a,"TK_EQUALS"]:[a,"TK_OPERATOR"]}return[a,"TK_UNKNOWN"]}var p,n,y,t,v,A,C,k,B,G,I,J,K,o,F,Q,E,R,X,T,P,N,V="",b=b?b:{},O;if(b.Pc!==i&&b.Ja===i)b.Ja=b.Pc;b.Pb!==i&&(O=b.Pb?"expand":"collapse");
O=b.ba?b.ba:O?O:"collapse";C=b.V?b.V:4;var aa=b.lb?b.lb:" ",Z=typeof b.xc==="undefined"?!0:b.xc,ba=typeof b.lc==="undefined"?!1:b.lc,da=b.Ja==="undefined"?!1:b.Ja,M=typeof b.hc==="undefined"?!1:b.hc;P=!1;var H=a.length;for(G="";C>0;)G+=aa,C-=1;for(;a&&(a[0]===" "||a[0]==="\t");)V+=a[0],a=a.substring(1);p=a;C="";t="TK_START_EXPR";A=v="";n=[];X=!1;I="\n\r\t ".split("");J="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_$".split("");Q="0123456789".split("");K="+ - * / % & ++ -- = += -= *= /= %= == === != !== > < >= <= >> << >>> >>>= >>= <<= && &= | || ! !! , : ? ^ ^= |= ::".split(" ");
F="continue,try,throw,return,var,if,switch,case,default,for,while,break,function".split(",");B=[];l("BLOCK");for(o=0;;){R=u();y=R[0];R=R[1];if(R==="TK_EOF")break;switch(R){case "TK_START_EXPR":if(y==="["){if(t==="TK_WORD"||v===")"){q(v,F)&&f();l("(EXPRESSION)");h();break}if(k.mode==="[EXPRESSION]"||k.mode==="[INDENTED-EXPRESSION]")if(A==="]"&&v===","){if(k.mode==="[EXPRESSION]")k.mode="[INDENTED-EXPRESSION]",M||(k.t+=1);l("[EXPRESSION]");M||g()}else if(v==="["){if(k.mode==="[EXPRESSION]")k.mode="[INDENTED-EXPRESSION]",
M||(k.t+=1);l("[EXPRESSION]");M||g()}else l("[EXPRESSION]");else l("[EXPRESSION]")}else l("(EXPRESSION)");v===";"||t==="TK_START_BLOCK"?g():t==="TK_END_EXPR"||t==="TK_START_EXPR"||t==="TK_END_BLOCK"||v==="."||(t!=="TK_WORD"&&t!=="TK_OPERATOR"?f():C==="function"||C==="typeof"?da&&f():(q(v,F)||v==="catch")&&f());h();break;case "TK_END_EXPR":if(y==="]")if(M){if(v==="}"){j();h();x();break}}else if(k.mode==="[INDENTED-EXPRESSION]"&&v==="]"){x();g();h();break}x();h();break;case "TK_START_BLOCK":C==="do"?
l("DO_BLOCK"):l("BLOCK");O=="expand"?(t!=="TK_OPERATOR"&&(v==="return"||v==="="?f():g(!0)),h(),k.t+=1):(t!=="TK_OPERATOR"&&t!=="TK_START_EXPR"?t==="TK_START_BLOCK"?g():f():m(k.yc)&&v===","&&(A==="}"?f():g()),k.t+=1,h());break;case "TK_END_BLOCK":x();O=="expand"?v!=="{"&&g():t==="TK_START_BLOCK"?P?j():c():m(k.mode)&&M?(M=!1,g(),M=!0):g();h();break;case "TK_WORD":if(X){f();h();f();X=!1;break}if(y==="function"){if(k.n)k.z=!0;if((P||v===";")&&v!=="{"){N=P?N:0;Z||(N=1);for(E=0;E<2-N;E++)g(!1)}}if(y===
"case"||y==="default"){v===":"?j():(k.t--,g(),k.t++);h();k.Fa=!0;break}E="NONE";t==="TK_END_BLOCK"?q(y.toLowerCase(),["else","catch","finally"])?O=="expand"||O=="end-expand"?E="NEWLINE":(E="SPACE",f()):E="NEWLINE":t==="TK_SEMICOLON"&&(k.mode==="BLOCK"||k.mode==="DO_BLOCK")?E="NEWLINE":t==="TK_SEMICOLON"&&s(k.mode)?E="SPACE":t==="TK_STRING"?E="NEWLINE":t==="TK_WORD"?(v==="else"&&c(!0),E="SPACE"):t==="TK_START_BLOCK"?E="NEWLINE":t==="TK_END_EXPR"&&(f(),E="NEWLINE");q(y,F)&&v!==")"&&(E=v=="else"?"SPACE":
"NEWLINE");if(k.L&&t==="TK_END_EXPR")k.L=!1;if(q(y.toLowerCase(),["else","catch","finally"]))t!=="TK_END_BLOCK"||O=="expand"||O=="end-expand"?g():(c(!0),f());else if(E==="NEWLINE"){if(!((t==="TK_START_EXPR"||v==="="||v===",")&&y==="function"))if(y==="function"&&v=="new")f();else if(v==="return"||v==="throw")f();else if(t!=="TK_END_EXPR"){if((t!=="TK_START_EXPR"||y!=="var")&&v!==":")y==="if"&&C==="else"&&v!=="{"?f():(k.n=!1,k.z=!1,g())}else if(q(y,F)&&v!=")")k.n=!1,k.z=!1,g()}else m(k.mode)&&v===","&&
A==="}"?g():E==="SPACE"&&f();h();C=y;if(y==="var")k.n=!0,k.z=!1,k.A=!1;if(y==="if")k.L=!0;if(y==="else")k.L=!1;break;case "TK_SEMICOLON":h();k.n=!1;k.z=!1;if(k.mode=="OBJECT")k.mode="BLOCK";break;case "TK_STRING":t==="TK_START_BLOCK"||t==="TK_END_BLOCK"||t==="TK_SEMICOLON"?g():t==="TK_WORD"&&f();h();break;case "TK_EQUALS":if(k.n)k.A=!0;f();h();f();break;case "TK_OPERATOR":E=A=!0;if(k.n&&y===","&&s(k.mode))k.A=!1;if(k.n&&y===",")if(k.A){h();k.z=!0;k.A=!1;g();break}else k.A=!1;if(v==="return"||v===
"throw"){f();h();break}if(y===":"&&k.Fa){h();g();k.Fa=!1;break}if(y==="::"){h();break}if(y===","){k.n?k.A?(h(),g(),k.A=!1):(h(),f()):t==="TK_END_BLOCK"&&k.mode!=="(EXPRESSION)"?(h(),k.mode==="OBJECT"&&v==="}"?g():f()):k.mode==="OBJECT"?(h(),g()):(h(),f());break}else q(y,["--","++","!"])||q(y,["-","+"])&&(q(t,["TK_START_BLOCK","TK_START_EXPR","TK_EQUALS","TK_OPERATOR"])||q(v,F))?(E=A=!1,v===";"&&s(k.mode)&&(A=!0),t==="TK_WORD"&&q(v,F)&&(A=!0),k.mode==="BLOCK"&&(v==="{"||v===";")&&g()):y==="."?A=!1:
y===":"?k.Ra==0?(k.mode="OBJECT",A=!1):k.Ra-=1:y==="?"&&(k.Ra+=1);A&&f();h();E&&f();break;case "TK_BLOCK_COMMENT":A=y.split(/\x0a|\x0d\x0a/);if(r(A.slice(1))){g();n.push(A[0]);for(E=1;E<A.length;E++)g(),n.push(" "),n.push(d(A[E]))}else{A.length>1?(g(),c()):f();for(E=0;E<A.length;E++)n.push(A[E]),n.push("\n")}g();break;case "TK_INLINE_COMMENT":f();h();s(k.mode)?f():e();break;case "TK_COMMENT":T?g():f();h();e();break;case "TK_UNKNOWN":(v==="return"||v==="throw")&&f(),h()}A=v;t=R;v=y}return V+n.join("").replace(/[\n ]+$/,
"")}if(typeof exports!=="undefined")exports.hd=S;var U,D,W,Y,L;U=typeof Float32Array!="undefined"?Float32Array:typeof WebGLFloatArray!="undefined"?WebGLFloatArray:Array;
D={create:function(a){var b=new U(3);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];return b},add:function(a,b,c){if(!c||a==c)return a[0]+=b[0],a[1]+=b[1],a[2]+=b[2],a;c[0]=a[0]+b[0];c[1]=a[1]+b[1];c[2]=a[2]+b[2];return c},Z:function(a,b,c){if(!c||a==c)return a[0]-=b[0],a[1]-=b[1],a[2]-=b[2],a;c[0]=a[0]-b[0];c[1]=a[1]-b[1];c[2]=a[2]-b[2];return c},pd:function(a,b){b||(b=a);b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];return b},scale:function(a,b,c){if(!c||a==c)return a[0]*=
b,a[1]*=b,a[2]*=b,a;c[0]=a[0]*b;c[1]=a[1]*b;c[2]=a[2]*b;return c},normalize:function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],g=Math.sqrt(c*c+d*d+e*e);if(g){if(g==1)return b[0]=c,b[1]=d,b[2]=e,b}else return b[0]=0,b[1]=0,b[2]=0,b;g=1/g;b[0]=c*g;b[1]=d*g;b[2]=e*g;return b},ib:function(a,b,c){c||(c=a);var d=a[0],e=a[1],a=a[2],g=b[0],f=b[1],b=b[2];c[0]=e*b-a*f;c[1]=a*g-d*b;c[2]=d*f-e*g;return c},length:function(a){var b=a[0],c=a[1],a=a[2];return Math.sqrt(b*b+c*c+a*a)},v:function(a,b){return a[0]*b[0]+
a[1]*b[1]+a[2]*b[2]},direction:function(a,b,c){c||(c=a);var d=a[0]-b[0],e=a[1]-b[1],a=a[2]-b[2],b=Math.sqrt(d*d+e*e+a*a);if(!b)return c[0]=0,c[1]=0,c[2]=0,c;b=1/b;c[0]=d*b;c[1]=e*b;c[2]=a*b;return c},jd:function(a,b,c,d){d||(d=a);d[0]=a[0]+c*(b[0]-a[0]);d[1]=a[1]+c*(b[1]-a[1]);d[2]=a[2]+c*(b[2]-a[2]);return d},Qa:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+"]"}};
W={create:function(a){var b=new U(9);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b[4]=a[4],b[5]=a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];return b},U:function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=1;a[5]=0;a[6]=0;a[7]=0;a[8]=1;return a},Tc:function(a,b){if(!b||a==b){var c=a[1],d=a[2],e=a[5];a[1]=a[3];a[2]=a[6];a[3]=c;a[5]=a[7];a[6]=d;a[7]=e;return a}b[0]=a[0];b[1]=a[3];b[2]=a[6];b[3]=a[1];
b[4]=a[4];b[5]=a[7];b[6]=a[2];b[7]=a[5];b[8]=a[8];return b},Fb:function(a,b){b||(b=Y.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=0;b[4]=a[3];b[5]=a[4];b[6]=a[5];b[7]=0;b[8]=a[6];b[9]=a[7];b[10]=a[8];b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b},Qa:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+"]"}};
Y={create:function(a){var b=new U(16);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b[4]=a[4],b[5]=a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8],b[9]=a[9],b[10]=a[10],b[11]=a[11],b[12]=a[12],b[13]=a[13],b[14]=a[14],b[15]=a[15]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=a[12];b[13]=a[13];b[14]=a[14];b[15]=a[15];return b},U:function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=0;
a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},Tc:function(a,b){if(!b||a==b){var c=a[1],d=a[2],e=a[3],g=a[6],f=a[7],h=a[11];a[1]=a[4];a[2]=a[8];a[3]=a[12];a[4]=c;a[6]=a[9];a[7]=a[13];a[8]=d;a[9]=g;a[11]=a[14];a[12]=e;a[13]=f;a[14]=h;return a}b[0]=a[0];b[1]=a[4];b[2]=a[8];b[3]=a[12];b[4]=a[1];b[5]=a[5];b[6]=a[9];b[7]=a[13];b[8]=a[2];b[9]=a[6];b[10]=a[10];b[11]=a[14];b[12]=a[3];b[13]=a[7];b[14]=a[11];b[15]=a[15];return b},cd:function(a){var b=a[0],c=a[1],d=a[2],e=a[3],g=a[4],f=a[5],
h=a[6],j=a[7],l=a[8],m=a[9],s=a[10],x=a[11],r=a[12],q=a[13],u=a[14],a=a[15];return r*m*h*e-l*q*h*e-r*f*s*e+g*q*s*e+l*f*u*e-g*m*u*e-r*m*d*j+l*q*d*j+r*c*s*j-b*q*s*j-l*c*u*j+b*m*u*j+r*f*d*x-g*q*d*x-r*c*h*x+b*q*h*x+g*c*u*x-b*f*u*x-l*f*d*a+g*m*d*a+l*c*h*a-b*m*h*a-g*c*s*a+b*f*s*a},inverse:function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],g=a[3],f=a[4],h=a[5],j=a[6],l=a[7],m=a[8],s=a[9],x=a[10],r=a[11],q=a[12],u=a[13],p=a[14],n=a[15],y=c*h-d*f,t=c*j-e*f,v=c*l-g*f,A=d*j-e*h,C=d*l-g*h,k=e*l-g*j,B=m*u-s*q,G=
m*p-x*q,I=m*n-r*q,J=s*p-x*u,K=s*n-r*u,o=x*n-r*p,F=1/(y*o-t*K+v*J+A*I-C*G+k*B);b[0]=(h*o-j*K+l*J)*F;b[1]=(-d*o+e*K-g*J)*F;b[2]=(u*k-p*C+n*A)*F;b[3]=(-s*k+x*C-r*A)*F;b[4]=(-f*o+j*I-l*G)*F;b[5]=(c*o-e*I+g*G)*F;b[6]=(-q*k+p*v-n*t)*F;b[7]=(m*k-x*v+r*t)*F;b[8]=(f*K-h*I+l*B)*F;b[9]=(-c*K+d*I-g*B)*F;b[10]=(q*C-u*v+n*y)*F;b[11]=(-m*C+s*v-r*y)*F;b[12]=(-f*J+h*G-j*B)*F;b[13]=(c*J-d*G+e*B)*F;b[14]=(-q*A+u*t-p*y)*F;b[15]=(m*A-s*t+x*y)*F;return b}};
Y.Cd=function(a,b){b||(b=Y.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b};Y.Sc=function(a,b){b||(b=W.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[4];b[4]=a[5];b[5]=a[6];b[6]=a[8];b[7]=a[9];b[8]=a[10];return b};
Y.Bd=function(a,b){var c=a[0],d=a[1],e=a[2],g=a[4],f=a[5],h=a[6],j=a[8],l=a[9],m=a[10],s=m*f-h*l,x=-m*g+h*j,r=l*g-f*j,q=c*s+d*x+e*r;if(!q)return w;q=1/q;b||(b=W.create());b[0]=s*q;b[1]=(-m*d+e*l)*q;b[2]=(h*d-e*f)*q;b[3]=x*q;b[4]=(m*c-e*j)*q;b[5]=(-h*c+e*g)*q;b[6]=r*q;b[7]=(-l*c+d*j)*q;b[8]=(f*c-d*g)*q;return b};
Y.multiply=function(a,b,c){c||(c=a);var d=a[0],e=a[1],g=a[2],f=a[3],h=a[4],j=a[5],l=a[6],m=a[7],s=a[8],x=a[9],r=a[10],q=a[11],u=a[12],p=a[13],n=a[14],a=a[15],y=b[0],t=b[1],v=b[2],A=b[3],C=b[4],k=b[5],B=b[6],G=b[7],I=b[8],J=b[9],K=b[10],o=b[11],F=b[12],Q=b[13],E=b[14],b=b[15];c[0]=y*d+t*h+v*s+A*u;c[1]=y*e+t*j+v*x+A*p;c[2]=y*g+t*l+v*r+A*n;c[3]=y*f+t*m+v*q+A*a;c[4]=C*d+k*h+B*s+G*u;c[5]=C*e+k*j+B*x+G*p;c[6]=C*g+k*l+B*r+G*n;c[7]=C*f+k*m+B*q+G*a;c[8]=I*d+J*h+K*s+o*u;c[9]=I*e+J*j+K*x+o*p;c[10]=I*g+J*l+K*
r+o*n;c[11]=I*f+J*m+K*q+o*a;c[12]=F*d+Q*h+E*s+b*u;c[13]=F*e+Q*j+E*x+b*p;c[14]=F*g+Q*l+E*r+b*n;c[15]=F*f+Q*m+E*q+b*a;return c};Y.qc=function(a,b,c){c||(c=b);var d=b[0],e=b[1],b=b[2];c[0]=a[0]*d+a[4]*e+a[8]*b+a[12];c[1]=a[1]*d+a[5]*e+a[9]*b+a[13];c[2]=a[2]*d+a[6]*e+a[10]*b+a[14];return c};Y.rc=function(a,b){var c;c||(c=b);var d=b[0],e=b[1],g=b[2],f=b[3];c[0]=a[0]*d+a[4]*e+a[8]*g+a[12]*f;c[1]=a[1]*d+a[5]*e+a[9]*g+a[13]*f;c[2]=a[2]*d+a[6]*e+a[10]*g+a[14]*f;c[3]=a[3]*d+a[7]*e+a[11]*g+a[15]*f};
Y.translate=function(a,b,c){var d=b[0],e=b[1],b=b[2];if(!c||a==c)return a[12]=a[0]*d+a[4]*e+a[8]*b+a[12],a[13]=a[1]*d+a[5]*e+a[9]*b+a[13],a[14]=a[2]*d+a[6]*e+a[10]*b+a[14],a[15]=a[3]*d+a[7]*e+a[11]*b+a[15],a;var g=a[0],f=a[1],h=a[2],j=a[3],l=a[4],m=a[5],s=a[6],x=a[7],r=a[8],q=a[9],u=a[10],p=a[11];c[0]=g;c[1]=f;c[2]=h;c[3]=j;c[4]=l;c[5]=m;c[6]=s;c[7]=x;c[8]=r;c[9]=q;c[10]=u;c[11]=p;c[12]=g*d+l*e+r*b+a[12];c[13]=f*d+m*e+q*b+a[13];c[14]=h*d+s*e+u*b+a[14];c[15]=j*d+x*e+p*b+a[15];return c};
Y.scale=function(a,b,c){var d=b[0],e=b[1],b=b[2];if(!c||a==c)return a[0]*=d,a[1]*=d,a[2]*=d,a[3]*=d,a[4]*=e,a[5]*=e,a[6]*=e,a[7]*=e,a[8]*=b,a[9]*=b,a[10]*=b,a[11]*=b,a;c[0]=a[0]*d;c[1]=a[1]*d;c[2]=a[2]*d;c[3]=a[3]*d;c[4]=a[4]*e;c[5]=a[5]*e;c[6]=a[6]*e;c[7]=a[7]*e;c[8]=a[8]*b;c[9]=a[9]*b;c[10]=a[10]*b;c[11]=a[11]*b;c[12]=a[12];c[13]=a[13];c[14]=a[14];c[15]=a[15];return c};
Y.rotate=function(a,b,c,d){var e=c[0],g=c[1],c=c[2],f=Math.sqrt(e*e+g*g+c*c);if(!f)return w;f!=1&&(f=1/f,e*=f,g*=f,c*=f);var h=Math.sin(b),j=Math.cos(b),l=1-j,b=a[0],f=a[1],m=a[2],s=a[3],x=a[4],r=a[5],q=a[6],u=a[7],p=a[8],n=a[9],y=a[10],t=a[11],v=e*e*l+j,A=g*e*l+c*h,C=c*e*l-g*h,k=e*g*l-c*h,B=g*g*l+j,G=c*g*l+e*h,I=e*c*l+g*h,e=g*c*l-e*h,g=c*c*l+j;d?a!=d&&(d[12]=a[12],d[13]=a[13],d[14]=a[14],d[15]=a[15]):d=a;d[0]=b*v+x*A+p*C;d[1]=f*v+r*A+n*C;d[2]=m*v+q*A+y*C;d[3]=s*v+u*A+t*C;d[4]=b*k+x*B+p*G;d[5]=f*
k+r*B+n*G;d[6]=m*k+q*B+y*G;d[7]=s*k+u*B+t*G;d[8]=b*I+x*e+p*g;d[9]=f*I+r*e+n*g;d[10]=m*I+q*e+y*g;d[11]=s*I+u*e+t*g;return d};Y.yb=function(a,b,c){var d=Math.sin(b),b=Math.cos(b),e=a[4],g=a[5],f=a[6],h=a[7],j=a[8],l=a[9],m=a[10],s=a[11];c?a!=c&&(c[0]=a[0],c[1]=a[1],c[2]=a[2],c[3]=a[3],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[4]=e*b+j*d;c[5]=g*b+l*d;c[6]=f*b+m*d;c[7]=h*b+s*d;c[8]=e*-d+j*b;c[9]=g*-d+l*b;c[10]=f*-d+m*b;c[11]=h*-d+s*b;return c};
Y.zb=function(a,b,c){var d=Math.sin(b),b=Math.cos(b),e=a[0],g=a[1],f=a[2],h=a[3],j=a[8],l=a[9],m=a[10],s=a[11];c?a!=c&&(c[4]=a[4],c[5]=a[5],c[6]=a[6],c[7]=a[7],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[0]=e*b+j*-d;c[1]=g*b+l*-d;c[2]=f*b+m*-d;c[3]=h*b+s*-d;c[8]=e*d+j*b;c[9]=g*d+l*b;c[10]=f*d+m*b;c[11]=h*d+s*b;return c};
Y.Ab=function(a,b,c){var d=Math.sin(b),b=Math.cos(b),e=a[0],g=a[1],f=a[2],h=a[3],j=a[4],l=a[5],m=a[6],s=a[7];c?a!=c&&(c[8]=a[8],c[9]=a[9],c[10]=a[10],c[11]=a[11],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[0]=e*b+j*d;c[1]=g*b+l*d;c[2]=f*b+m*d;c[3]=h*b+s*d;c[4]=e*-d+j*b;c[5]=g*-d+l*b;c[6]=f*-d+m*b;c[7]=h*-d+s*b;return c};
Y.Vb=function(a,b,c,d,e,g,f){f||(f=Y.create());var h=b-a,j=d-c,l=g-e;f[0]=e*2/h;f[1]=0;f[2]=0;f[3]=0;f[4]=0;f[5]=e*2/j;f[6]=0;f[7]=0;f[8]=(b+a)/h;f[9]=(d+c)/j;f[10]=-(g+e)/l;f[11]=-1;f[12]=0;f[13]=0;f[14]=-(g*e*2)/l;f[15]=0;return f};Y.ia=function(a,b,c,d,e,g){a=c*Math.tan(a*Math.PI/360);b*=a;return Y.Vb(-b,b,-a*(g?-1:1),a*(g?-1:1),c,d,e)};
Y.xb=function(a,b,c,d,e,g,f){f||(f=Y.create());var h=b-a,j=d-c,l=g-e;f[0]=2/h;f[1]=0;f[2]=0;f[3]=0;f[4]=0;f[5]=2/j;f[6]=0;f[7]=0;f[8]=0;f[9]=0;f[10]=-2/l;f[11]=0;f[12]=-(a+b)/h;f[13]=-(d+c)/j;f[14]=-(g+e)/l;f[15]=1;return f};
Y.jc=function(a,b,c,d){d||(d=Y.create());var e=a[0],g=a[1],a=a[2],f=c[0],h=c[1],j=c[2],c=b[1],l=b[2];if(e==b[0]&&g==c&&a==l)return Y.U(d);var m,s,x,r,c=e-b[0],l=g-b[1],b=a-b[2];r=1/Math.sqrt(c*c+l*l+b*b);c*=r;l*=r;b*=r;m=h*b-j*l;j=j*c-f*b;f=f*l-h*c;(r=Math.sqrt(m*m+j*j+f*f))?(r=1/r,m*=r,j*=r,f*=r):f=j=m=0;h=l*f-b*j;s=b*m-c*f;x=c*j-l*m;(r=Math.sqrt(h*h+s*s+x*x))?(r=1/r,h*=r,s*=r,x*=r):x=s=h=0;d[0]=m;d[1]=h;d[2]=c;d[3]=0;d[4]=j;d[5]=s;d[6]=l;d[7]=0;d[8]=f;d[9]=x;d[10]=b;d[11]=0;d[12]=-(m*e+j*g+f*a);
d[13]=-(h*e+s*g+x*a);d[14]=-(c*e+l*g+b*a);d[15]=1;return d};Y.Qa=function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+", "+a[9]+", "+a[10]+", "+a[11]+", "+a[12]+", "+a[13]+", "+a[14]+", "+a[15]+"]"};
L={create:function(a){var b=new U(4);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];return b},Yc:function(a,b){var c=a[0],d=a[1],e=a[2];if(!b||a==b)return a[3]=-Math.sqrt(Math.abs(1-c*c-d*d-e*e)),a;b[0]=c;b[1]=d;b[2]=e;b[3]=-Math.sqrt(Math.abs(1-c*c-d*d-e*e));return b},inverse:function(a,b){if(!b||a==b)return a[0]*=-1,a[1]*=-1,a[2]*=-1,a;b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];b[3]=a[3];return b},length:function(a){var b=a[0],c=a[1],d=a[2],
a=a[3];return Math.sqrt(b*b+c*c+d*d+a*a)},normalize:function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],g=a[3],f=Math.sqrt(c*c+d*d+e*e+g*g);if(f==0)return b[0]=0,b[1]=0,b[2]=0,b[3]=0,b;f=1/f;b[0]=c*f;b[1]=d*f;b[2]=e*f;b[3]=g*f;return b},multiply:function(a,b,c){c||(c=a);var d=a[0],e=a[1],g=a[2],a=a[3],f=b[0],h=b[1],j=b[2],b=b[3];c[0]=d*b+a*f+e*j-g*h;c[1]=e*b+a*h+g*f-d*j;c[2]=g*b+a*j+d*h-e*f;c[3]=a*b-d*f-e*h-g*j;return c},qc:function(a,b,c){c||(c=b);var d=b[0],e=b[1],g=b[2],b=a[0],f=a[1],h=a[2],a=a[3],
j=a*d+f*g-h*e,l=a*e+h*d-b*g,m=a*g+b*e-f*d,d=-b*d-f*e-h*g;c[0]=j*a+d*-b+l*-h-m*-f;c[1]=l*a+d*-f+m*-b-j*-h;c[2]=m*a+d*-h+j*-f-l*-b;return c},Sc:function(a,b){b||(b=W.create());var c=a[0],d=a[1],e=a[2],g=a[3],f=c+c,h=d+d,j=e+e,l=c*f,m=c*h;c*=j;var s=d*h;d*=j;e*=j;f*=g;h*=g;g*=j;b[0]=1-(s+e);b[1]=m-g;b[2]=c+h;b[3]=m+g;b[4]=1-(l+e);b[5]=d-f;b[6]=c-h;b[7]=d+f;b[8]=1-(l+s);return b},Fb:function(a,b){b||(b=Y.create());var c=a[0],d=a[1],e=a[2],g=a[3],f=c+c,h=d+d,j=e+e,l=c*f,m=c*h;c*=j;var s=d*h;d*=j;e*=j;
f*=g;h*=g;g*=j;b[0]=1-(s+e);b[1]=m-g;b[2]=c+h;b[3]=0;b[4]=m+g;b[5]=1-(l+e);b[6]=d-f;b[7]=0;b[8]=c-h;b[9]=d+f;b[10]=1-(l+s);b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b},Ad:function(a,b,c,d){d||(d=a);var e=a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3];if(Math.abs(e)>=1)return d!=a&&(d[0]=a[0],d[1]=a[1],d[2]=a[2],d[3]=a[3]),d;var g=Math.acos(e),f=Math.sqrt(1-e*e);if(Math.abs(f)<0.0010)return d[0]=a[0]*0.5+b[0]*0.5,d[1]=a[1]*0.5+b[1]*0.5,d[2]=a[2]*0.5+b[2]*0.5,d[3]=a[3]*0.5+b[3]*0.5,d;e=Math.sin((1-c)*
g)/f;c=Math.sin(c*g)/f;d[0]=a[0]*e+b[0]*c;d[1]=a[1]*e+b[1]*c;d[2]=a[2]*e+b[2]*c;d[3]=a[3]*e+b[3]*c;return d},Qa:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+"]"}};var $;$||($={});
(function(){function a(a){return a<10?"0"+a:a}function b(a){e.lastIndex=0;return e.test(a)?'"'+a.replace(e,function(a){var b=h[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,d){var e,h,r,q,u=g,p,n=d[a];n&&typeof n==="object"&&typeof n.toJSON==="function"&&(n=n.toJSON(a));typeof j==="function"&&(n=j.call(d,a,n));switch(typeof n){case "string":return b(n);case "number":return isFinite(n)?String(n):"null";case "boolean":case "null":return String(n);
case "object":if(!n)return"null";g+=f;p=[];if(Object.prototype.toString.apply(n)==="[object Array]"){q=n.length;for(e=0;e<q;e+=1)p[e]=c(e,n)||"null";r=p.length===0?"[]":g?"[\n"+g+p.join(",\n"+g)+"\n"+u+"]":"["+p.join(",")+"]";g=u;return r}if(j&&typeof j==="object"){q=j.length;for(e=0;e<q;e+=1)typeof j[e]==="string"&&(h=j[e],(r=c(h,n))&&p.push(b(h)+(g?": ":":")+r))}else for(h in n)Object.prototype.hasOwnProperty.call(n,h)&&(r=c(h,n))&&p.push(b(h)+(g?": ":":")+r);r=p.length===0?"{}":g?"{\n"+g+p.join(",\n"+
g)+"\n"+u+"}":"{"+p.join(",")+"}";g=u;return r}}if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":w},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var d=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g,f,h={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},j;if(typeof $.stringify!=="function")$.stringify=function(a,b,d){var e;f=g="";if(typeof d==="number")for(e=0;e<d;e+=1)f+=" ";else typeof d==="string"&&(f=d);if((j=b)&&typeof b!=="function"&&(typeof b!=="object"||typeof b.length!=="number"))throw Error("JSON.stringify");return c("",{"":a})};
if(typeof $.parse!=="function")$.parse=function(a,b){function c(a,d){var e,g,f=a[d];if(f&&typeof f==="object")for(e in f)Object.prototype.hasOwnProperty.call(f,e)&&(g=c(f,e),g!==i?f[e]=g:delete f[e]);return b.call(a,d,f)}var e,a=String(a);d.lastIndex=0;d.test(a)&&(a=a.replace(d,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),typeof b==="function"?c({"":e},""):e;throw new SyntaxError("JSON.parse");}})();z=z||{};
z.Xa=function(a,b,c){a=a||1;b=b||1;c=c||1;this.e=new z.q([-0.5*a,-0.5*b,0.5*c,0.5*a,-0.5*b,0.5*c,0.5*a,0.5*b,0.5*c,-0.5*a,0.5*b,0.5*c,-0.5*a,0.5*b,0.5*c,0.5*a,0.5*b,0.5*c,0.5*a,0.5*b,-0.5*c,-0.5*a,0.5*b,-0.5*c,0.5*a,-0.5*b,-0.5*c,-0.5*a,-0.5*b,-0.5*c,-0.5*a,0.5*b,-0.5*c,0.5*a,0.5*b,-0.5*c,-0.5*a,-0.5*b,-0.5*c,0.5*a,-0.5*b,-0.5*c,0.5*a,-0.5*b,0.5*c,-0.5*a,-0.5*b,0.5*c,0.5*a,-0.5*b,0.5*c,0.5*a,-0.5*b,-0.5*c,0.5*a,0.5*b,-0.5*c,0.5*a,0.5*b,0.5*c,-0.5*a,-0.5*b,-0.5*c,-0.5*a,-0.5*b,0.5*c,-0.5*a,0.5*b,0.5*
c,-0.5*a,0.5*b,-0.5*c],3);this.ma=new z.q([0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1],2);this.j=new z.R([0,1,2,0,2,3,4,5,6,4,6,7,8,9,10,8,10,11,12,13,14,12,14,15,16,17,18,16,18,19,20,21,22,20,22,23])};z.Xa.prototype={a:function(){for(var a in this)"function"===typeof this[a].a&&this[a].a(),delete this[a]}};z=z||{};
z.Ya=function(a,b,c){a=a||1;b=b||1;c=c||1;this.e=new z.q([-0.5*a,-0.5*b,0.5*c,0.5*a,-0.5*b,0.5*c,0.5*a,0.5*b,0.5*c,-0.5*a,0.5*b,0.5*c,0.5*a,-0.5*b,-0.5*c,-0.5*a,-0.5*b,-0.5*c,-0.5*a,0.5*b,-0.5*c,0.5*a,0.5*b,-0.5*c],3);this.j=new z.R([0,1,1,2,2,3,3,0,4,5,5,6,6,7,7,4,0,5,1,4,2,7,3,6])};z.Ya.prototype={a:function(){for(var a in this)"function"===typeof this[a].a&&this[a].a(),delete this[a]}};z=z||{};z.$a=function(){this.e=new z.q([0,0,1,0,0,1,1,1],2);this.ma=new z.q([0,0,1,0,0,1,1,1],2)};
z.$a.prototype={a:function(){for(var a in this)"function"===typeof this[a].a&&this[a].a(),delete this[a]}};z=z||{};z.ab=function(){this.e=new z.q([0,0,1,0,1,1,0,1,0,0],2)};z.ab.prototype={a:function(){for(var a in this)"function"===typeof this[a].a&&this[a].a(),delete this[a]}};z=z||{};
z.sa=function(a,b){for(var c in a)this[c]=a[c];if("string"===typeof this.color)this.color=z.d.ea(this.color);else if("undefined"===typeof this.color)this.color=[1,1,1,1];if("undefined"===typeof this.Ba)this.Ba=z.$.TRIANGLES;if("function"===typeof b)this.Aa=b};
z.sa.prototype={Aa:function(){var a=z.$,b=this.e,c=this.ma,d=this.j,e=this.color,g=this.Sa,f=this.Ba;g?a.Ib(b,c,e,g):a.Wc(b,e);d?a.Sb(f,d):a.jb(f,b.P);this.h=Y.create(a.h);this.w=Y.create(a.w)},a:function(){for(var a in this)"function"===typeof this[a].a&&this[a].a(),delete this[a]}};z=z||{};
z.ua=function(a,b,c){this.g=this.hb(a);z.gb();z.f=this.g;z.$=this;"undefined"!==typeof this.g?(this.TRIANGLES=this.g.TRIANGLES,this.TRIANGLE_STRIP=this.g.TRIANGLE_STRIP,this.TRIANGLE_FAN=this.g.TRIANGLE_FAN,this.LINES=this.g.LINES,this.LINE_STRIP=this.g.LINE_STRIP,this.LINE_LOOP=this.g.LINE_LOOP,this.POINTS=this.g.POINTS,"function"===typeof c&&c()):(z.D.log(z.G.get("initWebGL.error")),"function"===typeof b&&b());this.width=a.width;this.height=a.height;this.Ma=[];this.h=Y.U(Y.create());this.w=Y.U(Y.create());
this.clearColor=[0,0,0,0];this.Eb=[0,0,0,0];this.fillColor=[0,0,0,0];this.strokeColor=[0,0,0,0];this.Db=0;this.Qb=new z.ta(z.F.Va.Ta,z.F.Va.Ea);this.Qc=new z.ta(z.F.H.Ta,z.F.H.Ea);this.Cc=new z.$a;this.vd=new z.ab;this.$c=new z.Xa;this.ad=new z.Ya;this.La=0;this.currentTime=w;this.da=this.Ub=this.kb=this.elapsedTime=0;this.Ob("alpha");this.za(!0);this.origin();this.ia();this.Rc("#fff");this.fill("#fff");this.stroke("#000");this.la(1)};
z.ua.prototype={clear:function(a,b,c,d){var e=this.clearColor,g=this.g;if(e[0]!==a||e[1]!==b||e[2]!==c||e[3]!==d)e[0]=a,e[1]=b,e[2]=c,e[3]=d,g.clearColor(a,b,c,d);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT)},ia:function(){var a=this.width,b=this.height,c=a/2,d=b/2,e=d/Math.tan(z.d.Y(45)/2);Y.ia(45,a/b,e/10,e*100,this.w,!0);Y.translate(this.w,[-c,-d,-e])},xb:function(){Y.xb(0,this.width,this.height,0,-1E3,1E3,this.w)},Ac:function(){this.Ma.push(Y.create(this.h))},wc:function(){if(this.Ma.length>
0)this.h=this.Ma.pop()},origin:function(){Y.U(this.h)},transform:function(a){Y.multiply(this.h,a)},translate:function(a,b,c){Y.translate(this.h,[a,b,c||0])},rotate:function(a,b,c,d){Y.rotate(this.h,a,[b,c,d])},yb:function(a){Y.yb(this.h,a)},zb:function(a){Y.zb(this.h,a)},Ab:function(a){Y.Ab(this.h,a)},scale:function(a,b,c){Y.scale(this.h,[a,b,c||0])},Rc:function(a){this.Eb=z.d.ea(a)},fill:function(a){this.fillColor=z.d.ea(a)},stroke:function(a){this.strokeColor=z.d.ea(a)},la:function(a){if(this.Db!==
a)this.Db=a,this.g.lineWidth(a)},Ob:function(a){var b=this.g;"alpha"===a?(b.enable(b.BLEND),b.blendFunc(b.SRC_ALPHA,b.ONE_MINUS_SRC_ALPHA)):"add"===a||"additive"===a?(b.enable(b.BLEND),b.blendFunc(b.SRC_ALPHA,b.ONE)):b.disable(b.BLEND)},za:function(a){var b=this.g;a?b.enable(b.DEPTH_TEST):b.disable(b.DEPTH_TEST)},Wc:function(a,b){var c=this.Qb;c.Hb();c.va("vertexPosition",a);c.aa("mvMatrix",this.h);c.aa("projMatrix",this.w);c.cb("color",b)},Ib:function(a,b,c,d){var e=this.Qc;e.Hb();e.va("vertexPosition",
a);e.va("vertexTexCoord",b);e.aa("mvMatrix",this.h);e.aa("projMatrix",this.w);e.cb("color",c);e.bindTexture("sampler",d)},bc:function(a,b,c,d,e){var g=this.Cc,f=this.Eb;if("undefined"===typeof d||"undefined"===typeof e)d=texture.width,e=texture.height;"center"===g.fd&&(b-=d/2,c-=e/2);f[3]&&(this.Ac(),this.translate(b,c,0),this.scale(d,e,1),this.Ib(g.e,g.ma,f,a),this.jb(this.TRIANGLE_STRIP,g.e.P),this.wc())},jb:function(a,b){this.g.drawArrays(a,0,b)},Sb:function(a,b){var c=this.g;c.bindBuffer(c.ELEMENT_ARRAY_BUFFER,
b.b);c.drawElements(a,b.P,c.UNSIGNED_SHORT,0)},hb:function(a,b){var c=["experimental-webgl","webgl","webkit-3d","moz-webgl"],d,e,g;e=0;for(g=c.length;e<g;++e){try{d=a.getContext(c[e],b)}catch(f){}if(d)break}return d},loop:function(a){window.Ec(a);this.origin();this.ia();this.currentTime=(new Date).getTime();if(this.La!==0)this.da=this.currentTime-this.La,this.Ub=1E3/this.da;this.La=this.currentTime;this.elapsedTime+=this.da;this.kb++},a:function(){z.gb();for(var a in this)"function"===typeof this[a].a&&
this[a].a(),delete this[a]}};window.Ec=window.wd||window.Fd||window.nd||window.rd||window.od||function(a){window.setTimeout(a,1E3/60)};z=z||{};z.F={};z.F.Va={Ta:"attribute vec3 vertexPosition;\nuniform mat4 mvMatrix;\nuniform mat4 projMatrix;\nvoid main(void) {\n    gl_Position = projMatrix * mvMatrix * vec4(vertexPosition, 1.0);\n}",Ea:"#ifdef GL_ES\nprecision highp float;\n#endif\nuniform vec4 color;\nvoid main(void) {\n    gl_FragColor = color;\n}"};
z.F.H={Ta:"attribute vec3 vertexPosition;\nattribute vec2 vertexTexCoord;\nuniform mat4 mvMatrix;\nuniform mat4 projMatrix;\nvarying vec2 texCoord;\nvoid main(void) {\n  gl_Position = projMatrix * mvMatrix * vec4(vertexPosition, 1.0);\n  texCoord = vertexTexCoord;\n}",Ea:"#ifdef GL_ES\nprecision highp float;\n#endif\nuniform vec4 color;\nuniform sampler2D sampler;\nvarying vec2 texCoord;\nvoid main(void) {\n  vec4 tex = texture2D(sampler, vec2(texCoord.s, texCoord.t));\n  gl_FragColor = color * tex;\n}"};
z=z||{};z.D={log:function(a){"undefined"===typeof a&&(a="undefined");try{Components.fb["@mozilla.org/consoleservice;1"].Xb(Components.ob.tc).ld(a)}catch(b){alert(a)}},error:function(a){"undefined"===typeof a&&(a="undefined");try{var b=Components.fb["@mozilla.org/consoleservice;1"].Xb(Components.ob.tc),c=Components.fb["@mozilla.org/scripterror;1"].Zc(Components.ob.qd);c.Ha(a);b.kd(c)}catch(d){alert(a)}}};
z.G={eb:"tilt-string-bundle",get:function(a){if("undefined"===typeof a)return"undefined";var b=document.getElementById(this.eb);return b?b.getString(a):a},Da:function(a,b){if("undefined"===typeof a)return"undefined";if("undefined"===typeof b)return a;var c=document.getElementById(this.eb);return c?c.dd(a,b):[a,b].join(" ")}};z=z||{};
z.o={S:i,J:i,W:function(a,b,c,d){if("undefined"===typeof this.S)this.S=document;if("undefined"===typeof this.J)this.J=document.body;var e=this.J,g=this.S.createElement("canvas");g.width=a;g.height=b;g.id=d;c&&this.append(g,e);return g},gd:function(){var a=this.W(window.innerWidth,window.innerHeight,!0);a.setAttribute("style","width: 100%; height: 100%;");this.J.setAttribute("style","margin: 0px 0px 0px 0px;");return a},append:function(a,b){b.appendChild(a)},remove:function(a){a.parentNode.removeChild(a)},
Uc:function(a,b,c){function d(a,b,c){var j,l,m;j=0;for(l=b.childNodes.length;j<l;j++)m=b.childNodes[j],c>e&&(e=c),a(m,c),d(a,m,c+1)}var e=0;try{"function"===typeof a&&d(a,c||window.content.document,0),"function"===typeof b&&b(e)}finally{c=w}},Wb:function(a){var b=0,c=0,d=a.clientWidth,e=a.clientHeight;if(a.offsetParent){do b+=a.offsetLeft,c+=a.offsetTop;while(a=a.offsetParent)}else{if(a.x)b=a.x;if(a.y)c=a.y}return{x:b,y:c,width:d,height:e}},ed:function(a){var b;a.nodeType===1?b="ELEMENT_NODE":a.nodeType===
2?b="ATTRIBUTE_NODE":a.nodeType===3?b="TEXT_NODE":a.nodeType===4?b="CDATA_SECTION_NODE":a.nodeType===5?b="ENTITY_REFERENCE_NODE":a.nodeType===6?b="ENTITY_NODE":a.nodeType===7?b="PROCESSING_INSTRUCTION_NODE":a.nodeType===8?b="COMMENT_NODE":a.nodeType===9?b="DOCUMENT_NODE":a.nodeType===10?b="DOCUMENT_TYPE_NODE":a.nodeType===11?b="DOCUMENT_FRAGMENT_NODE":a.nodeType===12&&(b="NOTATION_NODE");return b}};z=z||{};
z.d={Y:function(a){return a*Math.PI/180},bd:function(a){return a*180/Math.PI},pb:function(a){return(a&a-1)===0},vb:function(a){var b;--a;for(b=1;b<32;b<<=1)a|=a>>b;return a+1},wa:function(a,b,c){return Math.max(b,Math.min(c,a))},ud:function(a,b,c){b*=0.5;var d=Math.sin(b),e=a[0]*d,g=a[1]*d,a=a[2]*d,b=Math.cos(b);return"undefined"===typeof c?[e,g,a,b]:(c[0]=e,c[1]=g,c[2]=a,c[3]=b,c)},Bc:function(a,b,c,d){var e;b*=0.5;a*=0.5;c*=0.5;e=Math.sin(b);var g=Math.sin(a),f=Math.sin(c),h=Math.cos(b),j=Math.cos(a),
l=Math.cos(c),b=e*j*l-h*g*f,a=h*g*l+e*j*f,c=h*j*f-e*g*l;e=h*j*l+e*g*f;return"undefined"===typeof d?[b,a,c,e]:(d[0]=b,d[1]=a,d[2]=c,d[3]=e,d)},Gb:function(a,b,c,d,e){var g=Y.create(),e=e||L.create();Y.multiply(d,c,g);Y.inverse(g);e[0]=+((a[0]-b[0])/b[2]*2-1);e[1]=-((a[1]-b[1])/b[3]*2-1);e[2]=2*a[2]-1;e[3]=1;Y.rc(g,e);e[3]=1/e[3];e[0]*=e[3];e[1]*=e[3];e[2]*=e[3];return e},Rb:function(a,b,c,d,e){this.Gb(a,c,d,e,a);this.Gb(b,c,d,e,b);return{position:a,jc:b,direction:D.normalize(D.Z(b,a))}},gc:function(a,
b,c,d,e){var g=D.create(),f=D.create(),h=D.create(),j=D.create(),l=D.create(),m=d.position,d=d.direction;"undefined"===typeof e&&(e=D.create());D.Z(b,a,g);D.Z(c,a,f);D.ib(g,f,h);if(h[0]===0&&h[1]===0&&h[2]===0)return-1;D.Z(m,a,l);b=-D.v(h,l);h=+D.v(h,d);if(Math.abs(h)<1.0E-4)return b==0?2:0;h=b/h;if(h<0)return 0;D.add(m,D.scale(d,h),e);m=D.v(g,g);d=D.v(g,f);h=D.v(f,f);D.Z(e,a,j);a=D.v(j,g);f=D.v(j,f);j=d*d-m*h;e=(d*f-h*a)/j;if(e<0||e>1)return 0;f=(d*a-m*f)/j;return f<0||e+f>1?0:1},ea:function(a){if("undefined"!==
typeof this[a])return this[a];var b,c,d,e;b=a.charAt(0)==="#"?a.substring(1):a;if(b.length===3)c=b.charAt(0),d=b.charAt(1),e=b.charAt(2),b=[c,c,d,d,e,e,"ff"].join("");else if(b.length===4)c=b.charAt(0),d=b.charAt(1),e=b.charAt(2),b=b.charAt(3),b=[c,c,d,d,e,e,b,b].join("");else if(b.match("^rgba")=="rgba")return b=b.substring(5,b.length-1).split(","),b[0]/=255,b[1]/=255,b[2]/=255,b[3]/=255,this[a]=b;else if(b.match("^rgb")=="rgb")return b=b.substring(4,b.length-1).split(","),b[0]/=255,b[1]/=255,b[2]/=
255,b[3]=1,this[a]=b;c=parseInt(b.substring(0,2),16)/255;d=parseInt(b.substring(2,4),16)/255;e=parseInt(b.substring(4,6),16)/255;b=b.length===6?1:parseInt(b.substring(6,8),16)/255;this[a]=[c,d,e,b];return[c,d,e,b]}};z=z||{};z.Lb={trim:function(a){return a.replace(/^\s+|\s+$/g,"")},md:function(a){return a.replace(/^\s+/,"")},yd:function(a){return a.replace(/\s+$/,"")}};z=z||{};z.Za={};
z.Za.Nb={dc:function(a){var b,c,d,e;b=z.o.W();c=z.o.W();b=z.ua.prototype.hb(b);b=b.getParameter(b.MAX_TEXTURE_SIZE);d=a.innerWidth+a.scrollMaxX;e=a.innerHeight+a.scrollMaxY;d=z.d.wa(d,0,b);b=z.d.wa(e,0,b);c.width=d;c.height=b;c.getContext("2d").drawWindow(a,0,0,d,b,"#fff");return c}};z=z||{};
z.Xc={Dc:function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.send(w);d.onreadystatechange=function(){d.readyState===4&&"function"===typeof b&&b(d,c)}},xd:function(a,b,c){function d(d,f){e[f]=d;g++;g===a.length&&"function"===typeof b&&b(e,c)}var e=[],g=0,f,h;f=0;for(h=a.length;f<h;f++)this.Dc(a[f],d,f)}};TiltChrome=TiltChrome||{};TiltChrome.Wa={};
TiltChrome.Wa.Kb=function(){function a(a){a.preventDefault();a.stopPropagation();C=a.clientX-a.target.offsetLeft;k=a.clientY-a.target.offsetTop;v=C;A=k;q=s;u=x;t=a.which;!j()&&t!==3&&m.oc(C,k)}function b(a){a.preventDefault();a.stopPropagation();t=!1;v===C&&A===k&&l.uc(C,k)}function c(a){a.preventDefault();a.stopPropagation();t=!1;v===C&&A===k&&l.vc(C,k)}function d(a){a.preventDefault();a.stopPropagation();C=a.clientX-a.target.offsetLeft;k=a.clientY-a.target.offsetTop}function e(a){a.preventDefault();
a.stopPropagation();t=!1}function g(a){a.preventDefault();a.stopPropagation();m.pc(a.detail)}function f(a){"open"!==TiltChrome.BrowserOverlay.panel.state&&(B[a.keyCode||a.which]=!0)}function h(a){a=a.keyCode||a.which;B[a]=!1;if(a===27)"open"===TiltChrome.BrowserOverlay.panel.state?(TiltChrome.BrowserOverlay.panel.hidePopup(),B=[],t=!1):(TiltChrome.BrowserOverlay.a(),TiltChrome.BrowserOverlay.href=w)}function j(){return B!==w?B[17]||B[224]:!1}var l=this,m=w,s=0,x=0,r=0,q=0,u=0,p=0,n=0,y=L.create(),
t=!1,v=0,A=0,C=0,k=0,B=[];l.Ha=function(k){m=new z.Ua(k.width,k.height);k.addEventListener("mousedown",a,!1);k.addEventListener("mouseup",b,!1);k.addEventListener("dblclick",c,!1);k.addEventListener("mousemove",d,!1);k.addEventListener("mouseout",e,!1);k.addEventListener("DOMMouseScroll",g,!1);window.addEventListener("keydown",f,!1);window.addEventListener("keyup",h,!1)};l.loop=function(a){if(t)if(j()||t===3){s=q+C-v;x=u+k-A;l.Cb(s,x,r);return}else m.nc(C,k);j()||(B[37]&&(s+=a/3),B[39]&&(s-=a/3),
B[38]&&(x+=a/3),B[40]&&(x-=a/3),B[65]&&(n-=z.d.Y(a)/10),B[68]&&(n+=z.d.Y(a)/10),B[87]&&(p+=z.d.Y(a)/10),B[83]&&(p-=z.d.Y(a)/10));a=m.loop(a);r=a.zoom;z.d.Bc(n,p,0,y);l.Ic(L.multiply(y,a.rotation));l.Cb(s,x,r)};this.a=function(k){k.removeEventListener("mousedown",a,!1);k.removeEventListener("mouseup",b,!1);k.removeEventListener("dblclick",c,!1);k.removeEventListener("mousemove",d,!1);k.removeEventListener("mouseout",e,!1);k.removeEventListener("DOMMouseScroll",g,!1);window.removeEventListener("keydown",
f,!1);window.removeEventListener("keyup",h,!1);m.a();B=y=m=w;for(var j in this)delete this[j];l=w}};TiltChrome=TiltChrome||{};
TiltChrome.Mb=function(a){var b=new TiltChrome.Wa.Kb;function c(){m!==w&&(m.loop(c),x.loaded&&(s&&(s=!1,m.clear(0,0,0,1),m.za(!1),m.bc(x,0,0,m.width,m.height),m.translate(m.width/2,m.height/2,n.m[2]-q*16),m.transform(L.Fb(n.rotation)),m.translate(n.m[0],n.m[1],0),m.za(!0),u.Aa(),p.Aa()),"function"===typeof b.loop&&b.loop(m.da)),(m.kb+1)%1E3===0&&window.QueryInterface(Ci.nsIInterfaceRequestor).getInterface(Ci.nsIDOMWindowUtils).garbageCollect())}function d(){var a=[],b=[],c=[],d=[],e=[];z.o.Uc(function(f,
g){var h=z.o.Wb(f);if(h.width>1&&h.height>1){var j=h.x-m.width/2,l=h.y-m.height/2,n=g*q,o=h.width,p=h.height,h=a.length/3;a.push(j,l,n);a.push(j+o,l,n);a.push(j+o,l+p,n);a.push(j,l+p,n);a.push(j,l+p,n-q);a.push(j+o,l+p,n-q);a.push(j+o,l+p,n);a.push(j,l+p,n);a.push(j,l,n);a.push(j+o,l,n);a.push(j+o,l,n-q);a.push(j,l,n-q);b.push((j+m.width/2)/r.width,(l+m.height/2)/r.height,(j+m.width/2+o)/r.width,(l+m.height/2)/r.height,(j+m.width/2+o)/r.width,(l+m.height/2+p)/r.height,(j+m.width/2)/r.width,(l+m.height/
2+p)/r.height);for(j=0;j<2;j++)b.push(0,0,0,0,0,0,0,0);e.push({innerHTML:f.innerHTML,name:f.localName,className:f.className,id:f.id});c.push(h+0,h+1,h+2,h+0,h+2,h+3);c.push(h+4,h+5,h+6,h+4,h+6,h+7);c.push(h+8,h+9,h+10,h+8,h+10,h+11);c.push(h+10,h+9,h+6,h+10,h+6,h+5);c.push(h+8,h+11,h+4,h+8,h+4,h+7);d.push(h+0,h+1,h+1,h+2,h+2,h+3,h+3,h+0);d.push(h+4,h+5,h+5,h+6,h+6,h+7,h+7,h+4);d.push(h+8,h+9,h+9,h+10,h+10,h+11,h+11,h+8);d.push(h+10,h+9,h+9,h+6,h+6,h+5,h+5,h+10);d.push(h+8,h+11,h+11,h+4,h+4,h+7,h+
7,h+8)}});u=new z.sa({e:new z.q(a,3),ma:new z.q(b,2),j:new z.R(c),color:"#fff",Sa:r,sc:e});p=new z.sa({e:u.e,j:new z.R(d),color:"#899",Ba:m.LINES})}function e(){if(TiltChrome.BrowserOverlay.href!==window.content.location.href)TiltChrome.BrowserOverlay.href=w,TiltChrome.BrowserOverlay.a()}function g(){m.width=window.content.innerWidth;m.height=window.content.innerHeight;s=!0;TiltChrome.BrowserOverlay.panel.hidePopup()}function f(a,b,c){if(n.m[0]!=a||n.m[1]!=b||n.m[2]!=c)n.m[0]=a,n.m[1]=b,n.m[2]=c,
s=!0}function h(a){if(n.rotation[0]!=a[0]||n.rotation[1]!=a[1]||n.rotation[2]!=a[2]||n.rotation[3]!=a[3])L.set(a,n.rotation),s=!0}function j(){window.content.focus()}function l(a,b){var c=z.d.Rb([a,b,0],[a,b,1],[0,0,m.width,m.height],u.h,u.w),d=D.create(),e=[],f,g,h,j,l;f=0;for(g=u.j.length;f<g;f+=3)h=[u.e[u.j[f]*3],u.e[u.j[f]*3+1],u.e[u.j[f]*3+2]],j=[u.e[u.j[f+1]*3],u.e[u.j[f+1]*3+1],u.e[u.j[f+1]*3+2]],l=[u.e[u.j[f+2]*3],u.e[u.j[f+2]*3+1],u.e[u.j[f+2]*3+2]],z.d.gc(h,j,l,c,d)>0&&e.push({location:D.create(d),
wb:u.sc[Math.floor(f/30)]});if(e.length>0)e.sort(function(a,b){return a.location[2]<b.location[2]?1:-1}),d=e[0],c=d.wb,d=z.Lb.trim(ca(d.wb.innerHTML).replace(/</g,"&lt;").replace(/>/g,"&gt;")),e=document.getElementById("tilt-panel-iframe"),f=e.contentDocument.getElementById("editor"),document.getElementById("tilt-panel-label").value=" <"+c.name+(c.className?' class="'+c.className+'"':"")+(c.id?' id="'+c.id+'"':"")+">",TiltChrome.BrowserOverlay.panel.openPopup(w,"overlap",window.innerWidth-e.width-
21,window.innerHeight-e.height-77,!1,!1),f.innerHTML=d,e.contentWindow.onload()}var m=new z.ua(a),s=!0,x=w,r=w,q=15,u=w,p=w,n={m:D.create(),rotation:L.create()};(function(){var c=z.Za.Nb.dc(window.content);r=new z.H(c,{fill:"white",stroke:"#aaa",la:8});d();gBrowser.tabContainer.addEventListener("TabClose",e,0);gBrowser.tabContainer.addEventListener("TabAttrModified",e,0);gBrowser.contentWindow.addEventListener("resize",g,0);b.width=m.width;b.height=m.height;b.Cb=f;b.Ic=h;b.uc=j;b.vc=l;"function"===
typeof b.Ha&&b.Ha(a);x=new z.H("chrome://tilt/skin/tilt-background.png");n.m=[0,0,0];n.rotation=[0,0,0,1];m.la(2)})();c();this.a=function(){gBrowser.tabContainer.removeEventListener("TabClose",e,0);gBrowser.tabContainer.removeEventListener("TabAttrModified",e,0);gBrowser.contentWindow.removeEventListener("resize",g,0);b.a(a);b=w;m.a();m=w;x.a();x=w;r.a();r=w;u.a();u=w;p.a();p=w;delete n.rotation;delete n.m;n=w;for(var c in this)"function"===typeof this[c].a&&this[c].a(),this[c]=w}};
