'use strict';var Tilt=Tilt||{},EXPORTED_SYMBOLS=["Tilt.VertexBuffer","Tilt.IndexBuffer"];Tilt.VertexBuffer=function(a,b,c){this.ref=null;this.length=this.numItems=this.itemSize=0;"undefined"!==typeof a&&this.initBuffer(a,b,c)};
Tilt.VertexBuffer.prototype={initBuffer:function(a,b,c){"undefined"===typeof c&&(c=a.length/b);var d=new Float32Array(a),e=Tilt.$gl;this.ref=e.createBuffer();e.bindBuffer(e.ARRAY_BUFFER,this.ref);e.bufferData(e.ARRAY_BUFFER,d,e.STATIC_DRAW);this.itemSize=b;this.numItems=c;this.length=a.length;for(b=0;b<a.length;b++)this[b]=a[b]},destroy:function(){for(var a in this)this[a]=null,delete this[a]}};
Tilt.IndexBuffer=function(a,b){this.ref=null;this.numItems=this.itemSize=this.length=0;"undefined"!==typeof a&&this.initBuffer(a,b)};
Tilt.IndexBuffer.prototype={initBuffer:function(a,b){if("undefined"===typeof b)b=a.length;var c=new Uint16Array(a),d=Tilt.$gl;this.ref=d.createBuffer();d.bindBuffer(d.ELEMENT_ARRAY_BUFFER,this.ref);d.bufferData(d.ELEMENT_ARRAY_BUFFER,c,d.STATIC_DRAW);this.itemSize=1;this.numItems=b;this.length=a.length;for(c=0;c<a.length;c++)this[c]=a[c]},destroy:function(){for(var a in this)"function"===typeof this[a].destroy&&this[a].destroy(),this[a]=null}};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.activeShader","Tilt.enabledAttributes"];
Tilt.$gl=null;Tilt.$renderer=null;Tilt.$activeShader=-1;Tilt.$enabledAttributes=-1;Tilt.clearCache=function(){Tilt.$gl=null;Tilt.$renderer=null;Tilt.$activeShader=-1;Tilt.$enabledAttributes=-1};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Mesh"];
Tilt.Mesh=function(a,b){for(var c in a)this[c]=a[c];if("string"===typeof this.color)this.color=Tilt.Math.hex2rgba(this.color);else if("undefined"===typeof this.color)this.color=[1,1,1,1];if("undefined"===typeof this.drawMode)this.drawMode=Tilt.$renderer.TRIANGLES;if("function"===typeof b)this.draw=b};
Tilt.Mesh.prototype={draw:function(){var a=Tilt.$renderer,b=this.vertices,c=this.texCoord,d=this.indices,e=this.color,f=this.texture,g=this.drawMode;f?a.useTextureShader(b,c,e,f):a.useColorShader(b,e);d?a.drawIndexedVertices(g,d):a.drawVertices(g,b.numItems);this.mvMatrix=mat4.create(a.mvMatrix);this.projMatrix=mat4.create(a.projMatrix)},destroy:function(){for(var a in this)"function"===typeof this[a].destroy&&this[a].destroy(),this[a]=null}};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Program"];
Tilt.Program=function(a,b){this.ref=null;this.id=0;this.uniforms=this.attributes=null;this.cache={};arguments.length===2&&this.initProgram(a,b)};
Tilt.Program.prototype={initProgram:function(a,b){this.ref=Tilt.GLSL.create(a,b);this.id=this.ref.id;this.attributes=this.ref.attributes;this.uniforms=this.ref.uniforms;this.ref.attributes=null;this.ref.uniforms=null;delete this.ref.id;delete this.ref.attributes;delete this.ref.uniforms},initProgramAt:function(a,b,c){arguments.length===2&&(c=b,b=a+".fs",a+=".vs");var d=this;Tilt.Xhr.requests([a,b],function(a){d.initProgram(a[0].responseText,a[1].responseText);"function"===typeof c&&c()})},use:function(){if(Tilt.$activeShader!==
this.id){Tilt.$activeShader=this.id;var a=Tilt.$gl;a.useProgram(this.ref);if(Tilt.$enabledAttributes<this.attributes.length){Tilt.$enabledAttributes=this.attributes.length;for(var b in this.attributes)this.attributes.hasOwnProperty(b)&&b!=="length"&&a.enableVertexAttribArray(this.attributes[b])}}},bindVertexBuffer:function(a,b){var c=Tilt.$gl,d=this.attributes[a],e=b.itemSize;c.bindBuffer(c.ARRAY_BUFFER,b.ref);c.vertexAttribPointer(d,e,c.FLOAT,!1,0,0)},bindUniformMatrix:function(a,b){var c=b[0]+b[1]+
b[2]+(b[4]+b[5]+b[6])+(b[8]+b[9]+b[10])+(b[12]+b[13]+b[14]);this.cache[a]!==c&&(this.cache[a]=c,Tilt.$gl.uniformMatrix4fv(this.uniforms[a],!1,b))},bindUniformVec4:function(a,b){var c=b[3]*255<<24|b[0]*255<<16|b[1]*255<<8|b[2]*255;this.cache[a]!==c&&(this.cache[a]=c,Tilt.$gl.uniform4fv(this.uniforms[a],b))},bindUniformFloat:function(a,b){this.cache[a]!==b&&(this.cache[a]=b,Tilt.$gl.uniform1f(this.uniforms[a],b))},bindTexture:function(a,b){if(this.cache[a]!==b.id){this.cache[a]=b.id;var c=Tilt.$gl;
c.bindTexture(c.TEXTURE_2D,b.ref);c.uniform1i(this.uniforms[a],0)}},destroy:function(){for(var a in this)"function"===typeof this[a].destroy&&this[a].destroy(),this[a]=null}};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.GLSL"];
Tilt.GLSL={create:function(a,b){var c=this.compile(a,"x-shader/x-vertex"),d=this.compile(b,"x-shader/x-fragment");return this.link(c,d)},compile:function(a,b){var c=Tilt.$gl,d;if("string"!==typeof a||a.length<1)return Tilt.Console.error(Tilt.StringBundle.get("compileShader.source.error")),null;if(b==="x-shader/x-vertex")d=c.createShader(c.VERTEX_SHADER);else if(b==="x-shader/x-fragment")d=c.createShader(c.FRAGMENT_SHADER);else return Tilt.Console.error(Tilt.StringBundle.format("compileShader.type.error"),
[a]),null;c.shaderSource(d,a);c.compileShader(d);d.src=a;return!c.getShaderParameter(d,c.COMPILE_STATUS)?(c=c.getShaderInfoLog(d),Tilt.Console.error(Tilt.StringBundle.format("compileShader.compile.error"),[c]),null):d},link:function(a,b){var c=Tilt.$gl,d;d=c.createProgram();c.attachShader(d,a);c.attachShader(d,b);c.linkProgram(d);if(!c.getProgramParameter(d,c.LINK_STATUS))return d=c.getProgramInfoLog(d),Tilt.Console.error(Tilt.StringBundle.format("linkProgram.error",[d])),null;d.id=++this.count;c=
[a.src,b.src].join(" ").replace(/#.*|[(){};,]/g," ").split(" ");return this.shaderIOCache(d,c)},shaderAttribute:function(a,b){return Tilt.$gl.getAttribLocation(a,b)},shaderUniform:function(a,b){return Tilt.$gl.getUniformLocation(a,b)},shaderIO:function(a,b){var c;return(c=this.shaderAttribute(a,b))>=0?c:this.shaderUniform(a,b)},shaderIOCache:function(a,b){var c,d,e,f;a.attributes={};a.attributes.length=0;a.uniforms={};c=0;for(d=b.length;c<d;c++)e=b[c],f=this.shaderIO(a,e),"number"===typeof f&&"undefined"===
typeof a.attributes[e]&&(a.attributes[e]=f,a.attributes.length++),"object"===typeof f&&f instanceof WebGLUniformLocation&&"undefined"===typeof a.uniforms[e]&&(a.uniforms[e]=f);return a},count:0};window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Texture"];
Tilt.Texture=function(a,b){this.ref=null;this.id=0;this.height=this.width=-1;this.loaded=!1;"object"===typeof a?this.initTexture(a,b):"string"===typeof a?this.initTextureAt(a,b):Tilt.Console.error(Tilt.StringBundle.get("initTexture.source.error"))};
Tilt.Texture.prototype={initTexture:function(a,b){this.ref=Tilt.TextureUtils.create(a,b);this.id=this.ref.id;this.width=this.ref.width;this.height=this.ref.height;this.loaded=!0;delete this.ref.id;delete this.ref.width;delete this.ref.height},initTextureAt:function(a,b,c){var d=this,e=new Image;e.src=a;e.onload=function(){d.initTexture(e,b);b=e=d=null;"function"===typeof c&&c()}},destroy:function(){for(var a in this)"function"===typeof this[a].destroy&&this[a].destroy(),this[a]=null}};
Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.TextureUtils"];
Tilt.TextureUtils={create:function(a,b){var b=b||{},c=Tilt.$gl,d=Tilt.TextureUtils.resizeImageToPowerOfTwo(a,b),e=a.width,f=a.height,g=c.createTexture();c.bindTexture(c.TEXTURE_2D,g);c.texImage2D(c.TEXTURE_2D,0,c.RGBA,c.RGBA,c.UNSIGNED_BYTE,d);g.width=e;g.height=f;g.id=++this.count;this.setTextureParams(b);c.bindTexture(c.TEXTURE_2D,null);return g},setTextureParams:function(a){var b=Tilt.$gl,c=b.TEXTURE_MIN_FILTER,d=b.TEXTURE_MAG_FILTER,e=b.TEXTURE_WRAP_S,f=b.TEXTURE_WRAP_T,a=a||{};a.texture&&b.bindTexture(b.TEXTURE_2D,
a.texture.ref);"nearest"===a.minFilter?b.texParameteri(b.TEXTURE_2D,c,b.NEAREST):"linear"===a.minFilter&&a.mipmap?b.texParameteri(b.TEXTURE_2D,c,b.LINEAR_MIPMAP_LINEAR):b.texParameteri(b.TEXTURE_2D,c,b.LINEAR);"nearest"===a.magFilter?b.texParameteri(b.TEXTURE_2D,d,b.NEAREST):"linear"===a.magFilter&&a.mipmap?b.texParameteri(b.TEXTURE_2D,d,b.LINEAR_MIPMAP_LINEAR):b.texParameteri(b.TEXTURE_2D,d,b.LINEAR);"repeat"===a.wrapS?b.texParameteri(b.TEXTURE_2D,e,b.REPEAT):b.texParameteri(b.TEXTURE_2D,e,b.CLAMP_TO_EDGE);
"repeat"===a.wrapT?b.texParameteri(b.TEXTURE_2D,f,b.REPEAT):b.texParameteri(b.TEXTURE_2D,f,b.CLAMP_TO_EDGE);a.mipmap&&b.generateMipmap(b.TEXTURE_2D)},resizeImageToPowerOfTwo:function(a,b){var c=(a.src||"").indexOf("chrome://"),d=Tilt.Math.isPowerOfTwo(a.width),e=Tilt.Math.isPowerOfTwo(a.height);if(d&&e&&c===-1)try{return a}finally{b=a=null}b=b||{};c=Tilt.Math.nextPowerOfTwo(a.width);d=Tilt.Math.nextPowerOfTwo(a.height);c=Tilt.Document.initCanvas(c,d);d=c.getContext("2d");if(b.fill)d.fillStyle=b.fill,
d.fillRect(0,0,c.width,c.height);d.drawImage(a,0,0,a.width,a.height,0,0,c.width,c.height);if(b.stroke)d.strokeStyle=b.stroke,d.lineWidth=b.strokeWeight,d.strokeRect(0,0,c.width,c.height);return c},setTextureFlipY:function(a){Tilt.$gl.pixelStorei(Tilt.$gl.UNPACK_FLIP_Y_WEBGL,a)},count:0};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Cube"];
Tilt.Cube=function(a,b,c){a=a||1;b=b||1;c=c||1;this.vertices=new Tilt.VertexBuffer([-0.5*a,-0.5*b,0.5*c,0.5*a,-0.5*b,0.5*c,0.5*a,0.5*b,0.5*c,-0.5*a,0.5*b,0.5*c,-0.5*a,0.5*b,0.5*c,0.5*a,0.5*b,0.5*c,0.5*a,0.5*b,-0.5*c,-0.5*a,0.5*b,-0.5*c,0.5*a,-0.5*b,-0.5*c,-0.5*a,-0.5*b,-0.5*c,-0.5*a,0.5*b,-0.5*c,0.5*a,0.5*b,-0.5*c,-0.5*a,-0.5*b,-0.5*c,0.5*a,-0.5*b,-0.5*c,0.5*a,-0.5*b,0.5*c,-0.5*a,-0.5*b,0.5*c,0.5*a,-0.5*b,0.5*c,0.5*a,-0.5*b,-0.5*c,0.5*a,0.5*b,-0.5*c,0.5*a,0.5*b,0.5*c,-0.5*a,-0.5*b,-0.5*c,-0.5*a,-0.5*
b,0.5*c,-0.5*a,0.5*b,0.5*c,-0.5*a,0.5*b,-0.5*c],3);this.texCoord=new Tilt.VertexBuffer([0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1],2);this.indices=new Tilt.IndexBuffer([0,1,2,0,2,3,4,5,6,4,6,7,8,9,10,8,10,11,12,13,14,12,14,15,16,17,18,16,18,19,20,21,22,20,22,23])};Tilt.Cube.prototype={destroy:function(){for(var a in this)"function"===typeof this[a].destroy&&this[a].destroy(),this[a]=null}};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.CubeWireframe"];
Tilt.CubeWireframe=function(a,b,c){a=a||1;b=b||1;c=c||1;this.vertices=new Tilt.VertexBuffer([-0.5*a,-0.5*b,0.5*c,0.5*a,-0.5*b,0.5*c,0.5*a,0.5*b,0.5*c,-0.5*a,0.5*b,0.5*c,0.5*a,-0.5*b,-0.5*c,-0.5*a,-0.5*b,-0.5*c,-0.5*a,0.5*b,-0.5*c,0.5*a,0.5*b,-0.5*c],3);this.indices=new Tilt.IndexBuffer([0,1,1,2,2,3,3,0,4,5,5,6,6,7,7,4,0,5,1,4,2,7,3,6])};Tilt.CubeWireframe.prototype={destroy:function(){for(var a in this)"function"===typeof this[a].destroy&&this[a].destroy(),this[a]=null}};Tilt=Tilt||{};
EXPORTED_SYMBOLS=["Tilt.Rectangle"];Tilt.Rectangle=function(){this.vertices=new Tilt.VertexBuffer([0,0,1,0,0,1,1,1],2);this.texCoord=new Tilt.VertexBuffer([0,0,1,0,0,1,1,1],2)};Tilt.Rectangle.prototype={destroy:function(){for(var a in this)"function"===typeof this[a].destroy&&this[a].destroy(),this[a]=null}};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.RectangleWireframe"];Tilt.RectangleWireframe=function(){this.vertices=new Tilt.VertexBuffer([0,0,1,0,1,1,0,1,0,0],2)};
Tilt.RectangleWireframe.prototype={destroy:function(){for(var a in this)"function"===typeof this[a].destroy&&this[a].destroy(),this[a]=null}};var glMatrixArrayType,vec3,mat3,mat4,quat4;glMatrixArrayType=typeof Float32Array!="undefined"?Float32Array:typeof WebGLFloatArray!="undefined"?WebGLFloatArray:Array;
vec3={create:function(a){var b=new glMatrixArrayType(3);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];return b},add:function(a,b,c){if(!c||a==c)return a[0]+=b[0],a[1]+=b[1],a[2]+=b[2],a;c[0]=a[0]+b[0];c[1]=a[1]+b[1];c[2]=a[2]+b[2];return c},subtract:function(a,b,c){if(!c||a==c)return a[0]-=b[0],a[1]-=b[1],a[2]-=b[2],a;c[0]=a[0]-b[0];c[1]=a[1]-b[1];c[2]=a[2]-b[2];return c},negate:function(a,b){b||(b=a);b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];return b},scale:function(a,
b,c){if(!c||a==c)return a[0]*=b,a[1]*=b,a[2]*=b,a;c[0]=a[0]*b;c[1]=a[1]*b;c[2]=a[2]*b;return c},normalize:function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],f=Math.sqrt(c*c+d*d+e*e);if(f){if(f==1)return b[0]=c,b[1]=d,b[2]=e,b}else return b[0]=0,b[1]=0,b[2]=0,b;f=1/f;b[0]=c*f;b[1]=d*f;b[2]=e*f;return b},cross:function(a,b,c){c||(c=a);var d=a[0],e=a[1],a=a[2],f=b[0],g=b[1],b=b[2];c[0]=e*b-a*g;c[1]=a*f-d*b;c[2]=d*g-e*f;return c},length:function(a){var b=a[0],c=a[1],a=a[2];return Math.sqrt(b*b+c*c+a*a)},
dot:function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]},direction:function(a,b,c){c||(c=a);var d=a[0]-b[0],e=a[1]-b[1],a=a[2]-b[2],b=Math.sqrt(d*d+e*e+a*a);if(!b)return c[0]=0,c[1]=0,c[2]=0,c;b=1/b;c[0]=d*b;c[1]=e*b;c[2]=a*b;return c},lerp:function(a,b,c,d){d||(d=a);d[0]=a[0]+c*(b[0]-a[0]);d[1]=a[1]+c*(b[1]-a[1]);d[2]=a[2]+c*(b[2]-a[2]);return d},str:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+"]"}};
mat3={create:function(a){var b=new glMatrixArrayType(9);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b[4]=a[4],b[5]=a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];return b},identity:function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=1;a[5]=0;a[6]=0;a[7]=0;a[8]=1;return a},transpose:function(a,b){if(!b||a==b){var c=a[1],d=a[2],e=a[5];a[1]=a[3];a[2]=a[6];a[3]=c;a[5]=a[7];a[6]=d;a[7]=e;return a}b[0]=a[0];
b[1]=a[3];b[2]=a[6];b[3]=a[1];b[4]=a[4];b[5]=a[7];b[6]=a[2];b[7]=a[5];b[8]=a[8];return b},toMat4:function(a,b){b||(b=mat4.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=0;b[4]=a[3];b[5]=a[4];b[6]=a[5];b[7]=0;b[8]=a[6];b[9]=a[7];b[10]=a[8];b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b},str:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+"]"}};
mat4={create:function(a){var b=new glMatrixArrayType(16);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b[4]=a[4],b[5]=a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8],b[9]=a[9],b[10]=a[10],b[11]=a[11],b[12]=a[12],b[13]=a[13],b[14]=a[14],b[15]=a[15]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=a[12];b[13]=a[13];b[14]=a[14];b[15]=a[15];return b},identity:function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=
1;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},transpose:function(a,b){if(!b||a==b){var c=a[1],d=a[2],e=a[3],f=a[6],g=a[7],h=a[11];a[1]=a[4];a[2]=a[8];a[3]=a[12];a[4]=c;a[6]=a[9];a[7]=a[13];a[8]=d;a[9]=f;a[11]=a[14];a[12]=e;a[13]=g;a[14]=h;return a}b[0]=a[0];b[1]=a[4];b[2]=a[8];b[3]=a[12];b[4]=a[1];b[5]=a[5];b[6]=a[9];b[7]=a[13];b[8]=a[2];b[9]=a[6];b[10]=a[10];b[11]=a[14];b[12]=a[3];b[13]=a[7];b[14]=a[11];b[15]=a[15];return b},determinant:function(a){var b=
a[0],c=a[1],d=a[2],e=a[3],f=a[4],g=a[5],h=a[6],i=a[7],j=a[8],k=a[9],l=a[10],o=a[11],m=a[12],n=a[13],q=a[14],a=a[15];return m*k*h*e-j*n*h*e-m*g*l*e+f*n*l*e+j*g*q*e-f*k*q*e-m*k*d*i+j*n*d*i+m*c*l*i-b*n*l*i-j*c*q*i+b*k*q*i+m*g*d*o-f*n*d*o-m*c*h*o+b*n*h*o+f*c*q*o-b*g*q*o-j*g*d*a+f*k*d*a+j*c*h*a-b*k*h*a-f*c*l*a+b*g*l*a},inverse:function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],f=a[3],g=a[4],h=a[5],i=a[6],j=a[7],k=a[8],l=a[9],o=a[10],m=a[11],n=a[12],q=a[13],r=a[14],p=a[15],A=c*h-d*g,B=c*i-e*g,t=c*j-f*g,u=
d*i-e*h,v=d*j-f*h,w=e*j-f*i,x=k*q-l*n,y=k*r-o*n,z=k*p-m*n,C=l*r-o*q,D=l*p-m*q,E=o*p-m*r,s=1/(A*E-B*D+t*C+u*z-v*y+w*x);b[0]=(h*E-i*D+j*C)*s;b[1]=(-d*E+e*D-f*C)*s;b[2]=(q*w-r*v+p*u)*s;b[3]=(-l*w+o*v-m*u)*s;b[4]=(-g*E+i*z-j*y)*s;b[5]=(c*E-e*z+f*y)*s;b[6]=(-n*w+r*t-p*B)*s;b[7]=(k*w-o*t+m*B)*s;b[8]=(g*D-h*z+j*x)*s;b[9]=(-c*D+d*z-f*x)*s;b[10]=(n*v-q*t+p*A)*s;b[11]=(-k*v+l*t-m*A)*s;b[12]=(-g*C+h*y-i*x)*s;b[13]=(c*C-d*y+e*x)*s;b[14]=(-n*u+q*B-r*A)*s;b[15]=(k*u-l*B+o*A)*s;return b}};
mat4.toRotationMat=function(a,b){b||(b=mat4.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b};mat4.toMat3=function(a,b){b||(b=mat3.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[4];b[4]=a[5];b[5]=a[6];b[6]=a[8];b[7]=a[9];b[8]=a[10];return b};
mat4.toInverseMat3=function(a,b){var c=a[0],d=a[1],e=a[2],f=a[4],g=a[5],h=a[6],i=a[8],j=a[9],k=a[10],l=k*g-h*j,o=-k*f+h*i,m=j*f-g*i,n=c*l+d*o+e*m;if(!n)return null;n=1/n;b||(b=mat3.create());b[0]=l*n;b[1]=(-k*d+e*j)*n;b[2]=(h*d-e*g)*n;b[3]=o*n;b[4]=(k*c-e*i)*n;b[5]=(-h*c+e*f)*n;b[6]=m*n;b[7]=(-j*c+d*i)*n;b[8]=(g*c-d*f)*n;return b};
mat4.multiply=function(a,b,c){c||(c=a);var d=a[0],e=a[1],f=a[2],g=a[3],h=a[4],i=a[5],j=a[6],k=a[7],l=a[8],o=a[9],m=a[10],n=a[11],q=a[12],r=a[13],p=a[14],a=a[15],A=b[0],B=b[1],t=b[2],u=b[3],v=b[4],w=b[5],x=b[6],y=b[7],z=b[8],C=b[9],D=b[10],E=b[11],s=b[12],F=b[13],G=b[14],b=b[15];c[0]=A*d+B*h+t*l+u*q;c[1]=A*e+B*i+t*o+u*r;c[2]=A*f+B*j+t*m+u*p;c[3]=A*g+B*k+t*n+u*a;c[4]=v*d+w*h+x*l+y*q;c[5]=v*e+w*i+x*o+y*r;c[6]=v*f+w*j+x*m+y*p;c[7]=v*g+w*k+x*n+y*a;c[8]=z*d+C*h+D*l+E*q;c[9]=z*e+C*i+D*o+E*r;c[10]=z*f+C*
j+D*m+E*p;c[11]=z*g+C*k+D*n+E*a;c[12]=s*d+F*h+G*l+b*q;c[13]=s*e+F*i+G*o+b*r;c[14]=s*f+F*j+G*m+b*p;c[15]=s*g+F*k+G*n+b*a;return c};mat4.multiplyVec3=function(a,b,c){c||(c=b);var d=b[0],e=b[1],b=b[2];c[0]=a[0]*d+a[4]*e+a[8]*b+a[12];c[1]=a[1]*d+a[5]*e+a[9]*b+a[13];c[2]=a[2]*d+a[6]*e+a[10]*b+a[14];return c};
mat4.multiplyVec4=function(a,b,c){c||(c=b);var d=b[0],e=b[1],f=b[2],b=b[3];c[0]=a[0]*d+a[4]*e+a[8]*f+a[12]*b;c[1]=a[1]*d+a[5]*e+a[9]*f+a[13]*b;c[2]=a[2]*d+a[6]*e+a[10]*f+a[14]*b;c[3]=a[3]*d+a[7]*e+a[11]*f+a[15]*b;return c};
mat4.translate=function(a,b,c){var d=b[0],e=b[1],b=b[2];if(!c||a==c)return a[12]=a[0]*d+a[4]*e+a[8]*b+a[12],a[13]=a[1]*d+a[5]*e+a[9]*b+a[13],a[14]=a[2]*d+a[6]*e+a[10]*b+a[14],a[15]=a[3]*d+a[7]*e+a[11]*b+a[15],a;var f=a[0],g=a[1],h=a[2],i=a[3],j=a[4],k=a[5],l=a[6],o=a[7],m=a[8],n=a[9],q=a[10],r=a[11];c[0]=f;c[1]=g;c[2]=h;c[3]=i;c[4]=j;c[5]=k;c[6]=l;c[7]=o;c[8]=m;c[9]=n;c[10]=q;c[11]=r;c[12]=f*d+j*e+m*b+a[12];c[13]=g*d+k*e+n*b+a[13];c[14]=h*d+l*e+q*b+a[14];c[15]=i*d+o*e+r*b+a[15];return c};
mat4.scale=function(a,b,c){var d=b[0],e=b[1],b=b[2];if(!c||a==c)return a[0]*=d,a[1]*=d,a[2]*=d,a[3]*=d,a[4]*=e,a[5]*=e,a[6]*=e,a[7]*=e,a[8]*=b,a[9]*=b,a[10]*=b,a[11]*=b,a;c[0]=a[0]*d;c[1]=a[1]*d;c[2]=a[2]*d;c[3]=a[3]*d;c[4]=a[4]*e;c[5]=a[5]*e;c[6]=a[6]*e;c[7]=a[7]*e;c[8]=a[8]*b;c[9]=a[9]*b;c[10]=a[10]*b;c[11]=a[11]*b;c[12]=a[12];c[13]=a[13];c[14]=a[14];c[15]=a[15];return c};
mat4.rotate=function(a,b,c,d){var e=c[0],f=c[1],c=c[2],g=Math.sqrt(e*e+f*f+c*c);if(!g)return null;g!=1&&(g=1/g,e*=g,f*=g,c*=g);var h=Math.sin(b),i=Math.cos(b),j=1-i,b=a[0],g=a[1],k=a[2],l=a[3],o=a[4],m=a[5],n=a[6],q=a[7],r=a[8],p=a[9],A=a[10],B=a[11],t=e*e*j+i,u=f*e*j+c*h,v=c*e*j-f*h,w=e*f*j-c*h,x=f*f*j+i,y=c*f*j+e*h,z=e*c*j+f*h,e=f*c*j-e*h,f=c*c*j+i;d?a!=d&&(d[12]=a[12],d[13]=a[13],d[14]=a[14],d[15]=a[15]):d=a;d[0]=b*t+o*u+r*v;d[1]=g*t+m*u+p*v;d[2]=k*t+n*u+A*v;d[3]=l*t+q*u+B*v;d[4]=b*w+o*x+r*y;d[5]=
g*w+m*x+p*y;d[6]=k*w+n*x+A*y;d[7]=l*w+q*x+B*y;d[8]=b*z+o*e+r*f;d[9]=g*z+m*e+p*f;d[10]=k*z+n*e+A*f;d[11]=l*z+q*e+B*f;return d};mat4.rotateX=function(a,b,c){var d=Math.sin(b),b=Math.cos(b),e=a[4],f=a[5],g=a[6],h=a[7],i=a[8],j=a[9],k=a[10],l=a[11];c?a!=c&&(c[0]=a[0],c[1]=a[1],c[2]=a[2],c[3]=a[3],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[4]=e*b+i*d;c[5]=f*b+j*d;c[6]=g*b+k*d;c[7]=h*b+l*d;c[8]=e*-d+i*b;c[9]=f*-d+j*b;c[10]=g*-d+k*b;c[11]=h*-d+l*b;return c};
mat4.rotateY=function(a,b,c){var d=Math.sin(b),b=Math.cos(b),e=a[0],f=a[1],g=a[2],h=a[3],i=a[8],j=a[9],k=a[10],l=a[11];c?a!=c&&(c[4]=a[4],c[5]=a[5],c[6]=a[6],c[7]=a[7],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[0]=e*b+i*-d;c[1]=f*b+j*-d;c[2]=g*b+k*-d;c[3]=h*b+l*-d;c[8]=e*d+i*b;c[9]=f*d+j*b;c[10]=g*d+k*b;c[11]=h*d+l*b;return c};
mat4.rotateZ=function(a,b,c){var d=Math.sin(b),b=Math.cos(b),e=a[0],f=a[1],g=a[2],h=a[3],i=a[4],j=a[5],k=a[6],l=a[7];c?a!=c&&(c[8]=a[8],c[9]=a[9],c[10]=a[10],c[11]=a[11],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[0]=e*b+i*d;c[1]=f*b+j*d;c[2]=g*b+k*d;c[3]=h*b+l*d;c[4]=e*-d+i*b;c[5]=f*-d+j*b;c[6]=g*-d+k*b;c[7]=h*-d+l*b;return c};
mat4.frustum=function(a,b,c,d,e,f,g){g||(g=mat4.create());var h=b-a,i=d-c,j=f-e;g[0]=e*2/h;g[1]=0;g[2]=0;g[3]=0;g[4]=0;g[5]=e*2/i;g[6]=0;g[7]=0;g[8]=(b+a)/h;g[9]=(d+c)/i;g[10]=-(f+e)/j;g[11]=-1;g[12]=0;g[13]=0;g[14]=-(f*e*2)/j;g[15]=0;return g};mat4.perspective=function(a,b,c,d,e,f){a=c*Math.tan(a*Math.PI/360);b*=a;return mat4.frustum(-b,b,-a*(f?-1:1),a*(f?-1:1),c,d,e)};
mat4.ortho=function(a,b,c,d,e,f,g){g||(g=mat4.create());var h=b-a,i=d-c,j=f-e;g[0]=2/h;g[1]=0;g[2]=0;g[3]=0;g[4]=0;g[5]=2/i;g[6]=0;g[7]=0;g[8]=0;g[9]=0;g[10]=-2/j;g[11]=0;g[12]=-(a+b)/h;g[13]=-(d+c)/i;g[14]=-(f+e)/j;g[15]=1;return g};
mat4.lookAt=function(a,b,c,d){d||(d=mat4.create());var e=a[0],f=a[1],a=a[2],g=c[0],h=c[1],i=c[2],c=b[1],j=b[2];if(e==b[0]&&f==c&&a==j)return mat4.identity(d);var k,l,o,m,c=e-b[0],j=f-b[1],b=a-b[2];m=1/Math.sqrt(c*c+j*j+b*b);c*=m;j*=m;b*=m;k=h*b-i*j;i=i*c-g*b;g=g*j-h*c;(m=Math.sqrt(k*k+i*i+g*g))?(m=1/m,k*=m,i*=m,g*=m):g=i=k=0;h=j*g-b*i;l=b*k-c*g;o=c*i-j*k;(m=Math.sqrt(h*h+l*l+o*o))?(m=1/m,h*=m,l*=m,o*=m):o=l=h=0;d[0]=k;d[1]=h;d[2]=c;d[3]=0;d[4]=i;d[5]=l;d[6]=j;d[7]=0;d[8]=g;d[9]=o;d[10]=b;d[11]=0;
d[12]=-(k*e+i*f+g*a);d[13]=-(h*e+l*f+o*a);d[14]=-(c*e+j*f+b*a);d[15]=1;return d};mat4.str=function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+", "+a[9]+", "+a[10]+", "+a[11]+", "+a[12]+", "+a[13]+", "+a[14]+", "+a[15]+"]"};
quat4={create:function(a){var b=new glMatrixArrayType(4);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];return b},calculateW:function(a,b){var c=a[0],d=a[1],e=a[2];if(!b||a==b)return a[3]=-Math.sqrt(Math.abs(1-c*c-d*d-e*e)),a;b[0]=c;b[1]=d;b[2]=e;b[3]=-Math.sqrt(Math.abs(1-c*c-d*d-e*e));return b},inverse:function(a,b){if(!b||a==b)return a[0]*=-1,a[1]*=-1,a[2]*=-1,a;b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];b[3]=a[3];return b},length:function(a){var b=
a[0],c=a[1],d=a[2],a=a[3];return Math.sqrt(b*b+c*c+d*d+a*a)},normalize:function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],f=a[3],g=Math.sqrt(c*c+d*d+e*e+f*f);if(g==0)return b[0]=0,b[1]=0,b[2]=0,b[3]=0,b;g=1/g;b[0]=c*g;b[1]=d*g;b[2]=e*g;b[3]=f*g;return b},multiply:function(a,b,c){c||(c=a);var d=a[0],e=a[1],f=a[2],a=a[3],g=b[0],h=b[1],i=b[2],b=b[3];c[0]=d*b+a*g+e*i-f*h;c[1]=e*b+a*h+f*g-d*i;c[2]=f*b+a*i+d*h-e*g;c[3]=a*b-d*g-e*h-f*i;return c},multiplyVec3:function(a,b,c){c||(c=b);var d=b[0],e=b[1],f=b[2],
b=a[0],g=a[1],h=a[2],a=a[3],i=a*d+g*f-h*e,j=a*e+h*d-b*f,k=a*f+b*e-g*d,d=-b*d-g*e-h*f;c[0]=i*a+d*-b+j*-h-k*-g;c[1]=j*a+d*-g+k*-b-i*-h;c[2]=k*a+d*-h+i*-g-j*-b;return c},toMat3:function(a,b){b||(b=mat3.create());var c=a[0],d=a[1],e=a[2],f=a[3],g=c+c,h=d+d,i=e+e,j=c*g,k=c*h;c*=i;var l=d*h;d*=i;e*=i;g*=f;h*=f;f*=i;b[0]=1-(l+e);b[1]=k-f;b[2]=c+h;b[3]=k+f;b[4]=1-(j+e);b[5]=d-g;b[6]=c-h;b[7]=d+g;b[8]=1-(j+l);return b},toMat4:function(a,b){b||(b=mat4.create());var c=a[0],d=a[1],e=a[2],f=a[3],g=c+c,h=d+d,i=
e+e,j=c*g,k=c*h;c*=i;var l=d*h;d*=i;e*=i;g*=f;h*=f;f*=i;b[0]=1-(l+e);b[1]=k-f;b[2]=c+h;b[3]=0;b[4]=k+f;b[5]=1-(j+e);b[6]=d-g;b[7]=0;b[8]=c-h;b[9]=d+g;b[10]=1-(j+l);b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b},slerp:function(a,b,c,d){d||(d=a);var e=a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3];if(Math.abs(e)>=1)return d!=a&&(d[0]=a[0],d[1]=a[1],d[2]=a[2],d[3]=a[3]),d;var f=Math.acos(e),g=Math.sqrt(1-e*e);if(Math.abs(g)<0.0010)return d[0]=a[0]*0.5+b[0]*0.5,d[1]=a[1]*0.5+b[1]*0.5,d[2]=a[2]*0.5+b[2]*0.5,
d[3]=a[3]*0.5+b[3]*0.5,d;e=Math.sin((1-c)*f)/g;c=Math.sin(c*f)/g;d[0]=a[0]*e+b[0]*c;d[1]=a[1]*e+b[1]*c;d[2]=a[2]*e+b[2]*c;d[3]=a[3]*e+b[3]*c;return d},str:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+"]"}};var JSON;JSON||(JSON={});
(function(){function a(a){return a<10?"0"+a:a}function b(a){e.lastIndex=0;return e.test(a)?'"'+a.replace(e,function(a){var b=h[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,d){var e,h,m,n,q=f,r,p=d[a];p&&typeof p==="object"&&typeof p.toJSON==="function"&&(p=p.toJSON(a));typeof i==="function"&&(p=i.call(d,a,p));switch(typeof p){case "string":return b(p);case "number":return isFinite(p)?String(p):"null";case "boolean":case "null":return String(p);
case "object":if(!p)return"null";f+=g;r=[];if(Object.prototype.toString.apply(p)==="[object Array]"){n=p.length;for(e=0;e<n;e+=1)r[e]=c(e,p)||"null";m=r.length===0?"[]":f?"[\n"+f+r.join(",\n"+f)+"\n"+q+"]":"["+r.join(",")+"]";f=q;return m}if(i&&typeof i==="object"){n=i.length;for(e=0;e<n;e+=1)typeof i[e]==="string"&&(h=i[e],(m=c(h,p))&&r.push(b(h)+(f?": ":":")+m))}else for(h in p)Object.prototype.hasOwnProperty.call(p,h)&&(m=c(h,p))&&r.push(b(h)+(f?": ":":")+m);m=r.length===0?"{}":f?"{\n"+f+r.join(",\n"+
f)+"\n"+q+"}":"{"+r.join(",")+"}";f=q;return m}}if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var d=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,f,g,h={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},i;if(typeof JSON.stringify!=="function")JSON.stringify=function(a,b,d){var e;g=f="";if(typeof d==="number")for(e=0;e<d;e+=1)g+=" ";else typeof d==="string"&&(g=d);if((i=b)&&typeof b!=="function"&&(typeof b!=="object"||typeof b.length!=="number"))throw Error("JSON.stringify");return c("",
{"":a})};if(typeof JSON.parse!=="function")JSON.parse=function(a,b){function c(a,d){var e,f,g=a[d];if(g&&typeof g==="object")for(e in g)Object.prototype.hasOwnProperty.call(g,e)&&(f=c(g,e),f!==void 0?g[e]=f:delete g[e]);return b.call(a,d,g)}var e,a=String(a);d.lastIndex=0;d.test(a)&&(a=a.replace(d,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),typeof b==="function"?c({"":e},""):e;throw new SyntaxError("JSON.parse");}})();Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Renderer"];
Tilt.Renderer=function(a,b,c){this.gl=this.create3DContext(a);Tilt.clearCache();Tilt.$gl=this.gl;Tilt.$renderer=this;"undefined"!==typeof this.gl?(this.TRIANGLES=this.gl.TRIANGLES,this.TRIANGLE_STRIP=this.gl.TRIANGLE_STRIP,this.TRIANGLE_FAN=this.gl.TRIANGLE_FAN,this.LINES=this.gl.LINES,this.LINE_STRIP=this.gl.LINE_STRIP,this.LINE_LOOP=this.gl.LINE_LOOP,this.POINTS=this.gl.POINTS,"function"===typeof c&&c()):(Tilt.Console.log(Tilt.StringBundle.get("initWebGL.error")),"function"===typeof b&&b());this.width=
a.width;this.height=a.height;this.mvMatrixStack=[];this.mvMatrix=mat4.identity(mat4.create());this.projMatrix=mat4.identity(mat4.create());this.clearColor=[0,0,0,0];this.tintColor=[0,0,0,0];this.fillColor=[0,0,0,0];this.strokeColor=[0,0,0,0];this.strokeWeightValue=0;this.colorShader=new Tilt.Program(Tilt.Shaders.Color.vs,Tilt.Shaders.Color.fs);this.textureShader=new Tilt.Program(Tilt.Shaders.Texture.vs,Tilt.Shaders.Texture.fs);this.rectangle=new Tilt.Rectangle;this.rectangleWireframe=new Tilt.RectangleWireframe;
this.cube=new Tilt.Cube;this.cubeWireframe=new Tilt.CubeWireframe;this.lastTime=0;this.currentTime=null;this.frameDelta=this.frameRate=this.frameCount=this.elapsedTime=0;this.blendMode("alpha");this.depthTest(!0);this.origin();this.perspective();this.tint("#fff");this.fill("#fff");this.stroke("#000");this.strokeWeight(1)};
Tilt.Renderer.prototype={clear:function(a,b,c,d){var e=this.clearColor,f=this.gl;if(e[0]!==a||e[1]!==b||e[2]!==c||e[3]!==d)e[0]=a,e[1]=b,e[2]=c,e[3]=d,f.clearColor(a,b,c,d);f.clear(f.COLOR_BUFFER_BIT|f.DEPTH_BUFFER_BIT)},background:function(a){a="string"===typeof a?Tilt.Math.hex2rgba(a):"undefined"===typeof a?[0,0,0,1]:"number"===typeof a?[a/255,a/255,a/255,1]:[a[0]/255,a[1]/255,a[2]/255,a[3]/255];this.clear(a[0],a[1],a[2],a[3])},perspective:function(){var a=this.width,b=this.height,c=a/2,d=b/2,e=
d/Math.tan(Tilt.Math.radians(45)/2);mat4.perspective(45,a/b,e/10,e*100,this.projMatrix,!0);mat4.translate(this.projMatrix,[-c,-d,-e])},ortho:function(){mat4.ortho(0,this.width,this.height,0,-1E3,1E3,this.projMatrix)},projection:function(a){mat4.set(a,this.projMatrix)},pushMatrix:function(){this.mvMatrixStack.push(mat4.create(this.mvMatrix))},popMatrix:function(){if(this.mvMatrixStack.length>0)this.mvMatrix=this.mvMatrixStack.pop()},origin:function(){mat4.identity(this.mvMatrix)},transform:function(a){mat4.multiply(this.mvMatrix,
a)},translate:function(a,b,c){mat4.translate(this.mvMatrix,[a,b,c])},rotate:function(a,b,c,d){mat4.rotate(this.mvMatrix,a,[b,c,d])},rotateX:function(a){mat4.rotateX(this.mvMatrix,a)},rotateY:function(a){mat4.rotateY(this.mvMatrix,a)},rotateZ:function(a){mat4.rotateZ(this.mvMatrix,a)},scale:function(a,b,c){mat4.scale(this.mvMatrix,[a,b,c])},tint:function(a){this.tintColor=Tilt.Math.hex2rgba(a)},noTint:function(){var a=this.tintColor;a[0]=1;a[1]=1;a[2]=1;a[3]=1},fill:function(a){this.fillColor=Tilt.Math.hex2rgba(a)},
noFill:function(){var a=this.fillColor;a[0]=0;a[1]=0;a[2]=0;a[3]=0},stroke:function(a){this.strokeColor=Tilt.Math.hex2rgba(a)},noStroke:function(){var a=this.strokeColor;a[0]=0;a[1]=0;a[2]=0;a[3]=0},strokeWeight:function(a){if(this.strokeWeightValue!==a)this.strokeWeightValue=a,this.gl.lineWidth(a)},blendMode:function(a){var b=this.gl;"alpha"===a?(b.enable(b.BLEND),b.blendFunc(b.SRC_ALPHA,b.ONE_MINUS_SRC_ALPHA)):"add"===a||"additive"===a?(b.enable(b.BLEND),b.blendFunc(b.SRC_ALPHA,b.ONE)):b.disable(b.BLEND)},
depthTest:function(a){var b=this.gl;a?b.enable(b.DEPTH_TEST):b.disable(b.DEPTH_TEST)},useColorShader:function(a,b){var c=this.colorShader;c.use();c.bindVertexBuffer("vertexPosition",a);c.bindUniformMatrix("mvMatrix",this.mvMatrix);c.bindUniformMatrix("projMatrix",this.projMatrix);c.bindUniformVec4("color",b)},useTextureShader:function(a,b,c,d){var e=this.textureShader;e.use();e.bindVertexBuffer("vertexPosition",a);e.bindVertexBuffer("vertexTexCoord",b);e.bindUniformMatrix("mvMatrix",this.mvMatrix);
e.bindUniformMatrix("projMatrix",this.projMatrix);e.bindUniformVec4("color",c);e.bindTexture("sampler",d)},triangle:function(a,b,c){a=new Tilt.VertexBuffer(a.concat(b,c),3);b=this.fillColor;c=this.strokeColor;b[3]&&(this.useColorShader(a,b),this.drawVertices(this.TRIANGLE_STRIP,a.numItems));c[3]&&(this.useColorShader(a,c),this.drawVertices(this.LINE_LOOP,a.numItems))},rectMode:function(a){this.rectangle.rectModeValue=a},rect:function(a,b,c,d){var e=this.rectangle,f=this.rectangleWireframe,g=this.fillColor,
h=this.strokeColor;"center"===this.rectangle.rectModeValue&&(a-=c/2,b-=d/2);this.pushMatrix();this.translate(a,b,0);this.scale(c,d,1);g[3]&&(this.useColorShader(e.vertices,g),this.drawVertices(this.TRIANGLE_STRIP,e.vertices.numItems));h[3]&&(this.useColorShader(f.vertices,h),this.drawVertices(this.LINE_STRIP,f.vertices.numItems));this.popMatrix()},imageMode:function(a){this.rectangle.imageModeValue=a},image:function(a,b,c,d,e){var f=this.rectangle,g=this.tintColor;if("undefined"===typeof d||"undefined"===
typeof e)d=texture.width,e=texture.height;"center"===f.imageModeValue&&(b-=d/2,c-=e/2);g[3]&&(this.pushMatrix(),this.translate(b,c,0),this.scale(d,e,1),this.useTextureShader(f.vertices,f.texCoord,g,a),this.drawVertices(this.TRIANGLE_STRIP,f.vertices.numItems),this.popMatrix())},box:function(a,b,c,d){var e=this.cube,f=this.cubeWireframe,g=this.tintColor,h=this.fillColor,i=this.strokeColor;this.pushMatrix();this.scale(a,b,c);d?g[3]&&(this.useTextureShader(e.vertices,e.texCoord,g,d),this.drawIndexedVertices(this.TRIANGLES,
e.indices)):h[3]&&(this.useColorShader(e.vertices,h),this.drawIndexedVertices(this.TRIANGLES,e.indices));i[3]&&(this.useColorShader(f.vertices,i),this.drawIndexedVertices(this.LINES,f.indices));this.popMatrix()},drawVertices:function(a,b){this.gl.drawArrays(a,0,b)},drawIndexedVertices:function(a,b){var c=this.gl;c.bindBuffer(c.ELEMENT_ARRAY_BUFFER,b.ref);c.drawElements(a,b.numItems,c.UNSIGNED_SHORT,0)},create3DContext:function(a,b){var c=["experimental-webgl","webgl","webkit-3d","moz-webgl"],d,e,
f;e=0;for(f=c.length;e<f;++e){try{d=a.getContext(c[e],b)}catch(g){}if(d)break}return d},loop:function(a){window.requestAnimFrame(a);this.origin();this.perspective();this.currentTime=(new Date).getTime();if(this.lastTime!==0)this.frameDelta=this.currentTime-this.lastTime,this.frameRate=1E3/this.frameDelta;this.lastTime=this.currentTime;this.elapsedTime+=this.frameDelta;this.frameCount++},destroy:function(){Tilt.clearCache();for(var a in this)"function"===typeof this[a].destroy&&this[a].destroy(),this[a]=
null}};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Shaders.Color"];Tilt.Shaders={};Tilt.Shaders.Color={vs:"attribute vec3 vertexPosition;\nuniform mat4 mvMatrix;\nuniform mat4 projMatrix;\nvoid main(void) {\n    gl_Position = projMatrix * mvMatrix * vec4(vertexPosition, 1.0);\n}",fs:"#ifdef GL_ES\nprecision highp float;\n#endif\nuniform vec4 color;\nvoid main(void) {\n    gl_FragColor = color;\n}"};
Tilt.Shaders.Texture={vs:"attribute vec3 vertexPosition;\nattribute vec2 vertexTexCoord;\nuniform mat4 mvMatrix;\nuniform mat4 projMatrix;\nvarying vec2 texCoord;\nvoid main(void) {\n  gl_Position = projMatrix * mvMatrix * vec4(vertexPosition, 1.0);\n  texCoord = vertexTexCoord;\n}",fs:"#ifdef GL_ES\nprecision highp float;\n#endif\nuniform vec4 color;\nuniform sampler2D sampler;\nvarying vec2 texCoord;\nvoid main(void) {\n  vec4 tex = texture2D(sampler, vec2(texCoord.s, texCoord.t));\n  gl_FragColor = color * tex;\n}"};
Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Arcball"];Tilt.Arcball=function(a,b,c){this.scrollValue=this.mouseDragY=this.mouseDragX=this.mouseY=this.mouseX=0;this.startVec=vec3.create();this.endVec=vec3.create();this.pVec=vec3.create();this.lastRot=quat4.create([0,0,0,1]);this.deltaRot=quat4.create([0,0,0,1]);this.currentRot=quat4.create([0,0,0,1]);this.currentZoom=0;this.resize(a,b,c)};
Tilt.Arcball.prototype={loop:function(a){a="undefined"===typeof a?0.25:Tilt.Math.clamp(a/100,0.01,0.99);this.currentZoom+=(this.scrollValue-this.currentZoom)*a;this.mouseX+=(this.mouseDragX-this.mouseX)*a;this.mouseY+=(this.mouseDragY-this.mouseY)*a;this.pointToSphere(this.mouseX,this.mouseY,this.width,this.height,this.radius,this.endVec);vec3.cross(this.startVec,this.endVec,this.pVec);vec3.length(this.pVec)>0?(this.deltaRot[0]=this.pVec[0],this.deltaRot[1]=this.pVec[1],this.deltaRot[2]=this.pVec[2],
this.deltaRot[3]=-vec3.dot(this.startVec,this.endVec)):(this.deltaRot[0]=0,this.deltaRot[1]=0,this.deltaRot[2]=0,this.deltaRot[3]=1);return{rotation:quat4.multiply(this.lastRot,this.deltaRot,this.currentRot),zoom:this.currentZoom}},mousePressed:function(a,b){this.mouseX=a;this.mouseY=b;this.pointToSphere(this.mouseX,this.mouseY,this.width,this.height,this.radius,this.startVec);quat4.set(this.currentRot,this.lastRot)},mouseDragged:function(a,b){this.mouseDragX=a;this.mouseDragY=b},mouseScroll:function(a){this.scrollValue-=
a*10},pointToSphere:function(a,b,c,d,e,f){a=(a-c/2)/e;b=(b-d/2)/e;c=a*a+b*b;d=0;c>1?(d=1/Math.sqrt(c),f[0]=a*d,f[1]=b*d,f[2]=0):(f[0]=a,f[1]=b,f[2]=Math.sqrt(1-c))},resize:function(a,b,c){this.width=a;this.height=b;this.radius="undefined"!==typeof c?c:b;this.pointToSphere(this.mouseX,this.mouseY,this.width,this.height,this.radius,this.startVec);quat4.set(this.currentRot,this.lastRot)},destroy:function(){for(var a in this)"function"===typeof this[a].destroy&&this[a].destroy(),this[a]=null}};
Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Extensions.WebGL"];Tilt.Extensions={};Tilt.Extensions.WebGL={initDocumentImage:function(a){var b,c,d,e;b=Tilt.Document.initCanvas();c=Tilt.Document.initCanvas();b=Tilt.Renderer.prototype.create3DContext(b);b=b.getParameter(b.MAX_TEXTURE_SIZE);d=a.innerWidth+a.scrollMaxX;e=a.innerHeight+a.scrollMaxY;d=Tilt.Math.clamp(d,0,b);b=Tilt.Math.clamp(e,0,b);c.width=d;c.height=b;c.getContext("2d").drawWindow(a,0,0,d,b,"#fff");return c}};Tilt=Tilt||{};
EXPORTED_SYMBOLS=["Tilt.Iframe","Tilt.Document","Tilt.Image","Tilt.Math","Tilt.String"];
Tilt.Document={currentContentDocument:void 0,currentParentNode:void 0,initCanvas:function(a,b,c,d){if("undefined"===typeof this.currentContentDocument)this.currentContentDocument=document;if("undefined"===typeof this.currentParentNode)this.currentParentNode=document.body;var e=this.currentParentNode,f=this.currentContentDocument.createElement("canvas");f.width=a;f.height=b;f.id=d;c&&this.append(f,e);return f},initFullScreenCanvas:function(){var a=this.initCanvas(window.innerWidth,window.innerHeight,
!0);a.setAttribute("style","width: 100%; height: 100%;");this.currentParentNode.setAttribute("style","margin: 0px 0px 0px 0px;");return a},append:function(a,b){b.appendChild(a)},remove:function(a){a.parentNode.removeChild(a)},traverse:function(a,b,c){function d(a,b,c){var i,j,k;i=0;for(j=b.childNodes.length;i<j;i++)k=b.childNodes[i],c>e&&(e=c),a(k,c),d(a,k,c+1)}var e=0;try{"function"===typeof a&&(d(a,c||window.content.document,0),a=null),"function"===typeof b&&(b(e),b=null)}finally{c=null}},getNodeCoordinates:function(a){var b=
0,c=0,d=a.clientWidth,e=a.clientHeight;if(a.offsetParent){do b+=a.offsetLeft,c+=a.offsetTop;while(a=a.offsetParent)}else{if(a.x)b=a.x;if(a.y)c=a.y}return{x:b,y:c,width:d,height:e}},getNodeType:function(a){var b;a.nodeType===1?b="ELEMENT_NODE":a.nodeType===2?b="ATTRIBUTE_NODE":a.nodeType===3?b="TEXT_NODE":a.nodeType===4?b="CDATA_SECTION_NODE":a.nodeType===5?b="ENTITY_REFERENCE_NODE":a.nodeType===6?b="ENTITY_NODE":a.nodeType===7?b="PROCESSING_INSTRUCTION_NODE":a.nodeType===8?b="COMMENT_NODE":a.nodeType===
9?b="DOCUMENT_NODE":a.nodeType===10?b="DOCUMENT_TYPE_NODE":a.nodeType===11?b="DOCUMENT_FRAGMENT_NODE":a.nodeType===12&&(b="NOTATION_NODE");return b}};
Tilt.Xhr={request:function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.send(null);d.onreadystatechange=function(){d.readyState===4&&"function"===typeof b&&(b(d,c),b=null)}},requests:function(a,b,c){function d(d,g){e[g]=d;f++;f===a.length&&"function"===typeof b&&(b(e,c),b=null)}var e=[],f=0,g,h;g=0;for(h=a.length;g<h;g++)this.request(a[g],d,g)}};
Tilt.Math={radians:function(a){return a*Math.PI/180},quat4fromAxis:function(a,b,c){b*=0.5;var d=Math.sin(b),e=a[0]*d,f=a[1]*d,a=a[2]*d,b=Math.cos(b);return"undefined"===typeof c?[e,f,a,b]:(c[0]=e,c[1]=f,c[2]=a,c[3]=b,c)},quat4fromEuler:function(a,b,c,d){a*=0.5;b*=0.5;c*=0.5;var e;e=Math.sin(c);var f=Math.sin(a),g=Math.sin(b),h=Math.cos(c),i=Math.cos(a),j=Math.cos(b),b=g*i*h-j*f*e,a=j*f*h+g*i*e,c=j*i*e-g*f*h;e=j*i*h+g*f*e;return"undefined"===typeof d?[b,a,c,e]:(d[0]=b,d[1]=a,d[2]=c,d[3]=e,d)},unproject:function(a,
b,c,d,e,f,g,h,i){var j=mat4.create(),k=quat4.create();mat4.multiply(e,d,j);mat4.inverse(j);k[0]=+((a-f)/h*2-1);k[1]=-((b-g)/i*2-1);k[2]=2*c-1;k[3]=1;mat4.multiplyVec4(j,k);k[3]=1/k[3];k[0]*=k[3];k[1]*=k[3];k[2]*=k[3];return k},createRay:function(a,b,c,d,e,f,g,h,i,j,k,l){a=this.unproject(a,b,c,g,h,i,j,k,l);d=this.unproject(d,e,f,g,h,i,j,k,l);return{position:a,lookAt:d,direction:vec3.normalize(vec3.subtract(d,a))}},intersectRayTriangle:function(a,b,c,d,e){var f=vec3.create(),g=vec3.create(),h=vec3.create(),
i=vec3.create(),j=vec3.create(),k=d.position,d=d.direction;"undefined"===typeof e&&(e=vec3.create());vec3.subtract(b,a,f);vec3.subtract(c,a,g);vec3.cross(f,g,h);if(h[0]===0&&h[1]===0&&h[2]===0)return-1;vec3.subtract(k,a,j);b=-vec3.dot(h,j);h=+vec3.dot(h,d);if(Math.abs(h)<1.0E-4)return b==0?2:0;h=b/h;if(h<0)return 0;vec3.add(k,vec3.scale(d,h),e);k=vec3.dot(f,f);d=vec3.dot(f,g);h=vec3.dot(g,g);vec3.subtract(e,a,i);a=vec3.dot(i,f);g=vec3.dot(i,g);i=d*d-k*h;e=(d*g-h*a)/i;if(e<0||e>1)return 0;g=(d*a-k*
g)/i;return g<0||e+g>1?0:1},isPowerOfTwo:function(a){return(a&a-1)===0},nextPowerOfTwo:function(a){var b;--a;for(b=1;b<32;b<<=1)a|=a>>b;return a+1},clamp:function(a,b,c){return Math.max(b,Math.min(c,a))},hex2rgba:function(a){if("undefined"!==typeof this[a])return this[a];var b,c,d,e;b=a.charAt(0)==="#"?a.substring(1):a;if(b.length===3)c=b.charAt(0),d=b.charAt(1),e=b.charAt(2),b=[c,c,d,d,e,e,"ff"].join("");else if(b.length===4)c=b.charAt(0),d=b.charAt(1),e=b.charAt(2),b=b.charAt(3),b=[c,c,d,d,e,e,
b,b].join("");else if(b.match("^rgba")=="rgba")return b=b.substring(5,b.length-1).split(","),b[0]/=255,b[1]/=255,b[2]/=255,b[3]/=255,this[a]=b;else if(b.match("^rgb")=="rgb")return b=b.substring(4,b.length-1).split(","),b[0]/=255,b[1]/=255,b[2]/=255,b[3]=1,this[a]=b;c=parseInt(b.substring(0,2),16)/255;d=parseInt(b.substring(2,4),16)/255;e=parseInt(b.substring(4,6),16)/255;b=b.length===6?1:parseInt(b.substring(6,8),16)/255;this[a]=[c,d,e,b];return[c,d,e,b]}};
Tilt.String={trim:function(a){return a.replace(/^\s+|\s+$/g,"")},ltrim:function(a){return a.replace(/^\s+/,"")},rtrim:function(a){return a.replace(/\s+$/,"")}};
Tilt.StringBundle={bundle:"tilt-string-bundle",get:function(a){if("undefined"===typeof a)return"undefined";var b=document.getElementById(this.bundle);return b?b.getString(a):a},format:function(a,b){if("undefined"===typeof a)return"undefined";if("undefined"===typeof b)return a;var c=document.getElementById(this.bundle);return c?c.getFormattedString(a,b):[a,b].join(" ")}};
Tilt.Console={log:function(a){try{"undefined"===typeof a&&(a="undefined"),Components.classes["@mozilla.org/consoleservice;1"].getService(Components.interfaces.nsIConsoleService).logStringMessage(a)}catch(b){alert(a)}},error:function(a,b,c,d,e,f,g){try{"undefined"===typeof a&&(a="undefined");var h=Components.classes["@mozilla.org/consoleservice;1"].getService(Components.interfaces.nsIConsoleService),i=Components.classes["@mozilla.org/scripterror;1"].createInstance(Components.interfaces.nsIScriptError);
i.init(a,b,c,d,e,f,g);h.logMessage(i)}catch(j){alert(a)}}};
