'use strict';var Tilt=Tilt||{},EXPORTED_SYMBOLS=["Tilt.Arcball"];Tilt.Arcball=function(a,b,c){this.scrollValue=this.mouseDragY=this.mouseDragX=this.mouseY=this.mouseX=0;this.startVec=vec3.create();this.endVec=vec3.create();this.pVec=vec3.create();this.lastRot=quat4.create([0,0,0,1]);this.deltaRot=quat4.create([0,0,0,1]);this.currentRot=quat4.create([0,0,0,1]);this.currentZoom=0;this.resize(a,b,c)};
Tilt.Arcball.prototype={loop:function(a){a="undefined"===typeof a?0.25:Tilt.Math.clamp(a/100,0.01,0.99);this.currentZoom+=(this.scrollValue-this.currentZoom)*a;this.mouseX+=(this.mouseDragX-this.mouseX)*a;this.mouseY+=(this.mouseDragY-this.mouseY)*a;this.pointToSphere(this.mouseX,this.mouseY,this.width,this.height,this.radius,this.endVec);vec3.cross(this.startVec,this.endVec,this.pVec);vec3.length(this.pVec)>0?(this.deltaRot[0]=this.pVec[0],this.deltaRot[1]=this.pVec[1],this.deltaRot[2]=this.pVec[2],
this.deltaRot[3]=-vec3.dot(this.startVec,this.endVec)):(this.deltaRot[0]=0,this.deltaRot[1]=0,this.deltaRot[2]=0,this.deltaRot[3]=1);return{rotation:quat4.multiply(this.lastRot,this.deltaRot,this.currentRot),zoom:this.currentZoom}},mousePressed:function(a,b){this.mouseX=a;this.mouseY=b;this.pointToSphere(this.mouseX,this.mouseY,this.width,this.height,this.radius,this.startVec);quat4.set(this.currentRot,this.lastRot)},mouseDragged:function(a,b){this.mouseDragX=a;this.mouseDragY=b},mouseScroll:function(a){this.scrollValue-=
a*10},pointToSphere:function(a,b,c,d,e,f){a=(a-c/2)/e;b=(b-d/2)/e;c=a*a+b*b;d=0;c>1?(d=1/Math.sqrt(c),f[0]=a*d,f[1]=b*d,f[2]=0):(f[0]=a,f[1]=b,f[2]=Math.sqrt(1-c))},resize:function(a,b,c){this.width=a;this.height=b;this.radius="undefined"!==typeof c?c:b;this.pointToSphere(this.mouseX,this.mouseY,this.width,this.height,this.radius,this.startVec);quat4.set(this.currentRot,this.lastRot)},destroy:function(){for(var a in this)delete this[a]}};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.VertexBuffer","Tilt.IndexBuffer"];
Tilt.VertexBuffer=function(a,b,c){this.ref=null;this.length=this.numItems=this.itemSize=0;"undefined"!==typeof a&&this.initBuffer(a,b,c)};Tilt.VertexBuffer.prototype={initBuffer:function(a,b,c){"undefined"===typeof c&&(c=a.length/b);var d=new Float32Array(a),e=Tilt.$gl;this.ref=e.createBuffer();e.bindBuffer(e.ARRAY_BUFFER,this.ref);e.bufferData(e.ARRAY_BUFFER,d,e.STATIC_DRAW);this.itemSize=b;this.numItems=c;this.length=a.length;b=0;for(c=a.length;b<c;b++)this[b]=a[b]},destroy:function(){for(var a in this)delete this[a]}};
Tilt.IndexBuffer=function(a,b){this.ref=null;this.numItems=this.itemSize=this.length=0;"undefined"!==typeof a&&this.initBuffer(a,b)};Tilt.IndexBuffer.prototype={initBuffer:function(a,b){if("undefined"===typeof b)b=a.length;var c=new Uint16Array(a),d=Tilt.$gl;this.ref=d.createBuffer();d.bindBuffer(d.ELEMENT_ARRAY_BUFFER,this.ref);d.bufferData(d.ELEMENT_ARRAY_BUFFER,c,d.STATIC_DRAW);this.itemSize=1;this.numItems=b;this.length=a.length;c=0;for(d=a.length;c<d;c++)this[c]=a[c]},destroy:function(){for(var a in this)delete this[a]}};
Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.activeShader","Tilt.enabledAttributes"];Tilt.$gl=null;Tilt.$renderer=null;Tilt.$activeShader=-1;Tilt.$enabledAttributes=-1;Tilt.$loadedTextures={};Tilt.clearCache=function(){Tilt.$gl=null;Tilt.$renderer=null;Tilt.$activeShader=-1;Tilt.$enabledAttributes=-1;Tilt.$loadedTextures={}};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Program"];
Tilt.Program=function(a,b){this.ref=null;this.id=0;this.uniforms=this.attributes=null;this.cache={};arguments.length===2&&this.initProgram(a,b)};
Tilt.Program.prototype={initProgram:function(a,b){this.ref=Tilt.GLSL.create(a,b);this.id=this.ref.id;this.attributes=this.ref.attributes;this.uniforms=this.ref.uniforms;delete this.ref.id;delete this.ref.attributes;delete this.ref.uniforms},initProgramAt:function(a,b,c){arguments.length===2&&(c=b,b=a+".fs",a+=".vs");var d=this;Tilt.Xhr.requests([a,b],function(a){d.initProgram(a[0].responseText,a[1].responseText);"function"===typeof c&&c()})},use:function(){if(Tilt.$activeShader!==this.id){Tilt.$activeShader=
this.id;var a=Tilt.$gl;a.useProgram(this.ref);if(Tilt.$enabledAttributes<this.attributes.length){Tilt.$enabledAttributes=this.attributes.length;for(var b in this.attributes)this.attributes.hasOwnProperty(b)&&b!=="length"&&a.enableVertexAttribArray(this.attributes[b])}}},bindVertexBuffer:function(a,b){var c=Tilt.$gl,d=this.attributes[a],e=b.itemSize;c.bindBuffer(c.ARRAY_BUFFER,b.ref);c.vertexAttribPointer(d,e,c.FLOAT,!1,0,0)},bindUniformMatrix:function(a,b){var c=b[0]+b[1]+b[2]+(b[4]+b[5]+b[6])+(b[8]+
b[9]+b[10])+(b[12]+b[13]+b[14]);this.cache[a]!==c&&(this.cache[a]=c,Tilt.$gl.uniformMatrix4fv(this.uniforms[a],!1,b))},bindUniformVec4:function(a,b){var c=b[3]*255<<24|b[0]*255<<16|b[1]*255<<8|b[2]*255;this.cache[a]!==c&&(this.cache[a]=c,Tilt.$gl.uniform4fv(this.uniforms[a],b))},bindUniformFloat:function(a,b){this.cache[a]!==b&&(this.cache[a]=b,Tilt.$gl.uniform1f(this.uniforms[a],b))},bindTexture:function(a,b){if(this.cache[a]!==b.id){this.cache[a]=b.id;var c=Tilt.$gl;c.bindTexture(c.TEXTURE_2D,b.ref);
c.uniform1i(this.uniforms[a],0)}},destroy:function(){for(var a in this)try{"function"===typeof this[a].destroy&&this[a].destroy()}catch(b){}finally{delete this[a]}}};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.GLSL"];
Tilt.GLSL={create:function(a,b){var c=this.compile(a,"x-shader/x-vertex"),d=this.compile(b,"x-shader/x-fragment");return this.link(c,d)},compile:function(a,b){var c=Tilt.$gl,d;if("string"!==typeof a||a.length<1)return Tilt.Console.error(Tilt.StringBundle.get("compileShader.source.error")),null;if(b==="x-shader/x-vertex")d=c.createShader(c.VERTEX_SHADER);else if(b==="x-shader/x-fragment")d=c.createShader(c.FRAGMENT_SHADER);else return Tilt.Console.error(Tilt.StringBundle.format("compileShader.type.error"),
[a]),null;c.shaderSource(d,a);c.compileShader(d);d.src=a;return!c.getShaderParameter(d,c.COMPILE_STATUS)?(c=c.getShaderInfoLog(d),Tilt.Console.error(Tilt.StringBundle.format("compileShader.compile.error"),[c]),null):d},link:function(a,b){var c=Tilt.$gl,d;d=c.createProgram();c.attachShader(d,a);c.attachShader(d,b);c.linkProgram(d);if(!c.getProgramParameter(d,c.LINK_STATUS))return d=c.getProgramInfoLog(d),Tilt.Console.error(Tilt.StringBundle.format("linkProgram.error",[d])),null;d.id=++this.count;c=
[a.src,b.src].join(" ").replace(/#.*|[(){};,]/g," ").split(" ");return this.shaderIOCache(d,c)},shaderAttribute:function(a,b){return Tilt.$gl.getAttribLocation(a,b)},shaderUniform:function(a,b){return Tilt.$gl.getUniformLocation(a,b)},shaderIO:function(a,b){if("string"===typeof b){if(b.length<1)return null;var c;return(c=this.shaderAttribute(a,b))>=0?c:this.shaderUniform(a,b)}return null},shaderIOCache:function(a,b){var c,d,e,f;a.attributes={};a.attributes.length=0;a.uniforms={};c=0;for(d=b.length;c<
d;c++)e=b[c],f=this.shaderIO(a,e),"number"===typeof f&&"undefined"===typeof a.attributes[e]&&(a.attributes[e]=f,a.attributes.length++),"object"===typeof f&&f instanceof WebGLUniformLocation&&"undefined"===typeof a.uniforms[e]&&(a.uniforms[e]=f);return a},count:0};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Texture"];
Tilt.Texture=function(a,b,c){this.ref=null;this.id=0;this.height=this.width=-1;this.loaded=!1;this.onload=c;"object"===typeof a?this.initTexture(a,b):"string"===typeof a?this.initTextureAt(a,b):Tilt.Console.error(Tilt.StringBundle.get("initTexture.source.error"))};
Tilt.Texture.prototype={initTexture:function(a,b){this.ref=Tilt.TextureUtils.create(a,b);this.id=this.ref.id;this.width=this.ref.width;this.height=this.ref.height;this.loaded=!0;if("undefined"!==typeof this.onload)this.onload();delete this.ref.id;delete this.ref.width;delete this.ref.height;delete this.onload},initTextureAt:function(a,b){var c=this,d=new Image;d.src=a;d.onload=function(){c.initTexture(d,b);b=d=c=null}},destroy:function(){for(var a in this)try{"function"===typeof this[a].destroy&&
this[a].destroy()}catch(b){}finally{delete this[a]}}};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.TextureUtils"];
Tilt.TextureUtils={create:function(a,b){b=b||{};if("undefined"!==typeof Tilt.$loadedTextures[a.src])return Tilt.$loadedTextures[a.src];var c=Tilt.$gl,d=Tilt.TextureUtils.resizeImageToPowerOfTwo(a,b),e=a.width,f=a.height,g=c.createTexture();c.bindTexture(c.TEXTURE_2D,g);c.texImage2D(c.TEXTURE_2D,0,c.RGBA,c.RGBA,c.UNSIGNED_BYTE,d);g.width=e;g.height=f;g.id=++this.count;this.setTextureParams(b);c.bindTexture(c.TEXTURE_2D,null);"undefined"!==typeof a.src&&(Tilt.$loadedTextures[a.src]=g);return g},setTextureParams:function(a){var b=
Tilt.$gl,c=b.TEXTURE_MIN_FILTER,d=b.TEXTURE_MAG_FILTER,e=b.TEXTURE_WRAP_S,f=b.TEXTURE_WRAP_T,a=a||{};a.texture&&b.bindTexture(b.TEXTURE_2D,a.texture.ref);"nearest"===a.minFilter?b.texParameteri(b.TEXTURE_2D,c,b.NEAREST):"linear"===a.minFilter&&a.mipmap?b.texParameteri(b.TEXTURE_2D,c,b.LINEAR_MIPMAP_LINEAR):b.texParameteri(b.TEXTURE_2D,c,b.LINEAR);"nearest"===a.magFilter?b.texParameteri(b.TEXTURE_2D,d,b.NEAREST):"linear"===a.magFilter&&a.mipmap?b.texParameteri(b.TEXTURE_2D,d,b.LINEAR_MIPMAP_LINEAR):
b.texParameteri(b.TEXTURE_2D,d,b.LINEAR);"repeat"===a.wrapS?b.texParameteri(b.TEXTURE_2D,e,b.REPEAT):b.texParameteri(b.TEXTURE_2D,e,b.CLAMP_TO_EDGE);"repeat"===a.wrapT?b.texParameteri(b.TEXTURE_2D,f,b.REPEAT):b.texParameteri(b.TEXTURE_2D,f,b.CLAMP_TO_EDGE);a.mipmap&&b.generateMipmap(b.TEXTURE_2D)},resizeImageToPowerOfTwo:function(a,b){var c=(a.src||"").indexOf("chrome://"),d=Tilt.Math.isPowerOfTwo(a.width),e=Tilt.Math.isPowerOfTwo(a.height);if(d&&e&&c===-1)try{return a}finally{b=a=null}b=b||{};c=
Tilt.Math.nextPowerOfTwo(a.width);d=Tilt.Math.nextPowerOfTwo(a.height);c=Tilt.Document.initCanvas(c,d);d=c.getContext("2d");if(b.fill)d.fillStyle=b.fill,d.fillRect(0,0,c.width,c.height);d.drawImage(a,0,0,a.width,a.height,0,0,c.width,c.height);if(b.stroke)d.strokeStyle=b.stroke,d.lineWidth=b.strokeWeight,d.strokeRect(0,0,c.width,c.height);return c},setTextureFlipY:function(a){Tilt.$gl.pixelStorei(Tilt.$gl.UNPACK_FLIP_Y_WEBGL,a)},count:0};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Button"];
Tilt.Button=function(a,b,c,d){this.x=a||0;this.y=b||0;this.width=c.width;this.height=c.height;this.sprite=c;this.$bounds=[this.x,this.y,this.width,this.height];if("function"===typeof d)this.onclick=d};
Tilt.Button.prototype={update:function(){var a=this.sprite,b=this.$bounds,c=this.x,d=this.y,e=this.width,f=this.height;b[0]=c;b[1]=d;b[2]=e;b[3]=f;a.x=c;a.y=d;a.width=e;a.height=f},draw:function(a){a=a||Tilt.$renderer;this.sprite.draw(a)},destroy:function(){for(var a in this)try{"function"===typeof this[a].destroy&&this[a].destroy()}catch(b){}finally{delete this[a]}}};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Lightbox"];
Tilt.Lightbox=function(a,b){this.color=a;this.sprite=b;this.$bounds=[b.x,b.y,b.width,b.height]};Tilt.Lightbox.prototype={update:function(){var a=this.sprite,b=this.$bounds,c=a.$bounds;a.update();b[0]=c[0];b[1]=c[1];b[2]=c[2];b[3]=c[3]},draw:function(a){a=a||Tilt.$renderer;a.fill(this.color);a.noStroke();a.rect(0,0,a.width,a.height);this.sprite.draw(a)},destroy:function(){for(var a in this)try{"function"===typeof this[a].destroy&&this[a].destroy()}catch(b){}finally{delete this[a]}}};Tilt=Tilt||{};
EXPORTED_SYMBOLS=["Tilt.Sprite"];Tilt.Sprite=function(a,b,c,d,e,f){this.texture=a;this.region=b||[0,0,a.width,a.height];this.x=c||0;this.y=d||0;this.width=e||this.region[2];this.height=f||this.region[3];this.$bounds=[this.x,this.y,this.width,this.height];this.$texCoord=null};
Tilt.Sprite.prototype={refresh:function(){this.$texCoord=null},update:function(){var a=this.$bounds,b=this.y,c=this.width,d=this.height;a[0]=this.x;a[1]=b;a[2]=c;a[3]=d},draw:function(a){a=a||Tilt.$renderer;if(this.$texCoord===null&&this.texture.loaded){var b=this.region,c=this.texture;this.$texCoord=new Tilt.VertexBuffer([b[0]/c.width,b[1]/c.height,(b[0]+b[2])/c.width,b[1]/c.height,b[0]/c.width,(b[1]+b[3])/c.height,(b[0]+b[2])/c.width,(b[1]+b[3])/c.height],2)}a.image(this.texture,this.x,this.y,this.width,
this.height,this.$texCoord)},destroy:function(){for(var a in this)try{"function"===typeof this[a].destroy&&this[a].destroy()}catch(b){}finally{delete this[a]}}};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.GUI"];Tilt.GUI=function(){this.elements=[]};
Tilt.GUI.prototype={push:function(){for(var a=0,b=arguments.length;a<b;a++)this.elements.push(arguments[a])},remove:function(){for(var a=0,b=arguments.length,c=-1;a<b;a++)(c=this.elements.indexOf(arguments[a]))!==-1&&this.elements.splice(c,1)},draw:function(){var a=Tilt.$renderer,b=this.elements,c,d,e;a.ortho();a.origin();a.defaults();d=0;for(e=b.length;d<e;d++)c=b[d],c.update(),c.hidden||c.draw(a)},click:function(a,b){var c=this.elements,d,e,f,g,h,i,k;i=0;for(k=c.length;i<k;i++)if(d=c[i],e=d.$bounds||
[-1,-1,-1,-1],f=e[0],g=e[1],h=e[2],e=e[3],a>f&&a<f+h&&b>g&&b<g+e&&"function"===typeof d.onclick)d.onclick(a,b)},doubleClick:function(){},destroy:function(){for(var a in this.elements)try{"function"===typeof this.elements[a].destroy&&this.elements[a].destroy()}catch(b){}finally{delete this.elements[a]}for(var c in this)try{"function"===typeof this[c].destroy&&this[c].destroy()}catch(d){}finally{delete this[c]}}};
function style_html(a,b){var c,d,e,f,b=b||{};d=b.indent_size||2;e=b.indent_char||" ";f=b.brace_style||"collapse";c=new function(){this.pos=0;this.token="";this.current_mode="CONTENT";this.tags={parent:"parent1",parentcount:1,parent1:""};this.token_text=this.last_token=this.last_text=this.token_type=this.tag_type="";this.Utils={whitespace:"\n\r\t ".split(""),single_token:"br,input,link,meta,!doctype,basefont,base,area,hr,wbr,param,img,isindex,?xml,embed".split(","),extra_liners:"head,body,/html".split(","),
in_array:function(a,b){for(var c=0;c<b.length;c++)if(a===b[c])return!0;return!1}};this.get_content=function(){for(var a="",b=[],c=!1;this.input.charAt(this.pos)!=="<";){if(this.pos>=this.input.length)return b.length?b.join(""):["","TK_EOF"];a=this.input.charAt(this.pos);this.pos++;this.line_char_count++;if(this.Utils.in_array(a,this.Utils.whitespace))b.length&&(c=!0),this.line_char_count--;else{if(c){if(this.line_char_count>=this.max_char){b.push("\n");for(c=0;c<this.indent_level;c++)b.push(this.indent_string);
this.line_char_count=0}else b.push(" "),this.line_char_count++;c=!1}b.push(a)}}return b.length?b.join(""):""};this.get_script=function(){var a="",b=[],a=/<\/script>/igm;a.lastIndex=this.pos;for(var c=(a=a.exec(this.input))?a.index:this.input.length;this.pos<c;){if(this.pos>=this.input.length)return b.length?b.join(""):["","TK_EOF"];a=this.input.charAt(this.pos);this.pos++;b.push(a)}return b.length?b.join(""):""};this.record_tag=function(a){this.tags[a+"count"]?this.tags[a+"count"]++:this.tags[a+"count"]=
1;this.tags[a+this.tags[a+"count"]]=this.indent_level;this.tags[a+this.tags[a+"count"]+"parent"]=this.tags.parent;this.tags.parent=a+this.tags[a+"count"]};this.retrieve_tag=function(a){if(this.tags[a+"count"]){for(var b=this.tags.parent;b;){if(a+this.tags[a+"count"]===b)break;b=this.tags[b+"parent"]}if(b)this.indent_level=this.tags[a+this.tags[a+"count"]],this.tags.parent=this.tags[b+"parent"];delete this.tags[a+this.tags[a+"count"]+"parent"];delete this.tags[a+this.tags[a+"count"]];this.tags[a+"count"]==
1?delete this.tags[a+"count"]:this.tags[a+"count"]--}};this.get_tag=function(){var a="",b=[],c=!1;do{if(this.pos>=this.input.length)return b.length?b.join(""):["","TK_EOF"];a=this.input.charAt(this.pos);this.pos++;this.line_char_count++;if(this.Utils.in_array(a,this.Utils.whitespace))c=!0,this.line_char_count--;else{if(a==="'"||a==='"')if(!b[1]||b[1]!=="!")a+=this.get_unformatted(a),c=!0;a==="="&&(c=!1);if(b.length&&b[b.length-1]!=="="&&a!==">"&&c)this.line_char_count>=this.max_char?(this.print_newline(!1,
b),this.line_char_count=0):(b.push(" "),this.line_char_count++),c=!1;b.push(a)}}while(a!==">");a=b.join("");c=a.indexOf(" ")!=-1?a.indexOf(" "):a.indexOf(">");c=a.substring(1,c).toLowerCase();a.charAt(a.length-2)==="/"||this.Utils.in_array(c,this.Utils.single_token)?this.tag_type="SINGLE":c==="script"?(this.record_tag(c),this.tag_type="SCRIPT"):c==="style"?(this.record_tag(c),this.tag_type="STYLE"):c==="a"?(a=this.get_unformatted("</a>",a),b.push(a),this.tag_type="SINGLE"):c.charAt(0)==="!"?c.indexOf("[if")!=
-1?(a.indexOf("!IE")!=-1&&(a=this.get_unformatted("--\>",a),b.push(a)),this.tag_type="START"):c.indexOf("[endif")!=-1?(this.tag_type="END",this.unindent()):(a=c.indexOf("[cdata[")!=-1?this.get_unformatted("]]\>",a):this.get_unformatted("--\>",a),b.push(a),this.tag_type="SINGLE"):(c.charAt(0)==="/"?(this.retrieve_tag(c.substring(1)),this.tag_type="END"):(this.record_tag(c),this.tag_type="START"),this.Utils.in_array(c,this.Utils.extra_liners)&&this.print_newline(!0,this.output));return b.join("")};
this.get_unformatted=function(a,b){if(b&&b.indexOf(a)!=-1)return"";var c="",d="",e=!0;do{if(this.pos>=this.input.length)break;c=this.input.charAt(this.pos);this.pos++;if(this.Utils.in_array(c,this.Utils.whitespace)){if(!e){this.line_char_count--;continue}if(c==="\n"||c==="\r"){d+="\n";for(c=0;c<this.indent_level;c++)d+=this.indent_string;e=!1;this.line_char_count=0;continue}}d+=c;this.line_char_count++;e=!0}while(d.indexOf(a)==-1);return d};this.get_token=function(){var a;if(this.last_token==="TK_TAG_SCRIPT"){a=
this.get_script();if(typeof a!=="string")return a;a=js_beautify(a,{indent_size:this.indent_size,indent_char:this.indent_character,indent_level:this.indent_level,brace_style:this.brace_style});return[a.replace(/^[\t ]+/,""),"TK_CONTENT"]}if(this.current_mode==="CONTENT")return a=this.get_content(),typeof a!=="string"?a:[a,"TK_CONTENT"];if(this.current_mode==="TAG")return a=this.get_tag(),typeof a!=="string"?a:[a,"TK_TAG_"+this.tag_type]};this.printer=function(a,b,c,d,e){this.input=a||"";this.output=
[];this.indent_character=b;this.indent_string="";this.indent_size=c;this.brace_style=e;this.indent_level=0;this.max_char=d;for(a=this.line_char_count=0;a<this.indent_size;a++)this.indent_string+=this.indent_character;this.print_newline=function(a,b){this.line_char_count=0;if(b&&b.length){if(!a)for(;this.Utils.in_array(b[b.length-1],this.Utils.whitespace);)b.pop();b.push("\n");for(var c=0;c<this.indent_level;c++)b.push(this.indent_string)}};this.print_token=function(a){this.output.push(a)};this.indent=
function(){this.indent_level++};this.unindent=function(){this.indent_level>0&&this.indent_level--}};return this};for(c.printer(a,e,d,80,f);;){d=c.get_token();c.token_text=d[0];c.token_type=d[1];if(c.token_type==="TK_EOF")break;switch(c.token_type){case "TK_TAG_START":case "TK_TAG_SCRIPT":case "TK_TAG_STYLE":c.print_newline(!1,c.output);c.print_token(c.token_text);c.indent();c.current_mode="CONTENT";break;case "TK_TAG_END":c.print_newline(!0,c.output);c.print_token(c.token_text);c.current_mode="CONTENT";
break;case "TK_TAG_SINGLE":c.print_newline(!1,c.output);c.print_token(c.token_text);c.current_mode="CONTENT";break;case "TK_CONTENT":c.token_text!==""&&(c.print_newline(!1,c.output),c.print_token(c.token_text)),c.current_mode="TAG"}c.last_token=c.token_type;c.last_text=c.token_text}return c.output.join("")}
function js_beautify(a,b){function c(a){for(a=typeof a==="undefined"?!1:a;m.length&&(m[m.length-1]===" "||m[m.length-1]===B||m[m.length-1]===O||a&&(m[m.length-1]==="\n"||m[m.length-1]==="\r"));)m.pop()}function d(a){return a.replace(/^\s\s*|\s\s*$/,"")}function e(){var a=H;H=!1;f();H=a}function f(a){j.eat_next_space=!1;if(!H||!n(j.mode))if(a=typeof a==="undefined"?!0:a,j.if_line=!1,c(),m.length){if(m[m.length-1]!=="\n"||!a)K=!0,m.push("\n");O&&m.push(O);for(a=0;a<j.indentation_level;a+=1)m.push(B);
j.var_line&&j.var_line_reindented&&(R===" "?m.push("    "):m.push(B))}}function g(){if(j.eat_next_space)j.eat_next_space=!1;else{var a=" ";m.length&&(a=m[m.length-1]);a!==" "&&a!=="\n"&&a!==B&&m.push(" ")}}function h(){K=!1;j.eat_next_space=!1;m.push(u)}function i(){m.length&&m[m.length-1]===B&&m.pop()}function k(a){j&&C.push(j);j={previous_mode:j?j.mode:"BLOCK",mode:a,var_line:!1,var_line_tainted:!1,var_line_reindented:!1,in_html_comment:!1,if_line:!1,in_case:!1,eat_next_space:!1,indentation_baseline:-1,
indentation_level:j?j.indentation_level+(j.var_line&&j.var_line_reindented?1:0):0,ternary_depth:0}}function n(a){return a==="[EXPRESSION]"||a==="[INDENTED-EXPRESSION]"}function s(a){return a==="[EXPRESSION]"||a==="[INDENTED-EXPRESSION]"||a==="(EXPRESSION)"}function v(){P=j.mode==="DO_BLOCK";C.length>0&&(j=C.pop())}function t(a,b){for(var c=0;c<a.length;c++)if(d(a[c])[0]!=b)return!1;return!0}function p(a,b){for(var c=0;c<b.length;c+=1)if(b[c]===a)return!0;return!1}function x(){I=0;if(l>=D)return["",
"TK_EOF"];N=!1;var a=o.charAt(l);l+=1;if(H&&n(j.mode)){for(var b=0;p(a,E);){a==="\n"?(c(),m.push("\n"),K=!0,b=0):a==="\t"?b+=4:a!=="\r"&&(b+=1);if(l>=D)return["","TK_EOF"];a=o.charAt(l);l+=1}if(j.indentation_baseline===-1)j.indentation_baseline=b;if(K){var e;for(e=0;e<j.indentation_level+1;e+=1)m.push(B);if(j.indentation_baseline!==-1)for(e=0;e<b-j.indentation_baseline;e++)m.push(" ")}}else{for(;p(a,E);){a==="\n"&&(I+=S?I<=S?1:0:1);if(l>=D)return["","TK_EOF"];a=o.charAt(l);l+=1}if(Q&&I>1)for(e=0;e<
I;e+=1)f(e===0),K=!0;N=I>0}if(p(a,F)){if(l<D)for(;p(o.charAt(l),F);)if(a+=o.charAt(l),l+=1,l===D)break;if(l!==D&&a.match(/^[0-9]+[Ee]$/)&&(o.charAt(l)==="-"||o.charAt(l)==="+"))return b=o.charAt(l),l+=1,e=x(l),a+=b+e[0],[a,"TK_WORD"];if(a==="in")return[a,"TK_OPERATOR"];N&&r!=="TK_OPERATOR"&&r!=="TK_EQUALS"&&!j.if_line&&(Q||q!=="var")&&f();return[a,"TK_WORD"]}if(a==="("||a==="[")return[a,"TK_START_EXPR"];if(a===")"||a==="]")return[a,"TK_END_EXPR"];if(a==="{")return[a,"TK_START_BLOCK"];if(a==="}")return[a,
"TK_END_BLOCK"];if(a===";")return[a,"TK_SEMICOLON"];if(a==="/"){b="";e=!0;if(o.charAt(l)==="*"){l+=1;if(l<D)for(;!(o.charAt(l)==="*"&&o.charAt(l+1)&&o.charAt(l+1)==="/")&&l<D;){a=o.charAt(l);b+=a;if(a==="\r"||a==="\n")e=!1;l+=1;if(l>=D)break}l+=2;return e?["/*"+b+"*/","TK_INLINE_COMMENT"]:["/*"+b+"*/","TK_BLOCK_COMMENT"]}if(o.charAt(l)==="/"){for(b=a;o.charAt(l)!=="\r"&&o.charAt(l)!=="\n";)if(b+=o.charAt(l),l+=1,l>=D)break;l+=1;N&&f();return[b,"TK_COMMENT"]}}if(a==="'"||a==='"'||a==="/"&&(r==="TK_WORD"&&
p(q,["return","do"])||r==="TK_COMMENT"||r==="TK_START_EXPR"||r==="TK_START_BLOCK"||r==="TK_END_BLOCK"||r==="TK_OPERATOR"||r==="TK_EQUALS"||r==="TK_EOF"||r==="TK_SEMICOLON")){b=a;e=!1;var g=a;if(l<D)if(b==="/")for(a=!1;e||a||o.charAt(l)!==b;){if(g+=o.charAt(l),e?e=!1:(e=o.charAt(l)==="\\",o.charAt(l)==="["?a=!0:o.charAt(l)==="]"&&(a=!1)),l+=1,l>=D)return[g,"TK_STRING"]}else for(;e||o.charAt(l)!==b;)if(g+=o.charAt(l),e=e?!1:o.charAt(l)==="\\",l+=1,l>=D)return[g,"TK_STRING"];l+=1;g+=b;if(b==="/")for(;l<
D&&p(o.charAt(l),F);)g+=o.charAt(l),l+=1;return[g,"TK_STRING"]}if(a==="#"){if(m.length===0&&o.charAt(l)==="!"){for(g=a;l<D&&a!="\n";)a=o.charAt(l),g+=a,l+=1;m.push(d(g)+"\n");f();return x()}b="#";if(l<D&&p(o.charAt(l),L)){do a=o.charAt(l),b+=a,l+=1;while(l<D&&a!=="#"&&a!=="=");a!=="#"&&(o.charAt(l)==="["&&o.charAt(l+1)==="]"?(b+="[]",l+=2):o.charAt(l)==="{"&&o.charAt(l+1)==="}"&&(b+="{}",l+=2));return[b,"TK_WORD"]}}if(a==="<"&&o.substring(l-1,l+3)==="<\!--")return l+=3,j.in_html_comment=!0,["<\!--",
"TK_COMMENT"];if(a==="-"&&j.in_html_comment&&o.substring(l-1,l+2)==="--\>")return j.in_html_comment=!1,l+=2,N&&f(),["--\>","TK_COMMENT"];if(p(a,G)){for(;l<D&&p(a+o.charAt(l),G);)if(a+=o.charAt(l),l+=1,l>=D)break;return a==="="?[a,"TK_EQUALS"]:[a,"TK_OPERATOR"]}return[a,"TK_UNKNOWN"]}var o,m,u,r,q,w,A,j,C,B,E,F,G,l,z,L,y,M,P,N,K,I,O="",b=b?b:{},J;if(b.space_after_anon_function!==void 0&&b.jslint_happy===void 0)b.jslint_happy=b.space_after_anon_function;b.braces_on_own_line!==void 0&&(J=b.braces_on_own_line?
"expand":"collapse");J=b.brace_style?b.brace_style:J?J:"collapse";A=b.indent_size?b.indent_size:2;var R=b.indent_char?b.indent_char:" ",Q=typeof b.preserve_newlines==="undefined"?!0:b.preserve_newlines,S=typeof b.max_preserve_newlines==="undefined"?!1:b.max_preserve_newlines,T=b.jslint_happy==="undefined"?!1:b.jslint_happy,H=typeof b.keep_array_indentation==="undefined"?!1:b.keep_array_indentation;K=!1;var D=a.length;for(B="";A>0;)B+=R,A-=1;for(;a&&(a[0]===" "||a[0]==="\t");)O+=a[0],a=a.substring(1);
o=a;A="";r="TK_START_EXPR";w=q="";m=[];P=!1;E="\n\r\t ".split("");F="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_$".split("");L="0123456789".split("");G="+ - * / % & ++ -- = += -= *= /= %= == === != !== > < >= <= >> << >>> >>>= >>= <<= && &= | || ! !! , : ? ^ ^= |= ::".split(" ");z="continue,try,throw,return,var,if,switch,case,default,for,while,break,function".split(",");C=[];k("BLOCK");for(l=0;;){M=x(l);u=M[0];M=M[1];if(M==="TK_EOF")break;switch(M){case "TK_START_EXPR":if(u===
"["){if(r==="TK_WORD"||q===")"){p(q,z)&&g();k("(EXPRESSION)");h();break}if(j.mode==="[EXPRESSION]"||j.mode==="[INDENTED-EXPRESSION]")if(w==="]"&&q===","){if(j.mode==="[EXPRESSION]")j.mode="[INDENTED-EXPRESSION]",H||(j.indentation_level+=1);k("[EXPRESSION]");H||f()}else if(q==="["){if(j.mode==="[EXPRESSION]")j.mode="[INDENTED-EXPRESSION]",H||(j.indentation_level+=1);k("[EXPRESSION]");H||f()}else k("[EXPRESSION]");else k("[EXPRESSION]")}else k("(EXPRESSION)");q===";"||r==="TK_START_BLOCK"?f():r==="TK_END_EXPR"||
r==="TK_START_EXPR"||r==="TK_END_BLOCK"||q==="."||(r!=="TK_WORD"&&r!=="TK_OPERATOR"?g():A==="function"||A==="typeof"?T&&g():(p(q,z)||q==="catch")&&g());h();break;case "TK_END_EXPR":if(u==="]")if(H){if(q==="}"){i();h();v();break}}else if(j.mode==="[INDENTED-EXPRESSION]"&&q==="]"){v();f();h();break}v();h();break;case "TK_START_BLOCK":A==="do"?k("DO_BLOCK"):k("BLOCK");J=="expand"?(r!=="TK_OPERATOR"&&(q==="return"||q==="="?g():f(!0)),h(),j.indentation_level+=1):(r!=="TK_OPERATOR"&&r!=="TK_START_EXPR"?
r==="TK_START_BLOCK"?f():g():n(j.previous_mode)&&q===","&&(w==="}"?g():f()),j.indentation_level+=1,h());break;case "TK_END_BLOCK":v();J=="expand"?q!=="{"&&f():r==="TK_START_BLOCK"?K?i():c():n(j.mode)&&H?(H=!1,f(),H=!0):f();h();break;case "TK_WORD":if(P){g();h();g();P=!1;break}if(u==="function"){if(j.var_line)j.var_line_reindented=!0;if((K||q===";")&&q!=="{"){I=K?I:0;Q||(I=1);for(y=0;y<2-I;y++)f(!1)}}if(u==="case"||u==="default"){q===":"?i():(j.indentation_level--,f(),j.indentation_level++);h();j.in_case=
!0;break}y="NONE";r==="TK_END_BLOCK"?p(u.toLowerCase(),["else","catch","finally"])?J=="expand"||J=="end-expand"?y="NEWLINE":(y="SPACE",g()):y="NEWLINE":r==="TK_SEMICOLON"&&(j.mode==="BLOCK"||j.mode==="DO_BLOCK")?y="NEWLINE":r==="TK_SEMICOLON"&&s(j.mode)?y="SPACE":r==="TK_STRING"?y="NEWLINE":r==="TK_WORD"?(q==="else"&&c(!0),y="SPACE"):r==="TK_START_BLOCK"?y="NEWLINE":r==="TK_END_EXPR"&&(g(),y="NEWLINE");p(u,z)&&q!==")"&&(y=q=="else"?"SPACE":"NEWLINE");if(j.if_line&&r==="TK_END_EXPR")j.if_line=!1;if(p(u.toLowerCase(),
["else","catch","finally"]))r!=="TK_END_BLOCK"||J=="expand"||J=="end-expand"?f():(c(!0),g());else if(y==="NEWLINE"){if(!((r==="TK_START_EXPR"||q==="="||q===",")&&u==="function"))if(u==="function"&&q=="new")g();else if(q==="return"||q==="throw")g();else if(r!=="TK_END_EXPR"){if((r!=="TK_START_EXPR"||u!=="var")&&q!==":")u==="if"&&A==="else"&&q!=="{"?g():(j.var_line=!1,j.var_line_reindented=!1,f())}else if(p(u,z)&&q!=")")j.var_line=!1,j.var_line_reindented=!1,f()}else n(j.mode)&&q===","&&w==="}"?f():
y==="SPACE"&&g();h();A=u;if(u==="var")j.var_line=!0,j.var_line_reindented=!1,j.var_line_tainted=!1;if(u==="if")j.if_line=!0;if(u==="else")j.if_line=!1;break;case "TK_SEMICOLON":h();j.var_line=!1;j.var_line_reindented=!1;if(j.mode=="OBJECT")j.mode="BLOCK";break;case "TK_STRING":r==="TK_START_BLOCK"||r==="TK_END_BLOCK"||r==="TK_SEMICOLON"?f():r==="TK_WORD"&&g();h();break;case "TK_EQUALS":if(j.var_line)j.var_line_tainted=!0;g();h();g();break;case "TK_OPERATOR":y=w=!0;if(j.var_line&&u===","&&s(j.mode))j.var_line_tainted=
!1;if(j.var_line&&u===",")if(j.var_line_tainted){h();j.var_line_reindented=!0;j.var_line_tainted=!1;f();break}else j.var_line_tainted=!1;if(q==="return"||q==="throw"){g();h();break}if(u===":"&&j.in_case){h();f();j.in_case=!1;break}if(u==="::"){h();break}if(u===","){j.var_line?j.var_line_tainted?(h(),f(),j.var_line_tainted=!1):(h(),g()):r==="TK_END_BLOCK"&&j.mode!=="(EXPRESSION)"?(h(),j.mode==="OBJECT"&&q==="}"?f():g()):j.mode==="OBJECT"?(h(),f()):(h(),g());break}else p(u,["--","++","!"])||p(u,["-",
"+"])&&(p(r,["TK_START_BLOCK","TK_START_EXPR","TK_EQUALS","TK_OPERATOR"])||p(q,z))?(y=w=!1,q===";"&&s(j.mode)&&(w=!0),r==="TK_WORD"&&p(q,z)&&(w=!0),j.mode==="BLOCK"&&(q==="{"||q===";")&&f()):u==="."?w=!1:u===":"?j.ternary_depth==0?(j.mode="OBJECT",w=!1):j.ternary_depth-=1:u==="?"&&(j.ternary_depth+=1);w&&g();h();y&&g();break;case "TK_BLOCK_COMMENT":w=u.split(/\x0a|\x0d\x0a/);if(t(w.slice(1),"*")){f();m.push(w[0]);for(y=1;y<w.length;y++)f(),m.push(" "),m.push(d(w[y]))}else{w.length>1?(f(),c()):g();
for(y=0;y<w.length;y++)m.push(w[y]),m.push("\n")}f();break;case "TK_INLINE_COMMENT":g();h();s(j.mode)?g():e();break;case "TK_COMMENT":N?f():g();h();e();break;case "TK_UNKNOWN":(q==="return"||q==="throw")&&g(),h()}w=q;r=M;q=u}return O+m.join("").replace(/[\n ]+$/,"")}if(typeof exports!=="undefined")exports.js_beautify=js_beautify;var glMatrixArrayType,vec3,mat3,mat4,quat4;glMatrixArrayType=typeof Float32Array!="undefined"?Float32Array:typeof WebGLFloatArray!="undefined"?WebGLFloatArray:Array;
vec3={create:function(a){var b=new glMatrixArrayType(3);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];return b},add:function(a,b,c){if(!c||a==c)return a[0]+=b[0],a[1]+=b[1],a[2]+=b[2],a;c[0]=a[0]+b[0];c[1]=a[1]+b[1];c[2]=a[2]+b[2];return c},subtract:function(a,b,c){if(!c||a==c)return a[0]-=b[0],a[1]-=b[1],a[2]-=b[2],a;c[0]=a[0]-b[0];c[1]=a[1]-b[1];c[2]=a[2]-b[2];return c},negate:function(a,b){b||(b=a);b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];return b},scale:function(a,
b,c){if(!c||a==c)return a[0]*=b,a[1]*=b,a[2]*=b,a;c[0]=a[0]*b;c[1]=a[1]*b;c[2]=a[2]*b;return c},normalize:function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],f=Math.sqrt(c*c+d*d+e*e);if(f){if(f==1)return b[0]=c,b[1]=d,b[2]=e,b}else return b[0]=0,b[1]=0,b[2]=0,b;f=1/f;b[0]=c*f;b[1]=d*f;b[2]=e*f;return b},cross:function(a,b,c){c||(c=a);var d=a[0],e=a[1],a=a[2],f=b[0],g=b[1],b=b[2];c[0]=e*b-a*g;c[1]=a*f-d*b;c[2]=d*g-e*f;return c},length:function(a){var b=a[0],c=a[1],a=a[2];return Math.sqrt(b*b+c*c+a*a)},
dot:function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]},direction:function(a,b,c){c||(c=a);var d=a[0]-b[0],e=a[1]-b[1],a=a[2]-b[2],b=Math.sqrt(d*d+e*e+a*a);if(!b)return c[0]=0,c[1]=0,c[2]=0,c;b=1/b;c[0]=d*b;c[1]=e*b;c[2]=a*b;return c},lerp:function(a,b,c,d){d||(d=a);d[0]=a[0]+c*(b[0]-a[0]);d[1]=a[1]+c*(b[1]-a[1]);d[2]=a[2]+c*(b[2]-a[2]);return d},str:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+"]"}};
mat3={create:function(a){var b=new glMatrixArrayType(9);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b[4]=a[4],b[5]=a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];return b},identity:function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=1;a[5]=0;a[6]=0;a[7]=0;a[8]=1;return a},transpose:function(a,b){if(!b||a==b){var c=a[1],d=a[2],e=a[5];a[1]=a[3];a[2]=a[6];a[3]=c;a[5]=a[7];a[6]=d;a[7]=e;return a}b[0]=a[0];
b[1]=a[3];b[2]=a[6];b[3]=a[1];b[4]=a[4];b[5]=a[7];b[6]=a[2];b[7]=a[5];b[8]=a[8];return b},toMat4:function(a,b){b||(b=mat4.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=0;b[4]=a[3];b[5]=a[4];b[6]=a[5];b[7]=0;b[8]=a[6];b[9]=a[7];b[10]=a[8];b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b},str:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+"]"}};
mat4={create:function(a){var b=new glMatrixArrayType(16);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b[4]=a[4],b[5]=a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8],b[9]=a[9],b[10]=a[10],b[11]=a[11],b[12]=a[12],b[13]=a[13],b[14]=a[14],b[15]=a[15]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=a[12];b[13]=a[13];b[14]=a[14];b[15]=a[15];return b},identity:function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=
1;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},transpose:function(a,b){if(!b||a==b){var c=a[1],d=a[2],e=a[3],f=a[6],g=a[7],h=a[11];a[1]=a[4];a[2]=a[8];a[3]=a[12];a[4]=c;a[6]=a[9];a[7]=a[13];a[8]=d;a[9]=f;a[11]=a[14];a[12]=e;a[13]=g;a[14]=h;return a}b[0]=a[0];b[1]=a[4];b[2]=a[8];b[3]=a[12];b[4]=a[1];b[5]=a[5];b[6]=a[9];b[7]=a[13];b[8]=a[2];b[9]=a[6];b[10]=a[10];b[11]=a[14];b[12]=a[3];b[13]=a[7];b[14]=a[11];b[15]=a[15];return b},determinant:function(a){var b=
a[0],c=a[1],d=a[2],e=a[3],f=a[4],g=a[5],h=a[6],i=a[7],k=a[8],n=a[9],s=a[10],v=a[11],t=a[12],p=a[13],x=a[14],a=a[15];return t*n*h*e-k*p*h*e-t*g*s*e+f*p*s*e+k*g*x*e-f*n*x*e-t*n*d*i+k*p*d*i+t*c*s*i-b*p*s*i-k*c*x*i+b*n*x*i+t*g*d*v-f*p*d*v-t*c*h*v+b*p*h*v+f*c*x*v-b*g*x*v-k*g*d*a+f*n*d*a+k*c*h*a-b*n*h*a-f*c*s*a+b*g*s*a},inverse:function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],f=a[3],g=a[4],h=a[5],i=a[6],k=a[7],n=a[8],s=a[9],v=a[10],t=a[11],p=a[12],x=a[13],o=a[14],m=a[15],u=c*h-d*g,r=c*i-e*g,q=c*k-f*g,w=
d*i-e*h,A=d*k-f*h,j=e*k-f*i,C=n*x-s*p,B=n*o-v*p,E=n*m-t*p,F=s*o-v*x,G=s*m-t*x,l=v*m-t*o,z=1/(u*l-r*G+q*F+w*E-A*B+j*C);b[0]=(h*l-i*G+k*F)*z;b[1]=(-d*l+e*G-f*F)*z;b[2]=(x*j-o*A+m*w)*z;b[3]=(-s*j+v*A-t*w)*z;b[4]=(-g*l+i*E-k*B)*z;b[5]=(c*l-e*E+f*B)*z;b[6]=(-p*j+o*q-m*r)*z;b[7]=(n*j-v*q+t*r)*z;b[8]=(g*G-h*E+k*C)*z;b[9]=(-c*G+d*E-f*C)*z;b[10]=(p*A-x*q+m*u)*z;b[11]=(-n*A+s*q-t*u)*z;b[12]=(-g*F+h*B-i*C)*z;b[13]=(c*F-d*B+e*C)*z;b[14]=(-p*w+x*r-o*u)*z;b[15]=(n*w-s*r+v*u)*z;return b}};
mat4.toRotationMat=function(a,b){b||(b=mat4.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b};mat4.toMat3=function(a,b){b||(b=mat3.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[4];b[4]=a[5];b[5]=a[6];b[6]=a[8];b[7]=a[9];b[8]=a[10];return b};
mat4.toInverseMat3=function(a,b){var c=a[0],d=a[1],e=a[2],f=a[4],g=a[5],h=a[6],i=a[8],k=a[9],n=a[10],s=n*g-h*k,v=-n*f+h*i,t=k*f-g*i,p=c*s+d*v+e*t;if(!p)return null;p=1/p;b||(b=mat3.create());b[0]=s*p;b[1]=(-n*d+e*k)*p;b[2]=(h*d-e*g)*p;b[3]=v*p;b[4]=(n*c-e*i)*p;b[5]=(-h*c+e*f)*p;b[6]=t*p;b[7]=(-k*c+d*i)*p;b[8]=(g*c-d*f)*p;return b};
mat4.multiply=function(a,b,c){c||(c=a);var d=a[0],e=a[1],f=a[2],g=a[3],h=a[4],i=a[5],k=a[6],n=a[7],s=a[8],v=a[9],t=a[10],p=a[11],x=a[12],o=a[13],m=a[14],a=a[15],u=b[0],r=b[1],q=b[2],w=b[3],A=b[4],j=b[5],C=b[6],B=b[7],E=b[8],F=b[9],G=b[10],l=b[11],z=b[12],L=b[13],y=b[14],b=b[15];c[0]=u*d+r*h+q*s+w*x;c[1]=u*e+r*i+q*v+w*o;c[2]=u*f+r*k+q*t+w*m;c[3]=u*g+r*n+q*p+w*a;c[4]=A*d+j*h+C*s+B*x;c[5]=A*e+j*i+C*v+B*o;c[6]=A*f+j*k+C*t+B*m;c[7]=A*g+j*n+C*p+B*a;c[8]=E*d+F*h+G*s+l*x;c[9]=E*e+F*i+G*v+l*o;c[10]=E*f+F*
k+G*t+l*m;c[11]=E*g+F*n+G*p+l*a;c[12]=z*d+L*h+y*s+b*x;c[13]=z*e+L*i+y*v+b*o;c[14]=z*f+L*k+y*t+b*m;c[15]=z*g+L*n+y*p+b*a;return c};mat4.multiplyVec3=function(a,b,c){c||(c=b);var d=b[0],e=b[1],b=b[2];c[0]=a[0]*d+a[4]*e+a[8]*b+a[12];c[1]=a[1]*d+a[5]*e+a[9]*b+a[13];c[2]=a[2]*d+a[6]*e+a[10]*b+a[14];return c};
mat4.multiplyVec4=function(a,b,c){c||(c=b);var d=b[0],e=b[1],f=b[2],b=b[3];c[0]=a[0]*d+a[4]*e+a[8]*f+a[12]*b;c[1]=a[1]*d+a[5]*e+a[9]*f+a[13]*b;c[2]=a[2]*d+a[6]*e+a[10]*f+a[14]*b;c[3]=a[3]*d+a[7]*e+a[11]*f+a[15]*b;return c};
mat4.translate=function(a,b,c){var d=b[0],e=b[1],b=b[2];if(!c||a==c)return a[12]=a[0]*d+a[4]*e+a[8]*b+a[12],a[13]=a[1]*d+a[5]*e+a[9]*b+a[13],a[14]=a[2]*d+a[6]*e+a[10]*b+a[14],a[15]=a[3]*d+a[7]*e+a[11]*b+a[15],a;var f=a[0],g=a[1],h=a[2],i=a[3],k=a[4],n=a[5],s=a[6],v=a[7],t=a[8],p=a[9],x=a[10],o=a[11];c[0]=f;c[1]=g;c[2]=h;c[3]=i;c[4]=k;c[5]=n;c[6]=s;c[7]=v;c[8]=t;c[9]=p;c[10]=x;c[11]=o;c[12]=f*d+k*e+t*b+a[12];c[13]=g*d+n*e+p*b+a[13];c[14]=h*d+s*e+x*b+a[14];c[15]=i*d+v*e+o*b+a[15];return c};
mat4.scale=function(a,b,c){var d=b[0],e=b[1],b=b[2];if(!c||a==c)return a[0]*=d,a[1]*=d,a[2]*=d,a[3]*=d,a[4]*=e,a[5]*=e,a[6]*=e,a[7]*=e,a[8]*=b,a[9]*=b,a[10]*=b,a[11]*=b,a;c[0]=a[0]*d;c[1]=a[1]*d;c[2]=a[2]*d;c[3]=a[3]*d;c[4]=a[4]*e;c[5]=a[5]*e;c[6]=a[6]*e;c[7]=a[7]*e;c[8]=a[8]*b;c[9]=a[9]*b;c[10]=a[10]*b;c[11]=a[11]*b;c[12]=a[12];c[13]=a[13];c[14]=a[14];c[15]=a[15];return c};
mat4.rotate=function(a,b,c,d){var e=c[0],f=c[1],c=c[2],g=Math.sqrt(e*e+f*f+c*c);if(!g)return null;g!=1&&(g=1/g,e*=g,f*=g,c*=g);var h=Math.sin(b),i=Math.cos(b),k=1-i,b=a[0],g=a[1],n=a[2],s=a[3],v=a[4],t=a[5],p=a[6],x=a[7],o=a[8],m=a[9],u=a[10],r=a[11],q=e*e*k+i,w=f*e*k+c*h,A=c*e*k-f*h,j=e*f*k-c*h,C=f*f*k+i,B=c*f*k+e*h,E=e*c*k+f*h,e=f*c*k-e*h,f=c*c*k+i;d?a!=d&&(d[12]=a[12],d[13]=a[13],d[14]=a[14],d[15]=a[15]):d=a;d[0]=b*q+v*w+o*A;d[1]=g*q+t*w+m*A;d[2]=n*q+p*w+u*A;d[3]=s*q+x*w+r*A;d[4]=b*j+v*C+o*B;d[5]=
g*j+t*C+m*B;d[6]=n*j+p*C+u*B;d[7]=s*j+x*C+r*B;d[8]=b*E+v*e+o*f;d[9]=g*E+t*e+m*f;d[10]=n*E+p*e+u*f;d[11]=s*E+x*e+r*f;return d};mat4.rotateX=function(a,b,c){var d=Math.sin(b),b=Math.cos(b),e=a[4],f=a[5],g=a[6],h=a[7],i=a[8],k=a[9],n=a[10],s=a[11];c?a!=c&&(c[0]=a[0],c[1]=a[1],c[2]=a[2],c[3]=a[3],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[4]=e*b+i*d;c[5]=f*b+k*d;c[6]=g*b+n*d;c[7]=h*b+s*d;c[8]=e*-d+i*b;c[9]=f*-d+k*b;c[10]=g*-d+n*b;c[11]=h*-d+s*b;return c};
mat4.rotateY=function(a,b,c){var d=Math.sin(b),b=Math.cos(b),e=a[0],f=a[1],g=a[2],h=a[3],i=a[8],k=a[9],n=a[10],s=a[11];c?a!=c&&(c[4]=a[4],c[5]=a[5],c[6]=a[6],c[7]=a[7],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[0]=e*b+i*-d;c[1]=f*b+k*-d;c[2]=g*b+n*-d;c[3]=h*b+s*-d;c[8]=e*d+i*b;c[9]=f*d+k*b;c[10]=g*d+n*b;c[11]=h*d+s*b;return c};
mat4.rotateZ=function(a,b,c){var d=Math.sin(b),b=Math.cos(b),e=a[0],f=a[1],g=a[2],h=a[3],i=a[4],k=a[5],n=a[6],s=a[7];c?a!=c&&(c[8]=a[8],c[9]=a[9],c[10]=a[10],c[11]=a[11],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[0]=e*b+i*d;c[1]=f*b+k*d;c[2]=g*b+n*d;c[3]=h*b+s*d;c[4]=e*-d+i*b;c[5]=f*-d+k*b;c[6]=g*-d+n*b;c[7]=h*-d+s*b;return c};
mat4.frustum=function(a,b,c,d,e,f,g){g||(g=mat4.create());var h=b-a,i=d-c,k=f-e;g[0]=e*2/h;g[1]=0;g[2]=0;g[3]=0;g[4]=0;g[5]=e*2/i;g[6]=0;g[7]=0;g[8]=(b+a)/h;g[9]=(d+c)/i;g[10]=-(f+e)/k;g[11]=-1;g[12]=0;g[13]=0;g[14]=-(f*e*2)/k;g[15]=0;return g};mat4.perspective=function(a,b,c,d,e,f){a=c*Math.tan(a*Math.PI/360);b*=a;return mat4.frustum(-b,b,-a*(f?-1:1),a*(f?-1:1),c,d,e)};
mat4.ortho=function(a,b,c,d,e,f,g){g||(g=mat4.create());var h=b-a,i=d-c,k=f-e;g[0]=2/h;g[1]=0;g[2]=0;g[3]=0;g[4]=0;g[5]=2/i;g[6]=0;g[7]=0;g[8]=0;g[9]=0;g[10]=-2/k;g[11]=0;g[12]=-(a+b)/h;g[13]=-(d+c)/i;g[14]=-(f+e)/k;g[15]=1;return g};
mat4.lookAt=function(a,b,c,d){d||(d=mat4.create());var e=a[0],f=a[1],a=a[2],g=c[0],h=c[1],i=c[2],c=b[1],k=b[2];if(e==b[0]&&f==c&&a==k)return mat4.identity(d);var n,s,v,t,c=e-b[0],k=f-b[1],b=a-b[2];t=1/Math.sqrt(c*c+k*k+b*b);c*=t;k*=t;b*=t;n=h*b-i*k;i=i*c-g*b;g=g*k-h*c;(t=Math.sqrt(n*n+i*i+g*g))?(t=1/t,n*=t,i*=t,g*=t):g=i=n=0;h=k*g-b*i;s=b*n-c*g;v=c*i-k*n;(t=Math.sqrt(h*h+s*s+v*v))?(t=1/t,h*=t,s*=t,v*=t):v=s=h=0;d[0]=n;d[1]=h;d[2]=c;d[3]=0;d[4]=i;d[5]=s;d[6]=k;d[7]=0;d[8]=g;d[9]=v;d[10]=b;d[11]=0;
d[12]=-(n*e+i*f+g*a);d[13]=-(h*e+s*f+v*a);d[14]=-(c*e+k*f+b*a);d[15]=1;return d};mat4.str=function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+", "+a[9]+", "+a[10]+", "+a[11]+", "+a[12]+", "+a[13]+", "+a[14]+", "+a[15]+"]"};
quat4={create:function(a){var b=new glMatrixArrayType(4);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];return b},calculateW:function(a,b){var c=a[0],d=a[1],e=a[2];if(!b||a==b)return a[3]=-Math.sqrt(Math.abs(1-c*c-d*d-e*e)),a;b[0]=c;b[1]=d;b[2]=e;b[3]=-Math.sqrt(Math.abs(1-c*c-d*d-e*e));return b},inverse:function(a,b){if(!b||a==b)return a[0]*=-1,a[1]*=-1,a[2]*=-1,a;b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];b[3]=a[3];return b},length:function(a){var b=
a[0],c=a[1],d=a[2],a=a[3];return Math.sqrt(b*b+c*c+d*d+a*a)},normalize:function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],f=a[3],g=Math.sqrt(c*c+d*d+e*e+f*f);if(g==0)return b[0]=0,b[1]=0,b[2]=0,b[3]=0,b;g=1/g;b[0]=c*g;b[1]=d*g;b[2]=e*g;b[3]=f*g;return b},multiply:function(a,b,c){c||(c=a);var d=a[0],e=a[1],f=a[2],a=a[3],g=b[0],h=b[1],i=b[2],b=b[3];c[0]=d*b+a*g+e*i-f*h;c[1]=e*b+a*h+f*g-d*i;c[2]=f*b+a*i+d*h-e*g;c[3]=a*b-d*g-e*h-f*i;return c},multiplyVec3:function(a,b,c){c||(c=b);var d=b[0],e=b[1],f=b[2],
b=a[0],g=a[1],h=a[2],a=a[3],i=a*d+g*f-h*e,k=a*e+h*d-b*f,n=a*f+b*e-g*d,d=-b*d-g*e-h*f;c[0]=i*a+d*-b+k*-h-n*-g;c[1]=k*a+d*-g+n*-b-i*-h;c[2]=n*a+d*-h+i*-g-k*-b;return c},toMat3:function(a,b){b||(b=mat3.create());var c=a[0],d=a[1],e=a[2],f=a[3],g=c+c,h=d+d,i=e+e,k=c*g,n=c*h;c*=i;var s=d*h;d*=i;e*=i;g*=f;h*=f;f*=i;b[0]=1-(s+e);b[1]=n-f;b[2]=c+h;b[3]=n+f;b[4]=1-(k+e);b[5]=d-g;b[6]=c-h;b[7]=d+g;b[8]=1-(k+s);return b},toMat4:function(a,b){b||(b=mat4.create());var c=a[0],d=a[1],e=a[2],f=a[3],g=c+c,h=d+d,i=
e+e,k=c*g,n=c*h;c*=i;var s=d*h;d*=i;e*=i;g*=f;h*=f;f*=i;b[0]=1-(s+e);b[1]=n-f;b[2]=c+h;b[3]=0;b[4]=n+f;b[5]=1-(k+e);b[6]=d-g;b[7]=0;b[8]=c-h;b[9]=d+g;b[10]=1-(k+s);b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b},slerp:function(a,b,c,d){d||(d=a);var e=a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3];if(Math.abs(e)>=1)return d!=a&&(d[0]=a[0],d[1]=a[1],d[2]=a[2],d[3]=a[3]),d;var f=Math.acos(e),g=Math.sqrt(1-e*e);if(Math.abs(g)<0.0010)return d[0]=a[0]*0.5+b[0]*0.5,d[1]=a[1]*0.5+b[1]*0.5,d[2]=a[2]*0.5+b[2]*0.5,
d[3]=a[3]*0.5+b[3]*0.5,d;e=Math.sin((1-c)*f)/g;c=Math.sin(c*f)/g;d[0]=a[0]*e+b[0]*c;d[1]=a[1]*e+b[1]*c;d[2]=a[2]*e+b[2]*c;d[3]=a[3]*e+b[3]*c;return d},str:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+"]"}};var JSON;JSON||(JSON={});
(function(){function a(a){return a<10?"0"+a:a}function b(a){e.lastIndex=0;return e.test(a)?'"'+a.replace(e,function(a){var b=h[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,d){var e,h,t,p,x=f,o,m=d[a];m&&typeof m==="object"&&typeof m.toJSON==="function"&&(m=m.toJSON(a));typeof i==="function"&&(m=i.call(d,a,m));switch(typeof m){case "string":return b(m);case "number":return isFinite(m)?String(m):"null";case "boolean":case "null":return String(m);
case "object":if(!m)return"null";f+=g;o=[];if(Object.prototype.toString.apply(m)==="[object Array]"){p=m.length;for(e=0;e<p;e+=1)o[e]=c(e,m)||"null";t=o.length===0?"[]":f?"[\n"+f+o.join(",\n"+f)+"\n"+x+"]":"["+o.join(",")+"]";f=x;return t}if(i&&typeof i==="object"){p=i.length;for(e=0;e<p;e+=1)typeof i[e]==="string"&&(h=i[e],(t=c(h,m))&&o.push(b(h)+(f?": ":":")+t))}else for(h in m)Object.prototype.hasOwnProperty.call(m,h)&&(t=c(h,m))&&o.push(b(h)+(f?": ":":")+t);t=o.length===0?"{}":f?"{\n"+f+o.join(",\n"+
f)+"\n"+x+"}":"{"+o.join(",")+"}";f=x;return t}}if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var d=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,f,g,h={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},i;if(typeof JSON.stringify!=="function")JSON.stringify=function(a,b,d){var e;g=f="";if(typeof d==="number")for(e=0;e<d;e+=1)g+=" ";else typeof d==="string"&&(g=d);if((i=b)&&typeof b!=="function"&&(typeof b!=="object"||typeof b.length!=="number"))throw Error("JSON.stringify");return c("",
{"":a})};if(typeof JSON.parse!=="function")JSON.parse=function(a,b){function c(a,d){var e,f,g=a[d];if(g&&typeof g==="object")for(e in g)Object.prototype.hasOwnProperty.call(g,e)&&(f=c(g,e),f!==void 0?g[e]=f:delete g[e]);return b.call(a,d,g)}var e,a=String(a);d.lastIndex=0;d.test(a)&&(a=a.replace(d,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),typeof b==="function"?c({"":e},""):e;throw new SyntaxError("JSON.parse");}})();Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Cube"];
Tilt.Cube=function(a,b,c){a=a||1;b=b||1;c=c||1;this.vertices=new Tilt.VertexBuffer([-0.5*a,-0.5*b,0.5*c,0.5*a,-0.5*b,0.5*c,0.5*a,0.5*b,0.5*c,-0.5*a,0.5*b,0.5*c,-0.5*a,0.5*b,0.5*c,0.5*a,0.5*b,0.5*c,0.5*a,0.5*b,-0.5*c,-0.5*a,0.5*b,-0.5*c,0.5*a,-0.5*b,-0.5*c,-0.5*a,-0.5*b,-0.5*c,-0.5*a,0.5*b,-0.5*c,0.5*a,0.5*b,-0.5*c,-0.5*a,-0.5*b,-0.5*c,0.5*a,-0.5*b,-0.5*c,0.5*a,-0.5*b,0.5*c,-0.5*a,-0.5*b,0.5*c,0.5*a,-0.5*b,0.5*c,0.5*a,-0.5*b,-0.5*c,0.5*a,0.5*b,-0.5*c,0.5*a,0.5*b,0.5*c,-0.5*a,-0.5*b,-0.5*c,-0.5*a,-0.5*
b,0.5*c,-0.5*a,0.5*b,0.5*c,-0.5*a,0.5*b,-0.5*c],3);this.texCoord=new Tilt.VertexBuffer([0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1],2);this.indices=new Tilt.IndexBuffer([0,1,2,0,2,3,4,5,6,4,6,7,8,9,10,8,10,11,12,13,14,12,14,15,16,17,18,16,18,19,20,21,22,20,22,23])};Tilt.Cube.prototype={destroy:function(){for(var a in this)try{"function"===typeof this[a].destroy&&this[a].destroy()}catch(b){}finally{delete this[a]}}};Tilt=Tilt||{};
EXPORTED_SYMBOLS=["Tilt.CubeWireframe"];Tilt.CubeWireframe=function(a,b,c){a=a||1;b=b||1;c=c||1;this.vertices=new Tilt.VertexBuffer([-0.5*a,-0.5*b,0.5*c,0.5*a,-0.5*b,0.5*c,0.5*a,0.5*b,0.5*c,-0.5*a,0.5*b,0.5*c,0.5*a,-0.5*b,-0.5*c,-0.5*a,-0.5*b,-0.5*c,-0.5*a,0.5*b,-0.5*c,0.5*a,0.5*b,-0.5*c],3);this.indices=new Tilt.IndexBuffer([0,1,1,2,2,3,3,0,4,5,5,6,6,7,7,4,0,5,1,4,2,7,3,6])};Tilt.CubeWireframe.prototype={destroy:function(){for(var a in this)try{"function"===typeof this[a].destroy&&this[a].destroy()}catch(b){}finally{delete this[a]}}};
Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Rectangle"];Tilt.Rectangle=function(){this.vertices=new Tilt.VertexBuffer([0,0,1,0,0,1,1,1],2);this.texCoord=new Tilt.VertexBuffer([0,0,1,0,0,1,1,1],2)};Tilt.Rectangle.prototype={destroy:function(){for(var a in this)try{"function"===typeof this[a].destroy&&this[a].destroy()}catch(b){}finally{delete this[a]}}};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.RectangleWireframe"];
Tilt.RectangleWireframe=function(){this.vertices=new Tilt.VertexBuffer([0,0,1,0,1,1,0,1,0,0],2)};Tilt.RectangleWireframe.prototype={destroy:function(){for(var a in this)try{"function"===typeof this[a].destroy&&this[a].destroy()}catch(b){}finally{delete this[a]}}};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Mesh"];
Tilt.Mesh=function(a,b){for(var c in a)this[c]=a[c];if("string"===typeof this.color)this.color=Tilt.Math.hex2rgba(this.color);else if("undefined"===typeof this.color)this.color=[1,1,1,1];if("undefined"===typeof this.drawMode)this.drawMode=Tilt.$renderer.TRIANGLES;if("function"===typeof b)this.draw=b};
Tilt.Mesh.prototype={draw:function(){var a=Tilt.$renderer,b=this.vertices,c=this.texCoord,d=this.indices,e=this.color,f=this.texture,g=this.drawMode;f?a.useTextureShader(b,c,e,f):a.useColorShader(b,e);d?a.drawIndexedVertices(g,d):a.drawVertices(g,b.numItems);this.mvMatrix=mat4.create(a.mvMatrix);this.projMatrix=mat4.create(a.projMatrix)},destroy:function(){for(var a in this)try{"function"===typeof this[a].destroy&&this[a].destroy()}catch(b){}finally{delete this[a]}}};Tilt=Tilt||{};
EXPORTED_SYMBOLS=["Tilt.Renderer"];
Tilt.Renderer=function(a,b,c){this.canvas=a;this.gl=this.create3DContext(a);Tilt.clearCache();Tilt.$gl=this.gl;Tilt.$renderer=this;"undefined"!==typeof this.gl?(this.TRIANGLES=this.gl.TRIANGLES,this.TRIANGLE_STRIP=this.gl.TRIANGLE_STRIP,this.TRIANGLE_FAN=this.gl.TRIANGLE_FAN,this.LINES=this.gl.LINES,this.LINE_STRIP=this.gl.LINE_STRIP,this.LINE_LOOP=this.gl.LINE_LOOP,this.POINTS=this.gl.POINTS,this.COLOR_BUFFER_BIT=this.gl.COLOR_BUFFER_BIT,this.DEPTH_BUFFER_BIT=this.gl.DEPTH_BUFFER_BIT,this.STENCIL_BUFFER_BIT=
this.gl.STENCIL_BUFFER_BIT,"function"===typeof c&&c()):(Tilt.Console.log(Tilt.StringBundle.get("initWebGL.error")),"function"===typeof b&&b());this.width=a.width;this.height=a.height;this.mvMatrixStack=[];this.mvMatrix=mat4.identity(mat4.create());this.projMatrix=mat4.identity(mat4.create());this.clearColor=[0,0,0,0];this.tintColor=[0,0,0,0];this.fillColor=[0,0,0,0];this.strokeColor=[0,0,0,0];this.strokeWeightValue=0;this.colorShader=new Tilt.Program(Tilt.Shaders.Color.vs,Tilt.Shaders.Color.fs);this.textureShader=
new Tilt.Program(Tilt.Shaders.Texture.vs,Tilt.Shaders.Texture.fs);this.rectangle=new Tilt.Rectangle;this.rectangleWireframe=new Tilt.RectangleWireframe;this.cube=new Tilt.Cube;this.cubeWireframe=new Tilt.CubeWireframe;this.lastTime=0;this.currentTime=null;this.frameDelta=this.frameRate=this.frameCount=this.elapsedTime=0;this.origin();this.perspective();this.defaults()};
Tilt.Renderer.prototype={clear:function(a,b,c,d){var e=this.clearColor,f=this.gl;if(e[0]!==a||e[1]!==b||e[2]!==c||e[3]!==d)e[0]=a,e[1]=b,e[2]=c,e[3]=d,f.clearColor(a,b,c,d),a*=255,b*=255,c*=255,d*=255,this.canvas.setAttribute("style","background: rgba("+a+", "+b+", "+c+", "+d+"); width: 100%; height: 100%;");f.clear(f.COLOR_BUFFER_BIT|f.DEPTH_BUFFER_BIT)},background:function(a){a="string"===typeof a?Tilt.Math.hex2rgba(a):"undefined"===typeof a?[0,0,0,1]:"number"===typeof a?[a/255,a/255,a/255,1]:[a[0]/
255,a[1]/255,a[2]/255,a[3]/255];this.clear(a[0],a[1],a[2],a[3])},perspective:function(){var a=this.width,b=this.height,c=a/2,d=b/2,e=d/Math.tan(Tilt.Math.radians(45)/2);mat4.perspective(45,a/b,e/10,e*100,this.projMatrix,!0);mat4.translate(this.projMatrix,[-c,-d,-e])},ortho:function(){mat4.ortho(0,this.width,this.height,0,-1E3,1E3,this.projMatrix)},projection:function(a){mat4.set(a,this.projMatrix)},pushMatrix:function(){this.mvMatrixStack.push(mat4.create(this.mvMatrix))},popMatrix:function(){if(this.mvMatrixStack.length>
0)this.mvMatrix=this.mvMatrixStack.pop()},origin:function(){mat4.identity(this.mvMatrix)},transform:function(a){mat4.multiply(this.mvMatrix,a)},translate:function(a,b,c){mat4.translate(this.mvMatrix,[a,b,c||0])},rotate:function(a,b,c,d){mat4.rotate(this.mvMatrix,a,[b,c,d])},rotateX:function(a){mat4.rotateX(this.mvMatrix,a)},rotateY:function(a){mat4.rotateY(this.mvMatrix,a)},rotateZ:function(a){mat4.rotateZ(this.mvMatrix,a)},scale:function(a,b,c){mat4.scale(this.mvMatrix,[a,b,c||0])},defaults:function(){this.blendMode("alpha");
this.depthTest(!1);this.tint("#fff");this.fill("#fff");this.stroke("#000");this.strokeWeight(1)},tint:function(a){this.tintColor=Tilt.Math.hex2rgba(a)},noTint:function(){var a=this.tintColor;a[0]=1;a[1]=1;a[2]=1;a[3]=1},fill:function(a){this.fillColor=Tilt.Math.hex2rgba(a)},noFill:function(){var a=this.fillColor;a[0]=0;a[1]=0;a[2]=0;a[3]=0},stroke:function(a){this.strokeColor=Tilt.Math.hex2rgba(a)},noStroke:function(){var a=this.strokeColor;a[0]=0;a[1]=0;a[2]=0;a[3]=0},strokeWeight:function(a){if(this.strokeWeightValue!==
a)this.strokeWeightValue=a,this.gl.lineWidth(a)},blendMode:function(a){var b=this.gl;"alpha"===a?(b.enable(b.BLEND),b.blendFunc(b.SRC_ALPHA,b.ONE_MINUS_SRC_ALPHA)):"add"===a||"additive"===a?(b.enable(b.BLEND),b.blendFunc(b.SRC_ALPHA,b.ONE)):b.disable(b.BLEND)},depthTest:function(a){var b=this.gl;a?b.enable(b.DEPTH_TEST):b.disable(b.DEPTH_TEST)},useColorShader:function(a,b){var c=this.colorShader;c.use();c.bindVertexBuffer("vertexPosition",a);c.bindUniformMatrix("mvMatrix",this.mvMatrix);c.bindUniformMatrix("projMatrix",
this.projMatrix);c.bindUniformVec4("color",b)},useTextureShader:function(a,b,c,d){var e=this.textureShader;e.use();e.bindVertexBuffer("vertexPosition",a);e.bindVertexBuffer("vertexTexCoord",b);e.bindUniformMatrix("mvMatrix",this.mvMatrix);e.bindUniformMatrix("projMatrix",this.projMatrix);e.bindUniformVec4("color",c);e.bindTexture("sampler",d)},triangle:function(a,b,c){a=new Tilt.VertexBuffer(a.concat(b,c),3);b=this.fillColor;c=this.strokeColor;c[3]&&(this.useColorShader(a,c),this.drawVertices(this.LINE_LOOP,
a.numItems));b[3]&&(this.useColorShader(a,b),this.drawVertices(this.TRIANGLE_STRIP,a.numItems))},rectMode:function(a){this.rectangle.rectModeValue=a},rect:function(a,b,c,d){var e=this.rectangle,f=this.rectangleWireframe,g=this.fillColor,h=this.strokeColor;"center"===this.rectangle.rectModeValue&&(a-=c/2,b-=d/2);this.pushMatrix();this.translate(a,b,0);this.scale(c,d,1);h[3]&&(this.useColorShader(f.vertices,h),this.drawVertices(this.LINE_STRIP,f.vertices.numItems));g[3]&&(this.useColorShader(e.vertices,
g),this.drawVertices(this.TRIANGLE_STRIP,e.vertices.numItems));this.popMatrix()},imageMode:function(a){this.rectangle.imageModeValue=a},image:function(a,b,c,d,e,f){var g=this.rectangle,h=this.tintColor,f=f||g.texCoord;if("undefined"===typeof d||"undefined"===typeof e)d=a.width,e=a.height;"center"===g.imageModeValue&&(b-=d/2,c-=e/2);h[3]&&(this.pushMatrix(),this.translate(b,c,0),this.scale(d,e,1),this.useTextureShader(g.vertices,f,h,a),this.drawVertices(this.TRIANGLE_STRIP,g.vertices.numItems),this.popMatrix())},
box:function(a,b,c,d){var e=this.cube,f=this.cubeWireframe,g=this.tintColor,h=this.fillColor,i=this.strokeColor;this.pushMatrix();this.scale(a,b,c);i[3]&&(this.useColorShader(f.vertices,i),this.drawIndexedVertices(this.LINES,f.indices));d?g[3]&&(this.useTextureShader(e.vertices,e.texCoord,g,d),this.drawIndexedVertices(this.TRIANGLES,e.indices)):h[3]&&(this.useColorShader(e.vertices,h),this.drawIndexedVertices(this.TRIANGLES,e.indices));this.popMatrix()},drawVertices:function(a,b){this.gl.drawArrays(a,
0,b)},drawIndexedVertices:function(a,b){var c=this.gl;c.bindBuffer(c.ELEMENT_ARRAY_BUFFER,b.ref);c.drawElements(a,b.numItems,c.UNSIGNED_SHORT,0)},create3DContext:function(a,b){var c=["experimental-webgl","webgl","webkit-3d","moz-webgl"],d,e,f;e=0;for(f=c.length;e<f;++e){try{d=a.getContext(c[e],b)}catch(g){}if(d)break}return d},loop:function(a){window.requestAnimFrame(a);this.origin();this.perspective();this.currentTime=(new Date).getTime();if(this.lastTime!==0)this.frameDelta=this.currentTime-this.lastTime,
this.frameRate=1E3/this.frameDelta;this.lastTime=this.currentTime;this.elapsedTime+=this.frameDelta;this.frameCount++},destroy:function(){Tilt.clearCache();for(var a in this)try{"function"===typeof this[a].destroy&&this[a].destroy()}catch(b){}finally{delete this[a]}}};
window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Shaders.Color"];Tilt.Shaders={};
Tilt.Shaders.Color={vs:"attribute vec3 vertexPosition;\nuniform mat4 mvMatrix;\nuniform mat4 projMatrix;\nvoid main(void) {\n    gl_Position = projMatrix * mvMatrix * vec4(vertexPosition, 1.0);\n}",fs:"#ifdef GL_ES\nprecision highp float;\n#endif\nuniform vec4 color;\nvoid main(void) {\n    gl_FragColor = color;\n}"};
Tilt.Shaders.Texture={vs:"attribute vec3 vertexPosition;\nattribute vec2 vertexTexCoord;\nuniform mat4 mvMatrix;\nuniform mat4 projMatrix;\nvarying vec2 texCoord;\nvoid main(void) {\n  gl_Position = projMatrix * mvMatrix * vec4(vertexPosition, 1.0);\n  texCoord = vertexTexCoord;\n}",fs:"#ifdef GL_ES\nprecision highp float;\n#endif\nuniform vec4 color;\nuniform sampler2D sampler;\nvarying vec2 texCoord;\nvoid main(void) {\n  vec4 tex = texture2D(sampler, vec2(texCoord.s, texCoord.t));\n  gl_FragColor = color * tex;\n}"};
Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Console","Tilt.StringBundle"];
Tilt.Console={log:function(a){"undefined"===typeof a&&(a="undefined");try{Components.classes["@mozilla.org/consoleservice;1"].getService(Components.interfaces.nsIConsoleService).logStringMessage(a)}catch(b){alert(a)}},error:function(a,b,c,d,e,f,g){"undefined"===typeof a&&(a="undefined");try{var h=Components.classes["@mozilla.org/consoleservice;1"].getService(Components.interfaces.nsIConsoleService),i=Components.classes["@mozilla.org/scripterror;1"].createInstance(Components.interfaces.nsIScriptError);i.init(a,
b,c,d,e,f,g);h.logMessage(i)}catch(k){alert(a)}}};Tilt.StringBundle={bundle:"tilt-string-bundle",get:function(a){if("undefined"===typeof a)return"undefined";var b=document.getElementById(this.bundle);return b?b.getString(a):a},format:function(a,b){if("undefined"===typeof a)return"undefined";if("undefined"===typeof b)return a;var c=document.getElementById(this.bundle);return c?c.getFormattedString(a,b):[a,b].join(" ")}};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Document"];
Tilt.Document={currentContentDocument:void 0,currentParentNode:void 0,initCanvas:function(a,b,c,d){if("undefined"===typeof this.currentContentDocument)this.currentContentDocument=document;if("undefined"===typeof this.currentParentNode)this.currentParentNode=document.body;var e=this.currentParentNode,f=this.currentContentDocument.createElement("canvas");f.setAttribute("style","width: 100%; height: 100%;");f.width=a;f.height=b;f.id=d;c&&this.append(f,e);return f},initFullScreenCanvas:function(){var a=
this.initCanvas(window.innerWidth,window.innerHeight,!0);this.currentParentNode.setAttribute("style","background:#000; margin: 0px; padding: 0px; overflow: hidden;");return a},append:function(a,b){b.appendChild(a)},remove:function(a){a.parentNode.removeChild(a)},traverse:function(a,b,c){function d(a,b,c){var i,k,n;i=0;for(k=b.childNodes.length;i<k;i++)n=b.childNodes[i],c>e&&(e=c),a(n,c),d(a,n,c+1)}var e=0;try{"function"===typeof a&&d(a,c||window.content.document,0),"function"===typeof b&&b(e)}finally{c=
null}},getNodeCoordinates:function(a){try{if(a.localName==="head"||a.localName==="body")throw new Exception;var b=a.getBoundingClientRect();return{x:b.left+window.content.pageXOffset,y:b.top+window.content.pageYOffset,width:b.width,height:b.height}}catch(c){var d=b=0,e=a.clientWidth,f=a.clientHeight;if(a.offsetParent){do b+=a.offsetLeft,d+=a.offsetTop;while(a=a.offsetParent)}else{if(a.x)b=a.x;if(a.y)d=a.y}return{x:b,y:d,width:e,height:f}}finally{}},getNodeType:function(a){var b;a.nodeType===1?b="ELEMENT_NODE":
a.nodeType===2?b="ATTRIBUTE_NODE":a.nodeType===3?b="TEXT_NODE":a.nodeType===4?b="CDATA_SECTION_NODE":a.nodeType===5?b="ENTITY_REFERENCE_NODE":a.nodeType===6?b="ENTITY_NODE":a.nodeType===7?b="PROCESSING_INSTRUCTION_NODE":a.nodeType===8?b="COMMENT_NODE":a.nodeType===9?b="DOCUMENT_NODE":a.nodeType===10?b="DOCUMENT_TYPE_NODE":a.nodeType===11?b="DOCUMENT_FRAGMENT_NODE":a.nodeType===12&&(b="NOTATION_NODE");return b}};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Math"];
Tilt.Math={radians:function(a){return a*Math.PI/180},degrees:function(a){return a*180/Math.PI},isPowerOfTwo:function(a){return(a&a-1)===0},nextPowerOfTwo:function(a){var b;--a;for(b=1;b<32;b<<=1)a|=a>>b;return a+1},clamp:function(a,b,c){return Math.max(b,Math.min(c,a))},quat4fromAxis:function(a,b,c){b*=0.5;var d=Math.sin(b),e=a[0]*d,f=a[1]*d,a=a[2]*d,b=Math.cos(b);return"undefined"===typeof c?[e,f,a,b]:(c[0]=e,c[1]=f,c[2]=a,c[3]=b,c)},quat4fromEuler:function(a,b,c,d){var e;b*=0.5;a*=0.5;c*=0.5;e=
Math.sin(b);var f=Math.sin(a),g=Math.sin(c),h=Math.cos(b),i=Math.cos(a),k=Math.cos(c),b=e*i*k-h*f*g,a=h*f*k+e*i*g,c=h*i*g-e*f*k;e=h*i*k+e*f*g;return"undefined"===typeof d?[b,a,c,e]:(d[0]=b,d[1]=a,d[2]=c,d[3]=e,d)},unproject:function(a,b,c,d,e){var f=mat4.create(),e=e||quat4.create();mat4.multiply(d,c,f);mat4.inverse(f);e[0]=+((a[0]-b[0])/b[2]*2-1);e[1]=-((a[1]-b[1])/b[3]*2-1);e[2]=2*a[2]-1;e[3]=1;mat4.multiplyVec4(f,e);e[3]=1/e[3];e[0]*=e[3];e[1]*=e[3];e[2]*=e[3];return e},createRay:function(a,b,
c,d,e){this.unproject(a,c,d,e,a);this.unproject(b,c,d,e,b);return{position:a,lookAt:b,direction:vec3.normalize(vec3.subtract(b,a))}},intersectRayTriangle:function(a,b,c,d,e){var f=vec3.create(),g=vec3.create(),h=vec3.create(),i=vec3.create(),k=vec3.create(),n=d.position,d=d.direction;"undefined"===typeof e&&(e=vec3.create());vec3.subtract(b,a,f);vec3.subtract(c,a,g);vec3.cross(f,g,h);if(h[0]===0&&h[1]===0&&h[2]===0)return-1;vec3.subtract(n,a,k);b=-vec3.dot(h,k);h=+vec3.dot(h,d);if(Math.abs(h)<1.0E-4)return b==
0?2:0;h=b/h;if(h<0)return 0;vec3.add(n,vec3.scale(d,h),e);n=vec3.dot(f,f);d=vec3.dot(f,g);h=vec3.dot(g,g);vec3.subtract(e,a,i);a=vec3.dot(i,f);g=vec3.dot(i,g);i=d*d-n*h;e=(d*g-h*a)/i;if(e<0||e>1)return 0;g=(d*a-n*g)/i;return g<0||e+g>1?0:1},hex2rgba:function(a){if("undefined"!==typeof this[a])return this[a];var b,c,d,e;b=a.charAt(0)==="#"?a.substring(1):a;if(b.length===3)c=b.charAt(0),d=b.charAt(1),e=b.charAt(2),b=[c,c,d,d,e,e,"ff"].join("");else if(b.length===4)c=b.charAt(0),d=b.charAt(1),e=b.charAt(2),
b=b.charAt(3),b=[c,c,d,d,e,e,b,b].join("");else if(b.match("^rgba")=="rgba")return b=b.substring(5,b.length-1).split(","),b[0]/=255,b[1]/=255,b[2]/=255,b[3]/=255,this[a]=b;else if(b.match("^rgb")=="rgb")return b=b.substring(4,b.length-1).split(","),b[0]/=255,b[1]/=255,b[2]/=255,b[3]=1,this[a]=b;c=parseInt(b.substring(0,2),16)/255;d=parseInt(b.substring(2,4),16)/255;e=parseInt(b.substring(4,6),16)/255;b=b.length===6?1:parseInt(b.substring(6,8),16)/255;this[a]=[c,d,e,b];return[c,d,e,b]}};
Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.String"];Tilt.String={trim:function(a){return a.replace(/^\s+|\s+$/g,"")},ltrim:function(a){return a.replace(/^\s+/,"")},rtrim:function(a){return a.replace(/\s+$/,"")}};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Extensions.WebGL"];Tilt.Extensions={};
Tilt.Extensions.WebGL={initDocumentImage:function(a){var b,c,d,e;b=Tilt.Document.initCanvas();c=Tilt.Document.initCanvas();b=Tilt.Renderer.prototype.create3DContext(b);b=b.getParameter(b.MAX_TEXTURE_SIZE);d=a.innerWidth+a.scrollMaxX;e=a.innerHeight+a.scrollMaxY;d=Tilt.Math.clamp(d,0,b);b=Tilt.Math.clamp(e,0,b);c.width=d;c.height=b;c.getContext("2d").drawWindow(a,0,0,d,b,"#fff");return c}};Tilt=Tilt||{};EXPORTED_SYMBOLS=["Tilt.Xhr"];
Tilt.Xhr={request:function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.send(null);d.onreadystatechange=function(){d.readyState===4&&"function"===typeof b&&b(d,c)}},requests:function(a,b,c){function d(d,g){e[g]=d;f++;f===a.length&&"function"===typeof b&&b(e,c)}var e=[],f=0,g,h;g=0;for(h=a.length;g<h;g++)this.request(a[g],d,g)}};
